//! Idea catalog data for the C3I AG-UI idea generator.
//!
//! Contains all 200 ideas across 10 categories with multi-dimensional scoring.

// =============================================================================
// Types
// =============================================================================

pub struct Idea {
    pub id: usize,
    pub title: &'static str,
    pub source: &'static str,
    pub desc: &'static str,
    pub zenoh: &'static str,
    pub crit: u8,
    pub usab: u8,
    pub info: u8,
    pub ux: u8,
}

// =============================================================================
// Category Registry
// =============================================================================

pub static CATEGORIES: &[(usize, usize, &str)] = &[
    (1, 20, "Category 1: AG-UI Core Event Integration"),
    (21, 40, "Category 2: Zenoh A2A Agent Communication"),
    (41, 60, "Category 3: Generative UI Widgets"),
    (61, 80, "Category 4: Human-in-the-Loop & Safety"),
    (81, 100, "Category 5: Dark Cockpit & Situational Awareness"),
    (101, 120, "Category 6: OTel Golden Triangle"),
    (121, 140, "Category 7: MCP Tool Ecosystem"),
    (141, 160, "Category 8: Multi-Modal & Accessibility"),
    (161, 180, "Category 9: State Management & Persistence"),
    (181, 200, "Category 10: Advanced & Future"),
];

// =============================================================================
// Idea Catalog (200 ideas)
// =============================================================================

pub fn ideas() -> Vec<Idea> {
    vec![
        // ===================================================================
        // CATEGORY 1: AG-UI Core Event Integration (1-20)
        // ===================================================================
        Idea { id: 1, title: "OODA Cycle SSE Lifecycle", source: "AG-UI RUN events", desc: "Emit RUN_STARTED/FINISHED for each OODA cycle. Operators see cycle count, duration, health delta in real-time.", zenoh: "c3i/ooda/{cycle_id}", crit: 5, usab: 5, info: 5, ux: 5 },
        Idea { id: 2, title: "Safety Kernel Constitutional Reasoning Stream", source: "AG-UI REASONING events", desc: "Stream Psi-0..Psi-5 constitutional check results as REASONING_MESSAGE_CONTENT events. Exposes decision chain without raw prompts.", zenoh: "c3i/safety/reasoning/{op_id}", crit: 5, usab: 5, info: 5, ux: 5 },
        Idea { id: 3, title: "Guardian Approval Interrupt", source: "AG-UI Interrupts (Draft)", desc: "When SafetyKernel needs two-key-turn confirmation, emit RUN_FINISHED(outcome=interrupt). Frontend shows approval dialog. Resume on user response.", zenoh: "c3i/guardian/approval/{req_id}", crit: 5, usab: 5, info: 5, ux: 5 },
        Idea { id: 4, title: "Mesh State Delta Streaming via JSON Patch", source: "AG-UI STATE_DELTA (RFC 6902)", desc: "Replace 30s polling with incremental JSON Patch updates. Only changed metrics flow to the frontend.", zenoh: "c3i/telemetry/delta", crit: 5, usab: 5, info: 5, ux: 4 },
        Idea { id: 5, title: "Planning Task Lifecycle Events", source: "AG-UI STEP events", desc: "Each task CRUD operation emits STEP_STARTED/FINISHED. Shows exact operation being performed.", zenoh: "c3i/planning/events", crit: 4, usab: 5, info: 4, ux: 4 },
        Idea { id: 6, title: "MCP Tool Call Visibility", source: "AG-UI TOOL_CALL events", desc: "When MCP executes planning_query or verification_run, emit TOOL_CALL_START/ARGS/END. Operator sees which tool is executing and with what arguments.", zenoh: "c3i/mcp/tool_call/{id}", crit: 5, usab: 4, info: 5, ux: 5 },
        Idea { id: 7, title: "Circuit Breaker State Change Events", source: "AG-UI CUSTOM", desc: "Emit CUSTOM('circuit_breaker') when enforcer opens/closes a circuit. Shows blocked agent IDs in real-time.", zenoh: "c3i/enforcer/circuit/{agent_id}", crit: 5, usab: 5, info: 4, ux: 5 },
        Idea { id: 8, title: "Emergency Stop Mesh Broadcast", source: "AG-UI CUSTOM + Zenoh", desc: "Emergency stop emits CUSTOM('emergency_stop') AND broadcasts to c3i/a2a/broadcast. All mesh agents halt. Frontend flashes red overlay.", zenoh: "c3i/a2a/broadcast", crit: 5, usab: 5, info: 5, ux: 4 },
        Idea { id: 9, title: "Verification Run Progress Stream", source: "AG-UI ACTIVITY events", desc: "During gleam test, emit ACTIVITY_SNAPSHOT with test name, ACTIVITY_DELTA for each pass/fail. Shows 479/479 progress bar.", zenoh: "c3i/verification/progress", crit: 4, usab: 4, info: 5, ux: 4 },
        Idea { id: 10, title: "Chaya Sync Phase Stream", source: "AG-UI STEP events", desc: "5-phase sync emits STEP for each phase: ReadPlanning, DetectOrphans, Convert, Regenerate, Verify. Real-time phase indicator.", zenoh: "c3i/planning/sync/{phase}", crit: 4, usab: 4, info: 4, ux: 4 },
        Idea { id: 11, title: "Audit Trail Messages Snapshot", source: "AG-UI MESSAGES_SNAPSHOT", desc: "Emit complete safety event log as MESSAGES_SNAPSHOT. Operator gets scrollable compliance history.", zenoh: "c3i/safety/audit", crit: 5, usab: 3, info: 5, ux: 3 },
        Idea { id: 12, title: "Zenoh Raw Event Passthrough", source: "AG-UI RAW events", desc: "Forward native Zenoh pub/sub messages as RAW events with source='zenoh'. Frontend renders message key, payload, timestamp.", zenoh: "c3i/zenoh/raw/#", crit: 3, usab: 4, info: 4, ux: 3 },
        Idea { id: 13, title: "Metabolic Set-Point State Delta", source: "AG-UI STATE_DELTA", desc: "Push metabolic governor state changes: set_point, energy, cpu_load, health_status as JSON Patch operations.", zenoh: "c3i/metabolic/state", crit: 4, usab: 3, info: 4, ux: 4 },
        Idea { id: 14, title: "Boot Sequence Step Events", source: "AG-UI STEP events", desc: "5-stage boot emits STEP per stage: InitSystem, LoadConfig, MountFS, StartServices, ActivateApp. Shows sequential progress.", zenoh: "c3i/boot/stage/{n}", crit: 4, usab: 4, info: 3, ux: 3 },
        Idea { id: 15, title: "Immune Threat Level Custom Event", source: "AG-UI CUSTOM", desc: "MARA state changes emit CUSTOM('threat_level') with level, strategy, confidence. Dashboard shows threat gauge.", zenoh: "c3i/immune/threat", crit: 4, usab: 3, info: 4, ux: 4 },
        Idea { id: 16, title: "Text Message Agent Explanations", source: "AG-UI TEXT_MESSAGE events", desc: "Agent streams natural language explanations via TEXT_MESSAGE_START/CONTENT/END. Operator asks 'why is CPU high?' and gets streaming answer.", zenoh: "c3i/agent/response", crit: 3, usab: 5, info: 4, ux: 4 },
        Idea { id: 17, title: "Tool Call Result Rendering", source: "AG-UI TOOL_CALL_RESULT", desc: "After MCP tool execution, emit TOOL_CALL_RESULT with structured output. Frontend renders results inline (e.g., task list, verification report).", zenoh: "c3i/mcp/result/{id}", crit: 4, usab: 4, info: 4, ux: 4 },
        Idea { id: 18, title: "State Snapshot on Connection", source: "AG-UI STATE_SNAPSHOT", desc: "When SSE connection opens, immediately emit full STATE_SNAPSHOT with all current mesh state. Client bootstraps from this.", zenoh: "c3i/state/snapshot", crit: 4, usab: 4, info: 4, ux: 3 },
        Idea { id: 19, title: "Multi-Step OODA with Nested Runs", source: "AG-UI parentRunId", desc: "Complex OODA cycles that delegate to sub-agents create nested runs with parentRunId. UI shows run hierarchy tree.", zenoh: "c3i/ooda/{cycle_id}/sub/{sub_id}", crit: 4, usab: 3, info: 4, ux: 3 },
        Idea { id: 20, title: "Custom Event Schema Registry", source: "AG-UI CUSTOM", desc: "Define a C3I-specific custom event schema registry: emergency_stop, circuit_breaker, threat_level, anomaly_detected, tmr_vote, sync_phase. All agents use consistent schema.", zenoh: "c3i/schema/events", crit: 4, usab: 3, info: 4, ux: 2 },

        // ===================================================================
        // CATEGORY 2: Zenoh A2A Agent Communication (21-40)
        // ===================================================================
        Idea { id: 21, title: "Agent-to-Agent Direct Messaging", source: "A2A + Zenoh", desc: "Each of 7 services (Cortex, Prajna, Smriti, CEPAF, Planning, Chaya, Guardian) has a dedicated inbox topic. Direct messaging via c3i/a2a/{source}/{target}.", zenoh: "c3i/a2a/{src}/{tgt}", crit: 5, usab: 5, info: 5, ux: 4 },
        Idea { id: 22, title: "Mesh Broadcast for Global State", source: "A2A + Zenoh", desc: "Broadcast channel for mesh-wide announcements: config changes, emergency alerts, new service registration.", zenoh: "c3i/a2a/broadcast", crit: 5, usab: 4, info: 4, ux: 3 },
        Idea { id: 23, title: "Zenoh Heartbeat Discovery", source: "A2A + Zenoh", desc: "Each agent publishes heartbeat every 5s to c3i/a2a/heartbeat/{agent_id}. Auto-populate ServiceRegistry from gossip.", zenoh: "c3i/a2a/heartbeat/{id}", crit: 4, usab: 4, info: 3, ux: 3 },
        Idea { id: 24, title: "Task Distribution via Zenoh Topics", source: "A2A + Planning Orchestration", desc: "Planning publishes tasks to c3i/planning/distribute/{strategy}. Chaya nodes subscribe and accept based on strategy (round-robin, least-loaded, priority).", zenoh: "c3i/planning/distribute/{strategy}", crit: 4, usab: 4, info: 4, ux: 3 },
        Idea { id: 25, title: "Guardian Consensus via Zenoh", source: "A2A + SafetyKernel", desc: "Multiple Guardian instances reach consensus on safety-critical operations via pub/sub voting on c3i/guardian/vote/{op_id}.", zenoh: "c3i/guardian/vote/{op_id}", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 26, title: "Cortex AI Request Pipeline", source: "A2A + Zenoh", desc: "Planning asks Cortex for AI analysis by publishing to c3i/a2a/planning/cortex. Cortex responds on c3i/a2a/cortex/planning with enriched results.", zenoh: "c3i/a2a/planning/cortex", crit: 4, usab: 4, info: 4, ux: 3 },
        Idea { id: 27, title: "Smriti Knowledge Query via Zenoh", source: "A2A + Zenoh", desc: "Any agent queries Smriti knowledge base by publishing to c3i/a2a/*/smriti with topic filter. Smriti responds with relevant knowledge nodes.", zenoh: "c3i/a2a/*/smriti", crit: 3, usab: 4, info: 5, ux: 3 },
        Idea { id: 28, title: "Prajna Health Aggregation", source: "A2A + Zenoh", desc: "Prajna subscribes to all heartbeat topics, aggregates mesh health, publishes composite score to c3i/prajna/health/composite.", zenoh: "c3i/prajna/health/composite", crit: 4, usab: 3, info: 4, ux: 3 },
        Idea { id: 29, title: "OODA Phase Coordination", source: "A2A + Zenoh", desc: "OODA controller publishes current phase to c3i/ooda/{cycle}/phase. Other agents can inject observations by publishing to c3i/ooda/{cycle}/inject.", zenoh: "c3i/ooda/{cycle}/phase", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 30, title: "Service Registration Events", source: "A2A + Zenoh", desc: "When a new service starts, it publishes ServiceRegistered to c3i/a2a/registry. All agents update their ServiceRegistry.", zenoh: "c3i/a2a/registry", crit: 4, usab: 3, info: 3, ux: 2 },
        Idea { id: 31, title: "Multi-Agent Consensus Protocol", source: "A2A + Zenoh", desc: "Implement Raft-like consensus over Zenoh for distributed decisions. Leader election via c3i/a2a/consensus/leader.", zenoh: "c3i/a2a/consensus/leader", crit: 4, usab: 2, info: 4, ux: 2 },
        Idea { id: 32, title: "Dead Letter Queue for Failed Messages", source: "A2A + Zenoh", desc: "Undeliverable A2A messages routed to c3i/a2a/dead_letter. Monitor and replay failed messages.", zenoh: "c3i/a2a/dead_letter", crit: 3, usab: 3, info: 4, ux: 2 },
        Idea { id: 33, title: "Agent Capability Advertisement", source: "A2A + Zenoh", desc: "Each agent publishes its MCP tool capabilities to c3i/a2a/capabilities/{agent_id}. Enables dynamic tool discovery.", zenoh: "c3i/a2a/capabilities/{id}", crit: 3, usab: 4, info: 4, ux: 2 },
        Idea { id: 34, title: "Cross-Holon State Sync via Zenoh", source: "A2A + Zenoh", desc: "Holons sync their state via c3i/holon/{id}/state. Conflict resolution uses last-writer-wins with vector clocks.", zenoh: "c3i/holon/{id}/state", crit: 4, usab: 2, info: 4, ux: 2 },
        Idea { id: 35, title: "Zenoh QoS Priority Lanes", source: "Zenoh", desc: "Safety messages use high-priority Zenoh channels. Telemetry uses best-effort. Ensures emergency_stop always arrives first.", zenoh: "c3i/priority/high/*", crit: 5, usab: 2, info: 3, ux: 2 },
        Idea { id: 36, title: "Agent Subscription Management", source: "A2A + Zenoh", desc: "Agents dynamically subscribe/unsubscribe to topics based on current role. E.g., Planning only subscribes to task-related topics.", zenoh: "c3i/subscriptions/{agent_id}", crit: 3, usab: 3, info: 3, ux: 2 },
        Idea { id: 37, title: "Zenoh Bridge to External A2A", source: "A2A Protocol + Zenoh", desc: "Bridge Zenoh topics to Google A2A protocol for inter-system agent communication. C3I agents talk to external agent ecosystems.", zenoh: "c3i/bridge/a2a/*", crit: 3, usab: 3, info: 3, ux: 3 },
        Idea { id: 38, title: "AG-UI Event Fan-Out via Zenoh", source: "AG-UI + Zenoh", desc: "AG-UI events emitted by any agent are published to c3i/agui/events/{agent_id}. Multiple SSE endpoints can subscribe and relay to different frontends.", zenoh: "c3i/agui/events/{agent_id}", crit: 4, usab: 4, info: 3, ux: 3 },
        Idea { id: 39, title: "Zenoh Backpressure for Slow Consumers", source: "Zenoh", desc: "When SSE client falls behind, Zenoh publisher applies backpressure. Prevents memory exhaustion on fast-producing agents.", zenoh: "c3i/backpressure/*", crit: 4, usab: 2, info: 2, ux: 2 },
        Idea { id: 40, title: "Temporal Message Ordering via Zenoh Timestamps", source: "Zenoh", desc: "All Zenoh messages carry NTP-synced timestamps. Consumers reorder by timestamp for deterministic replay. Critical for audit trail.", zenoh: "c3i/time/*", crit: 4, usab: 2, info: 3, ux: 2 },

        // ===================================================================
        // CATEGORY 3: Generative UI Widgets (41-60)
        // ===================================================================
        Idea { id: 41, title: "Interactive Mesh Topology D3 Graph", source: "Google Generative UI", desc: "Agent generates SVG/D3 mesh topology with 7 containers as nodes. Color by health. Click to drill down. Live position updates via STATE_DELTA.", zenoh: "c3i/ui/topology", crit: 3, usab: 4, info: 4, ux: 5 },
        Idea { id: 42, title: "Fractal Compliance Matrix", source: "Google Generative UI + Verification", desc: "8x8 colored grid: Fractal Layers (L0-L7) vs Compliance Checks (types, safety, perf, etc.). Green=pass, red=fail. Click cell for details.", zenoh: "c3i/ui/compliance", crit: 4, usab: 4, info: 4, ux: 4 },
        Idea { id: 43, title: "14-State Container DFA Widget", source: "Google Generative UI + Math", desc: "Interactive state machine diagram showing container lifecycle. Current state highlighted. Transitions animate on STATE_DELTA events.", zenoh: "c3i/ui/dfa/{container}", crit: 4, usab: 3, info: 4, ux: 4 },
        Idea { id: 44, title: "Real-Time Sparkline Dashboard", source: "Google Generative UI", desc: "Agent generates sparkline charts for CPU, memory, network, disk across all containers. Auto-scales. Color-coded thresholds.", zenoh: "c3i/ui/sparklines", crit: 3, usab: 4, info: 4, ux: 5 },
        Idea { id: 45, title: "OTel Flame Graph Visualization", source: "Golden Triangle + Generative UI", desc: "Agent generates interactive flame graph from OTel traces. Shows time breakdown: HTTP -> routing -> safety -> DB -> Zenoh -> response.", zenoh: "c3i/ui/flamegraph", crit: 3, usab: 3, info: 5, ux: 4 },
        Idea { id: 46, title: "Streaming Task Kanban Board", source: "Generative UI + Planning", desc: "Drag-drop Kanban with columns: Pending, InProgress, Completed, Blocked. Tasks move in real-time via STATE_DELTA. Drag triggers TOOL_CALL.", zenoh: "c3i/ui/kanban", crit: 3, usab: 5, info: 4, ux: 4 },
        Idea { id: 47, title: "Threat Level Gauge Widget", source: "Generative UI + Immune", desc: "Animated radial gauge showing MARA threat level (0-100). Color transitions: green -> yellow -> red. Needle moves on STATE_DELTA.", zenoh: "c3i/ui/threat_gauge", crit: 4, usab: 3, info: 3, ux: 5 },
        Idea { id: 48, title: "Knowledge Graph Explorer", source: "Generative UI + Knowledge", desc: "Interactive force-directed graph of knowledge nodes. Colored by HolonLevel. Search and filter. Double-click to expand neighbors.", zenoh: "c3i/ui/knowledge", crit: 2, usab: 3, info: 5, ux: 4 },
        Idea { id: 49, title: "Zenoh Message Flow Animation", source: "Generative UI + Zenoh", desc: "Animated diagram showing messages flowing between topics. Lines pulse from publisher to subscriber. Color by message type.", zenoh: "c3i/ui/zenoh_flow", crit: 2, usab: 3, info: 4, ux: 5 },
        Idea { id: 50, title: "Fault Injection Simulation", source: "Generative UI + Chaos", desc: "Interactive sandbox: operator clicks to kill a container, introduces network partition, or injects CPU spike. Mesh reacts in real-time.", zenoh: "c3i/ui/simulation", crit: 3, usab: 3, info: 4, ux: 4 },
        Idea { id: 51, title: "Incident Report Generator", source: "Google Generative UI + OTel", desc: "After incident, agent generates complete HTML report with timeline, root cause, affected components, RCA tree, and remediation steps.", zenoh: "c3i/ui/incident/{id}", crit: 3, usab: 3, info: 5, ux: 3 },
        Idea { id: 52, title: "TMR Voting Panel", source: "Generative UI + TMR", desc: "3-panel widget showing Channel A/B/C values side-by-side. Majority highlighted in green. Dissenter marked red. Animation on consensus.", zenoh: "c3i/ui/tmr", crit: 4, usab: 3, info: 3, ux: 4 },
        Idea { id: 53, title: "Access Control Graph Visualization", source: "Generative UI + GraphVerification", desc: "DOT graph of agent -> method -> file -> decision. Click to highlight paths. Run DFS/BFS live. Color SCCs distinctly.", zenoh: "c3i/ui/access_graph", crit: 4, usab: 3, info: 5, ux: 3 },
        Idea { id: 54, title: "Metabolic Homeostasis Dashboard", source: "Generative UI + Metabolic", desc: "Multi-gauge panel: CPU set-point dial, energy bar, TPS meter, error rate counter. Governor action (Expand/Maintain/Contract) as background color.", zenoh: "c3i/ui/metabolic", crit: 3, usab: 3, info: 4, ux: 4 },
        Idea { id: 55, title: "Podman Container Cards", source: "Generative UI + Podman", desc: "Card grid for each container: name, status pill, CPU/memory bars, uptime, image tag. Start/Stop/Restart buttons trigger TOOL_CALLs.", zenoh: "c3i/ui/podman", crit: 3, usab: 5, info: 3, ux: 4 },
        Idea { id: 56, title: "Generative Documentation Pages", source: "Google Generative UI", desc: "Ask 'explain SafetyKernel Psi checks' and agent generates a full HTML page with diagrams, code examples, and state machine visualizations.", zenoh: "c3i/ui/docs/{topic}", crit: 2, usab: 4, info: 5, ux: 3 },
        Idea { id: 57, title: "Timeline Waterfall Chart", source: "Generative UI + OTel", desc: "Horizontal waterfall chart showing request lifecycle. Each span as a colored bar. Hover for details. Shows critical path.", zenoh: "c3i/ui/waterfall", crit: 3, usab: 3, info: 4, ux: 4 },
        Idea { id: 58, title: "Heatmap of Agent Activity", source: "Generative UI + OTel", desc: "Time-of-day vs agent-id heatmap showing activity density. Identifies peak hours, idle agents, and hotspots.", zenoh: "c3i/ui/heatmap", crit: 2, usab: 3, info: 4, ux: 4 },
        Idea { id: 59, title: "System Architecture Diagram", source: "Generative UI", desc: "Auto-generated architecture diagram showing all services, their connections, protocols, and ports. Updated dynamically from ServiceRegistry.", zenoh: "c3i/ui/architecture", crit: 2, usab: 4, info: 4, ux: 4 },
        Idea { id: 60, title: "Interactive Training Sandbox", source: "Google Generative UI", desc: "Agent generates fault-scenario training: 'Practice responding to split-brain'. Interactive simulation with injected faults requiring operator remediation.", zenoh: "c3i/ui/training/{scenario}", crit: 2, usab: 3, info: 3, ux: 4 },

        // ===================================================================
        // CATEGORY 4: Human-in-the-Loop & Safety (61-80)
        // ===================================================================
        Idea { id: 61, title: "Two-Key-Turn Operation Confirmation", source: "AG-UI Interrupts + Prajna", desc: "Stop/Restart/Scale operations require two-key-turn: first key arms, interrupt pauses, second key confirms. Prevents accidental destructive actions.", zenoh: "c3i/guardian/two_key/{op}", crit: 5, usab: 5, info: 3, ux: 4 },
        Idea { id: 62, title: "Agent Steering During OODA", source: "AG-UI Steering", desc: "While OODA cycle is running, operator can inject override observations or force a specific Decision. Agent adjusts mid-stream.", zenoh: "c3i/ooda/{cycle}/steer", crit: 5, usab: 4, info: 3, ux: 3 },
        Idea { id: 63, title: "Rollback Confirmation Dialog", source: "AG-UI Frontend Tools", desc: "Before execute_with_rollback commits a state change, emit TOOL_CALL('frontend_confirm'). User sees before/after diff and approves.", zenoh: "c3i/safety/rollback/{op}", crit: 5, usab: 4, info: 4, ux: 3 },
        Idea { id: 64, title: "Constitutional Override Request", source: "AG-UI Interrupts", desc: "When a Psi check fails but operator believes it's a false positive, they can request an override. Requires elevated Guardian approval.", zenoh: "c3i/safety/override/{check}", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 65, title: "Encrypted Reasoning State", source: "AG-UI ReasoningEncryptedValue", desc: "Constitutional reasoning chain encrypted for carry-over across turns. Backend decrypts to maintain continuity. Frontend stores opaquely.", zenoh: "c3i/safety/encrypted_reasoning", crit: 5, usab: 2, info: 3, ux: 2 },
        Idea { id: 66, title: "Real-Time Violation Feed", source: "AG-UI CUSTOM + Enforcer", desc: "Every access violation emits CUSTOM('violation') with agent, path, reason, severity. Dashboard shows scrolling violation feed.", zenoh: "c3i/enforcer/violations", crit: 5, usab: 4, info: 4, ux: 3 },
        Idea { id: 67, title: "Manual Circuit Breaker Reset", source: "AG-UI Frontend Tools", desc: "Operator clicks 'Reset Circuit' for a blocked agent. Emits TOOL_CALL('reset_circuit', {agent_id}). Requires Guardian token.", zenoh: "c3i/enforcer/reset/{agent_id}", crit: 4, usab: 4, info: 3, ux: 3 },
        Idea { id: 68, title: "Safety Event Timeline", source: "AG-UI ACTIVITY + Safety", desc: "Chronological timeline of all safety events: checks passed, violations, overrides, emergency stops. Filterable by severity.", zenoh: "c3i/safety/timeline", crit: 5, usab: 3, info: 5, ux: 3 },
        Idea { id: 69, title: "Quarantine Agent Action", source: "AG-UI Frontend Tools", desc: "Operator quarantines a suspicious agent via TOOL_CALL('quarantine_agent'). Agent loses all permissions until Guardian lifts quarantine.", zenoh: "c3i/safety/quarantine/{agent_id}", crit: 5, usab: 3, info: 3, ux: 3 },
        Idea { id: 70, title: "Compliance Attestation Workflow", source: "AG-UI Interrupts", desc: "Before deployment, agent runs verification suite. If all pass, emit interrupt requesting operator attestation signature. Stored as audit record.", zenoh: "c3i/compliance/attestation", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 71, title: "Emergency Stop with Mesh Cascade", source: "AG-UI CUSTOM + Zenoh", desc: "Emergency stop cascades: first stops local operations, then broadcasts to mesh, then notifies all SSE clients. Three-phase shutdown.", zenoh: "c3i/emergency/cascade", crit: 5, usab: 4, info: 3, ux: 4 },
        Idea { id: 72, title: "Safety Kernel Health Monitor", source: "AG-UI STATE_DELTA + Safety", desc: "Continuous monitoring of SafetyKernel actor state: is_active, threat_level, guardian_healthy. Any change pushes STATE_DELTA.", zenoh: "c3i/safety/health", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 73, title: "Lethal Mutation Gate in UI", source: "AG-UI CUSTOM + Safety", desc: "When lethal mutation gate detects dangerous command (rm -rf), emit CUSTOM('lethal_mutation') with command, violation list. Frontend blocks execution.", zenoh: "c3i/safety/lethal", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 74, title: "Permission Elevation Workflow", source: "AG-UI Interrupts", desc: "Agent requests elevated permissions via interrupt. Operator reviews the operation scope, approves with time limit, agent continues.", zenoh: "c3i/safety/elevation/{req}", crit: 4, usab: 4, info: 3, ux: 3 },
        Idea { id: 75, title: "Audit Export to Immutable Log", source: "AG-UI Custom + Safety", desc: "All safety events are also exported to an append-only immutable log via Zenoh. Tamper-evident for regulatory compliance.", zenoh: "c3i/audit/immutable", crit: 5, usab: 2, info: 4, ux: 2 },
        Idea { id: 76, title: "SIL-6 Compliance Dashboard", source: "AG-UI STATE_SNAPSHOT", desc: "Full STATE_SNAPSHOT of all IEC 61508 compliance metrics: STAMP constraint coverage, FMEA scores, test pass rates, NIF status.", zenoh: "c3i/compliance/sil6", crit: 5, usab: 3, info: 5, ux: 3 },
        Idea { id: 77, title: "Agent Behavior Anomaly Alert", source: "AG-UI CUSTOM", desc: "Behavioral analysis detects unusual patterns (e.g., agent making 100x normal requests). CUSTOM('behavior_anomaly') with details.", zenoh: "c3i/enforcer/anomaly", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 78, title: "Proof Token Verification in UI", source: "AG-UI CUSTOM", desc: "Display ProofToken validation status for each operation. Green checkmark for valid, red X for invalid, yellow for expired.", zenoh: "c3i/safety/proof_token", crit: 4, usab: 3, info: 3, ux: 3 },
        Idea { id: 79, title: "Safety Kernel Activation Toggle", source: "AG-UI Frontend Tools", desc: "Operator can activate/deactivate SafetyKernel from dashboard. Requires two-key-turn. Status shown as glowing indicator.", zenoh: "c3i/safety/activation", crit: 5, usab: 3, info: 2, ux: 3 },
        Idea { id: 80, title: "Constitutional Check Replay", source: "AG-UI MESSAGES_SNAPSHOT", desc: "Replay any past constitutional check sequence. Load the MESSAGES_SNAPSHOT, step through each Psi check result, analyze decisions.", zenoh: "c3i/safety/replay/{op_id}", crit: 4, usab: 3, info: 4, ux: 3 },

        // ===================================================================
        // CATEGORY 5: Dark Cockpit & Situational Awareness (81-100)
        // ===================================================================
        Idea { id: 81, title: "Progressive Disclosure Mode", source: "SC-HMI-010 + AG-UI", desc: "5 modes: Dark (>90% healthy), Dim (>70%), Normal, Bright (<30%), Emergency. Transition via STATE_DELTA health score.", zenoh: "c3i/hmi/mode", crit: 4, usab: 5, info: 3, ux: 5 },
        Idea { id: 82, title: "Activity-Driven Status Bar", source: "AG-UI ACTIVITY events", desc: "Bottom bar shows current ops: 'OODA: Orient [3/5]', 'Sync: Phase 2 [45%]', 'Test: [312/479]'. Updates via ACTIVITY_DELTA.", zenoh: "c3i/hmi/status_bar", crit: 3, usab: 5, info: 4, ux: 4 },
        Idea { id: 83, title: "Critical Alert Sound Events", source: "AG-UI CUSTOM + Audio", desc: "CUSTOM('sound_alert', {severity}) triggers browser audio. Different tones for warning/error/critical. Operator hears alerts even when not looking.", zenoh: "c3i/hmi/sound", crit: 4, usab: 4, info: 2, ux: 4 },
        Idea { id: 84, title: "Anomaly Highlighting via State Delta", source: "AG-UI STATE_DELTA", desc: "When a metric crosses a threshold, the STATE_DELTA includes a 'highlight' flag. Frontend pulses the affected element.", zenoh: "c3i/hmi/highlight", crit: 3, usab: 4, info: 3, ux: 4 },
        Idea { id: 85, title: "Zen Mode (Minimal Display)", source: "AG-UI Custom", desc: "Operator toggles Zen mode: only critical alerts and active OODA cycles visible. Everything else fades to dark. Maximum focus.", zenoh: "c3i/hmi/zen", crit: 2, usab: 4, info: 2, ux: 5 },
        Idea { id: 86, title: "Alert Acknowledgment Workflow", source: "AG-UI Frontend Tools", desc: "Critical alerts require explicit acknowledgment. TOOL_CALL('acknowledge_alert', {id}). Unacked alerts escalate after timeout.", zenoh: "c3i/hmi/alerts/ack", crit: 4, usab: 4, info: 3, ux: 3 },
        Idea { id: 87, title: "Situational Awareness Blink Animation", source: "AG-UI CUSTOM + CockpitZenoh", desc: "Critical alarms trigger CSS blink animation on affected container cards. Stops when acknowledged. Per SC-COCKPIT-002.", zenoh: "c3i/hmi/blink/{container}", crit: 4, usab: 3, info: 2, ux: 4 },
        Idea { id: 88, title: "Trend Sparklines in Status Cards", source: "AG-UI STATE_DELTA", desc: "Each container card shows mini sparklines for last 60s of CPU/memory. Trends visible at a glance. Generated from STATE_DELTA history.", zenoh: "c3i/hmi/trends/{container}", crit: 3, usab: 4, info: 4, ux: 4 },
        Idea { id: 89, title: "Color-Blind Accessible Modes", source: "WCAG 2.1 + AG-UI", desc: "Dark cockpit uses patterns (stripes, dots, cross-hatching) in addition to colors. Operator selects deuteranopia/protanopia mode.", zenoh: "c3i/hmi/a11y", crit: 2, usab: 4, info: 2, ux: 4 },
        Idea { id: 90, title: "Keyboard Navigation for All Actions", source: "WCAG 2.1 + AG-UI", desc: "All cockpit actions accessible via keyboard shortcuts. Tab order follows logical flow. Screen reader announces AG-UI events.", zenoh: "c3i/hmi/keyboard", crit: 2, usab: 4, info: 2, ux: 4 },
        Idea { id: 91, title: "Minimap Overview Panel", source: "Generative UI + Cockpit", desc: "Zoomable minimap showing entire mesh at a glance. Click to zoom into any section. Current view highlighted as a viewport box.", zenoh: "c3i/hmi/minimap", crit: 2, usab: 4, info: 3, ux: 4 },
        Idea { id: 92, title: "Log Level Toggle per Container", source: "AG-UI Frontend Tools", desc: "Operator adjusts log level per container from cockpit: TOOL_CALL('set_log_level', {container, level}). Changes propagate via Zenoh.", zenoh: "c3i/hmi/loglevel/{container}", crit: 3, usab: 4, info: 3, ux: 3 },
        Idea { id: 93, title: "Health Score Trendline", source: "AG-UI STATE_DELTA", desc: "Composite health score (0-100) plotted over time. Declining trend triggers predictive warning before actual failure.", zenoh: "c3i/hmi/health_trend", crit: 4, usab: 3, info: 4, ux: 3 },
        Idea { id: 94, title: "Auto-Layout Dashboard Panels", source: "Generative UI + HMI", desc: "Dashboard panels automatically rearrange based on alert state. Critical alerts expand, healthy components shrink. Priority-based layout.", zenoh: "c3i/hmi/layout", crit: 3, usab: 4, info: 3, ux: 4 },
        Idea { id: 95, title: "Night Vision Mode", source: "HMI + Dark Cockpit", desc: "Red-on-black color scheme for nighttime operations. Preserves dark adaptation. All UI elements use deep red shades.", zenoh: "c3i/hmi/nightvision", crit: 2, usab: 3, info: 2, ux: 4 },
        Idea { id: 96, title: "Contextual Tooltip System", source: "AG-UI + Generative UI", desc: "Hover over any metric to see AI-generated contextual explanation: what the metric means, why it's at current level, what action to take.", zenoh: "c3i/hmi/tooltips", crit: 2, usab: 5, info: 4, ux: 4 },
        Idea { id: 97, title: "Multi-Monitor Support", source: "AG-UI + HMI", desc: "Different SSE streams per monitor: Monitor 1 = mesh overview, Monitor 2 = planning, Monitor 3 = telemetry. Each is an independent AG-UI client.", zenoh: "c3i/hmi/monitor/{n}", crit: 2, usab: 4, info: 3, ux: 4 },
        Idea { id: 98, title: "Ambient Background Color by Health", source: "HMI + AG-UI STATE_DELTA", desc: "Dashboard background subtly shifts: dark green (healthy) -> warm amber (degraded) -> deep red (critical). Peripheral vision cue.", zenoh: "c3i/hmi/ambient", crit: 3, usab: 3, info: 2, ux: 5 },
        Idea { id: 99, title: "Pin Important Metrics", source: "AG-UI + HMI", desc: "Operator pins specific metrics to always-visible top bar. Pinned items persist across sessions via Zenoh state store.", zenoh: "c3i/hmi/pins", crit: 2, usab: 5, info: 3, ux: 3 },
        Idea { id: 100, title: "Notification Center", source: "AG-UI CUSTOM", desc: "Sliding notification panel showing history of all CUSTOM events: violations, alerts, approvals, tool calls. Filterable, searchable, dismissable.", zenoh: "c3i/hmi/notifications", crit: 3, usab: 4, info: 4, ux: 4 },

        // ===================================================================
        // CATEGORY 6: OTel Golden Triangle (101-120)
        // ===================================================================
        Idea { id: 101, title: "Token Cost Tracker per MCP Tool", source: "Golden Triangle + OTel", desc: "Track LLM token consumption per tool call. CUSTOM('token_usage', {tool, input, output, cost}). Dashboard shows cumulative cost breakdown.", zenoh: "c3i/otel/cost", crit: 3, usab: 3, info: 5, ux: 3 },
        Idea { id: 102, title: "Distributed Trace Visualization", source: "Golden Triangle + OTel", desc: "Full distributed trace from HTTP request through Gleam -> Zenoh -> Cortex -> DB and back. Rendered as connected spans.", zenoh: "c3i/otel/traces", crit: 3, usab: 3, info: 5, ux: 3 },
        Idea { id: 103, title: "Latency Percentile Dashboard", source: "OTel Metrics", desc: "P50/P95/P99 latency charts for each endpoint. Alerts when P99 exceeds threshold. Historical comparison.", zenoh: "c3i/otel/latency", crit: 3, usab: 3, info: 5, ux: 3 },
        Idea { id: 104, title: "Error Rate Monitoring", source: "OTel Metrics", desc: "Error rate per service/endpoint. Spike detection triggers CUSTOM('error_spike'). Correlated with recent deployments.", zenoh: "c3i/otel/errors", crit: 4, usab: 3, info: 4, ux: 3 },
        Idea { id: 105, title: "Prometheus Query Builder", source: "OTel + Generative UI", desc: "Agent generates Prometheus queries from natural language: 'show me CPU usage for the last hour' -> PromQL query -> chart.", zenoh: "c3i/otel/promql", crit: 2, usab: 4, info: 4, ux: 4 },
        Idea { id: 106, title: "Service Dependency Map from Traces", source: "OTel + Generative UI", desc: "Auto-generate service dependency map from OTel trace data. Shows which services call which, with latency on edges.", zenoh: "c3i/otel/dependency", crit: 2, usab: 3, info: 5, ux: 4 },
        Idea { id: 107, title: "OODA Cycle Performance Metrics", source: "OTel + SC-ORCH-004", desc: "Track OODA cycle time vs 100ms target. Histogram of cycle times. Alert when trending above threshold.", zenoh: "c3i/otel/ooda", crit: 4, usab: 3, info: 4, ux: 3 },
        Idea { id: 108, title: "Memory Leak Detection", source: "OTel Metrics", desc: "Track BEAM process memory over time. Detect monotonically increasing memory (leak indicator). Alert with process ID.", zenoh: "c3i/otel/memory", crit: 4, usab: 2, info: 4, ux: 2 },
        Idea { id: 109, title: "Log Volume Analytics", source: "OTel + Generative UI", desc: "Chart log volume by level over time. Spike in error logs triggers investigation workflow. Agent suggests root cause.", zenoh: "c3i/otel/log_volume", crit: 3, usab: 3, info: 4, ux: 3 },
        Idea { id: 110, title: "SLA Dashboard", source: "OTel Metrics", desc: "Service Level Agreement tracking: uptime %, error budget remaining, latency targets. Shows burn rate.", zenoh: "c3i/otel/sla", crit: 3, usab: 3, info: 4, ux: 3 },
        Idea { id: 111, title: "Zenoh Message Rate Metrics", source: "OTel + Zenoh", desc: "Track messages/sec per Zenoh topic. Identify hot topics, silent topics, and unusual spikes.", zenoh: "c3i/otel/zenoh_rate", crit: 3, usab: 3, info: 4, ux: 3 },
        Idea { id: 112, title: "DB Query Performance", source: "OTel + DuckDB", desc: "Track DuckDB query execution times. Identify slow queries. Show query plan visualization.", zenoh: "c3i/otel/db", crit: 3, usab: 3, info: 4, ux: 3 },
        Idea { id: 113, title: "NIF Call Latency Tracking", source: "OTel + Rust NIFs", desc: "Track Rust NIF call latency: zenoh_open, zenoh_put, sqrt, etc. Detect NIF loading failures.", zenoh: "c3i/otel/nif", crit: 4, usab: 2, info: 4, ux: 2 },
        Idea { id: 114, title: "Grafana Dashboard Auto-Link", source: "Golden Triangle", desc: "AG-UI CUSTOM events include Grafana dashboard deep links. Clicking 'Details' opens the relevant Grafana panel.", zenoh: "c3i/otel/grafana", crit: 2, usab: 4, info: 3, ux: 4 },
        Idea { id: 115, title: "Alert Correlation Engine", source: "OTel + AG-UI", desc: "Correlate multiple OTel alerts into a single incident. 'High CPU' + 'Slow queries' + 'Memory spike' = 'Resource exhaustion incident'.", zenoh: "c3i/otel/correlate", crit: 3, usab: 3, info: 5, ux: 3 },
        Idea { id: 116, title: "Capacity Planning Projections", source: "OTel + Generative UI", desc: "Agent analyzes resource trends and generates capacity projection charts. Shows when resources will be exhausted at current growth rate.", zenoh: "c3i/otel/capacity", crit: 3, usab: 3, info: 5, ux: 3 },
        Idea { id: 117, title: "Cost Optimization Recommendations", source: "Golden Triangle + OTel", desc: "Agent analyzes token usage, resource consumption, and suggests optimizations: 'Switch to smaller model for planning_query saves 40% tokens'.", zenoh: "c3i/otel/optimize", crit: 2, usab: 4, info: 4, ux: 3 },
        Idea { id: 118, title: "Real-Time Request Tracing", source: "OTel + AG-UI SSE", desc: "Tag an incoming request and trace it through the entire stack in real-time. Each hop emits a STEP event.", zenoh: "c3i/otel/trace/{id}", crit: 3, usab: 3, info: 4, ux: 4 },
        Idea { id: 119, title: "Comparison Mode (Before/After)", source: "OTel + Generative UI", desc: "Compare metrics from two time windows side-by-side. Agent generates diff visualization highlighting significant changes.", zenoh: "c3i/otel/compare", crit: 2, usab: 3, info: 4, ux: 4 },
        Idea { id: 120, title: "Health Score Calculation Transparency", source: "OTel + AG-UI REASONING", desc: "Show how composite health score is calculated: weights for CPU, memory, errors, latency. REASONING events explain each factor.", zenoh: "c3i/otel/health_calc", crit: 3, usab: 3, info: 5, ux: 3 },

        // ===================================================================
        // CATEGORY 7: MCP Tool Ecosystem (121-140)
        // ===================================================================
        Idea { id: 121, title: "zenoh_subscribe Tool", source: "MCP + Zenoh", desc: "New MCP tool that subscribes to a Zenoh topic and streams messages back as TOOL_CALL_RESULT events. Live data feed to the agent.", zenoh: "c3i/mcp/zenoh_sub/*", crit: 4, usab: 4, info: 4, ux: 3 },
        Idea { id: 122, title: "container_manage Tool", source: "MCP + Podman", desc: "MCP tool for container operations: list, start, stop, restart, inspect. Returns structured ContainerInfo.", zenoh: "c3i/mcp/podman/*", crit: 4, usab: 4, info: 4, ux: 3 },
        Idea { id: 123, title: "graph_query Tool", source: "MCP + Knowledge", desc: "Query the knowledge graph by node type, relationship, or semantic similarity. Returns matching nodes and paths.", zenoh: "c3i/mcp/knowledge/*", crit: 3, usab: 4, info: 5, ux: 3 },
        Idea { id: 124, title: "anomaly_detect Tool", source: "MCP + Anomaly", desc: "Run anomaly detection on specified metrics with configurable thresholds. Returns list of detected anomalies.", zenoh: "c3i/mcp/anomaly/*", crit: 4, usab: 3, info: 4, ux: 3 },
        Idea { id: 125, title: "cryocore_archive Tool", source: "MCP + Indrajaal.Ark", desc: "Create or restore system snapshots. Archive creates GZip tarball, restore unpacks to specified path.", zenoh: "c3i/mcp/cryocore/*", crit: 3, usab: 3, info: 3, ux: 2 },
        Idea { id: 126, title: "Tool Output Streaming", source: "AG-UI Tool Output Streaming", desc: "Long-running tools (verification_run) stream partial results via TOOL_CALL_RESULT with intermediate data.", zenoh: "c3i/mcp/stream/{id}", crit: 3, usab: 4, info: 4, ux: 4 },
        Idea { id: 127, title: "Tool Chain Orchestration", source: "MCP + AG-UI STEP", desc: "Chain tools: planning_query -> verification_run -> report_generate. Each step emitted as AG-UI STEP event.", zenoh: "c3i/mcp/chain/{id}", crit: 3, usab: 4, info: 4, ux: 3 },
        Idea { id: 128, title: "Frontend-Executed Tools", source: "AG-UI Frontend Tools", desc: "Some tools execute in the browser: clipboard_read, screenshot, local_file_browse. Agent requests, frontend executes, result sent back.", zenoh: "c3i/mcp/frontend/*", crit: 2, usab: 4, info: 3, ux: 4 },
        Idea { id: 129, title: "execute_gleam Tool", source: "MCP + Gleam", desc: "Execute arbitrary Gleam expressions in a sandboxed BEAM environment. Returns the result. For interactive exploration.", zenoh: "c3i/mcp/gleam_eval", crit: 3, usab: 4, info: 4, ux: 3 },
        Idea { id: 130, title: "ooda_trigger Tool", source: "MCP + OODA", desc: "Manually trigger an OODA cycle with specified observations. Returns the full Observe->Orient->Decide->Act chain.", zenoh: "c3i/mcp/ooda/trigger", crit: 4, usab: 3, info: 4, ux: 3 },
        Idea { id: 131, title: "safety_check Tool", source: "MCP + SafetyKernel", desc: "Run all constitutional checks (Psi-0..5, Omega-0) against a proposed operation. Returns structured SafetyResult list.", zenoh: "c3i/mcp/safety/check", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 132, title: "mesh_health Tool", source: "MCP + Prajna", desc: "Aggregate health from all mesh nodes. Returns composite health score, per-node status, and recommendations.", zenoh: "c3i/mcp/mesh/health", crit: 4, usab: 4, info: 4, ux: 3 },
        Idea { id: 133, title: "generate_report Tool", source: "MCP + Generative UI", desc: "Generate comprehensive system report as HTML. Includes all domain states, metrics, compliance status.", zenoh: "c3i/mcp/report/generate", crit: 2, usab: 3, info: 5, ux: 3 },
        Idea { id: 134, title: "diff_state Tool", source: "MCP + State", desc: "Compare two state snapshots and return JSON Patch diff. Useful for understanding what changed between two points in time.", zenoh: "c3i/mcp/state/diff", crit: 3, usab: 3, info: 4, ux: 3 },
        Idea { id: 135, title: "search_logs Tool", source: "MCP + OTel", desc: "Search OTel logs by keyword, time range, severity. Returns matching log entries with context.", zenoh: "c3i/mcp/logs/search", crit: 3, usab: 4, info: 4, ux: 3 },
        Idea { id: 136, title: "explain_error Tool", source: "MCP + OODA Orient", desc: "Given an error message, classify it using OODA Orient patterns and suggest remediation steps.", zenoh: "c3i/mcp/error/explain", crit: 3, usab: 5, info: 4, ux: 3 },
        Idea { id: 137, title: "schedule_task Tool", source: "MCP + Planning", desc: "Schedule a task for future execution with cron-like syntax. Returns scheduled task ID and next execution time.", zenoh: "c3i/mcp/planning/schedule", crit: 3, usab: 4, info: 3, ux: 3 },
        Idea { id: 138, title: "export_audit Tool", source: "MCP + Safety", desc: "Export safety audit log for specified time range. Returns JSON array of all safety events.", zenoh: "c3i/mcp/audit/export", crit: 4, usab: 3, info: 4, ux: 2 },
        Idea { id: 139, title: "Tool Permissions Matrix", source: "MCP + Enforcer", desc: "Each MCP tool has an access matrix defining which agent types can call it. Enforcer checks before execution.", zenoh: "c3i/mcp/permissions", crit: 4, usab: 2, info: 3, ux: 2 },
        Idea { id: 140, title: "Tool Usage Analytics", source: "MCP + OTel", desc: "Track which tools are called most, average latency, success/failure rates. Optimize tool implementations.", zenoh: "c3i/mcp/analytics", crit: 2, usab: 3, info: 4, ux: 3 },

        // ===================================================================
        // CATEGORY 8: Multi-Modal & Accessibility (141-160)
        // ===================================================================
        Idea { id: 141, title: "Voice Command Input", source: "AG-UI Multimodality", desc: "Operator speaks commands. Browser speech recognition transcribes. Sent as AG-UI user message. Agent responds with text + UI updates.", zenoh: "c3i/modal/voice/input", crit: 2, usab: 4, info: 2, ux: 4 },
        Idea { id: 142, title: "Voice Alert Output", source: "AG-UI Multimodality", desc: "Critical safety events trigger browser speech synthesis: 'Warning: CPU threshold exceeded on zenoh-router-2'. Hands-free awareness.", zenoh: "c3i/modal/voice/output", crit: 3, usab: 4, info: 3, ux: 4 },
        Idea { id: 143, title: "Screenshot Attachment", source: "AG-UI Multimodality", desc: "Operator captures screenshot and attaches to AG-UI message. Agent can analyze it (if vision-capable) or store for incident report.", zenoh: "c3i/modal/image/attach", crit: 2, usab: 3, info: 3, ux: 3 },
        Idea { id: 144, title: "Generated Architecture Diagrams", source: "AG-UI Multimodality + GenUI", desc: "Agent generates SVG architecture diagrams and sends as image attachment. Operator sees visual representation of system state.", zenoh: "c3i/modal/image/generate", crit: 2, usab: 3, info: 4, ux: 4 },
        Idea { id: 145, title: "ARIA Labels for All Widgets", source: "WCAG 2.1", desc: "All generative UI widgets include proper ARIA labels, roles, and live regions. Screen readers announce state changes.", zenoh: "c3i/a11y/aria", crit: 2, usab: 4, info: 2, ux: 4 },
        Idea { id: 146, title: "High Contrast Mode", source: "WCAG 2.1 + HMI", desc: "Force high contrast colors for all UI elements. White on black for maximum readability. Toggleable from cockpit.", zenoh: "c3i/a11y/contrast", crit: 2, usab: 4, info: 2, ux: 3 },
        Idea { id: 147, title: "Mobile-Responsive Cockpit", source: "AG-UI + CSS", desc: "Dashboard adapts to mobile screen: single column, swipeable pages, touch-friendly buttons. SSE still works on mobile.", zenoh: "c3i/a11y/mobile", crit: 2, usab: 4, info: 2, ux: 4 },
        Idea { id: 148, title: "Text-to-Speech for Reasoning", source: "AG-UI REASONING + TTS", desc: "Constitutional reasoning chain read aloud via browser TTS. Useful for operators who are monitoring multiple screens.", zenoh: "c3i/modal/tts/reasoning", crit: 2, usab: 3, info: 3, ux: 3 },
        Idea { id: 149, title: "Haptic Feedback for Alerts", source: "AG-UI + Mobile", desc: "On mobile devices, critical alerts trigger haptic vibration pattern. Different patterns for warning/error/critical.", zenoh: "c3i/modal/haptic", crit: 2, usab: 3, info: 1, ux: 3 },
        Idea { id: 150, title: "Internationalization (i18n)", source: "AG-UI + Generative UI", desc: "Agent generates UI in the operator's preferred language. Metric labels, alert descriptions, tooltips all localized.", zenoh: "c3i/a11y/i18n", crit: 1, usab: 3, info: 2, ux: 4 },
        Idea { id: 151, title: "Reduced Motion Mode", source: "WCAG 2.1", desc: "Disable all animations for vestibular sensitivity. Sparklines become static bars. Blink alerts become solid colors.", zenoh: "c3i/a11y/motion", crit: 1, usab: 3, info: 2, ux: 3 },
        Idea { id: 152, title: "PDF Export of Dashboard", source: "AG-UI + Generative UI", desc: "Export current dashboard state as a PDF report. Generated by agent with all current metrics and charts rendered to static images.", zenoh: "c3i/modal/pdf", crit: 2, usab: 3, info: 3, ux: 3 },
        Idea { id: 153, title: "Clipboard Integration", source: "AG-UI Frontend Tools", desc: "TOOL_CALL('clipboard_write', {content}) copies data to clipboard. Useful for sharing metrics, IDs, or configurations.", zenoh: "c3i/modal/clipboard", crit: 1, usab: 4, info: 2, ux: 3 },
        Idea { id: 154, title: "Custom Keyboard Shortcuts", source: "AG-UI + HMI", desc: "Operator defines custom keyboard shortcuts for frequent actions: Ctrl+O = OODA cycle, Ctrl+E = emergency stop, etc.", zenoh: "c3i/a11y/shortcuts", crit: 2, usab: 4, info: 2, ux: 3 },
        Idea { id: 155, title: "Dyslexia-Friendly Font Option", source: "WCAG 2.1", desc: "Toggle to OpenDyslexic font for all UI text. Improves readability for dyslexic operators.", zenoh: "c3i/a11y/font", crit: 1, usab: 3, info: 1, ux: 3 },
        Idea { id: 156, title: "Tab Panel Focus Management", source: "WCAG 2.1", desc: "Tab through dashboard panels in logical order. Focus ring visible. Active panel announced by screen reader.", zenoh: "c3i/a11y/focus", crit: 1, usab: 3, info: 2, ux: 3 },
        Idea { id: 157, title: "Audio Transcription for Incident Reports", source: "AG-UI Multimodality", desc: "Operator records voice memo about an incident. Transcribed and attached to the incident report automatically.", zenoh: "c3i/modal/transcribe", crit: 2, usab: 3, info: 3, ux: 3 },
        Idea { id: 158, title: "Color Theme Customization", source: "AG-UI + Generative UI", desc: "Agent generates CSS theme from natural language: 'aerospace blue', 'NASA mission control', 'cyber green'. Applied to entire cockpit.", zenoh: "c3i/modal/theme", crit: 1, usab: 3, info: 1, ux: 4 },
        Idea { id: 159, title: "Widget Size Customization", source: "AG-UI + HMI", desc: "Operator resizes dashboard widgets by dragging edges. Layout persisted via Zenoh state store. Each operator has personal layout.", zenoh: "c3i/hmi/widget_size", crit: 1, usab: 4, info: 2, ux: 4 },
        Idea { id: 160, title: "Multi-Language Agent Responses", source: "AG-UI TEXT_MESSAGE", desc: "Agent responds in the operator's preferred language. Safety alerts always include English alongside the localized version.", zenoh: "c3i/modal/language", crit: 2, usab: 3, info: 2, ux: 3 },

        // ===================================================================
        // CATEGORY 9: State Management & Persistence (161-180)
        // ===================================================================
        Idea { id: 161, title: "Run History with Branching", source: "AG-UI parentRunId", desc: "Every agent run stores parentRunId creating a git-like log. UI shows run tree. Branch from any point to explore alternatives.", zenoh: "c3i/state/runs", crit: 3, usab: 4, info: 4, ux: 3 },
        Idea { id: 162, title: "Thread Persistence Across Sessions", source: "AG-UI threadId", desc: "Conversation threads persist in DuckDB. Operator resumes where they left off. Full message history available.", zenoh: "c3i/state/threads", crit: 2, usab: 5, info: 3, ux: 4 },
        Idea { id: 163, title: "State Rollback (Time-Travel)", source: "AG-UI STATE_SNAPSHOT", desc: "Store periodic STATE_SNAPSHOTs. Operator can 'rewind' to any past state and inspect. Useful for debugging.", zenoh: "c3i/state/rollback", crit: 3, usab: 3, info: 4, ux: 3 },
        Idea { id: 164, title: "Cross-Session State via Zenoh", source: "Zenoh + AG-UI", desc: "Dashboard state (pinned metrics, layout, preferences) stored in Zenoh key-value store. Available from any client.", zenoh: "c3i/state/preferences/{user}", crit: 2, usab: 4, info: 2, ux: 4 },
        Idea { id: 165, title: "Collaborative Multi-Operator View", source: "AG-UI Shared State + Zenoh", desc: "Multiple operators share same SSE stream via Zenoh broadcast. One operator's actions (approvals, task updates) visible to all.", zenoh: "c3i/state/collab", crit: 3, usab: 4, info: 3, ux: 3 },
        Idea { id: 166, title: "Operator Cursor Presence", source: "AG-UI Shared State", desc: "Like Google Docs: each operator's cursor/focus visible to others. See who is looking at which section of the dashboard.", zenoh: "c3i/state/cursors", crit: 1, usab: 3, info: 2, ux: 4 },
        Idea { id: 167, title: "Undo/Redo for Operations", source: "AG-UI STATE_SNAPSHOT", desc: "Operator can undo last action (task status change, config update). STATE_SNAPSHOT provides the checkpoint for rollback.", zenoh: "c3i/state/undo", crit: 3, usab: 4, info: 2, ux: 4 },
        Idea { id: 168, title: "Bookmark Important States", source: "AG-UI + State", desc: "Operator bookmarks a STATE_SNAPSHOT with a label: 'before deployment', 'after hotfix'. Quick comparison between bookmarks.", zenoh: "c3i/state/bookmarks", crit: 2, usab: 4, info: 3, ux: 3 },
        Idea { id: 169, title: "State Diff Between Bookmarks", source: "AG-UI STATE_DELTA", desc: "Select two bookmarked states and see the JSON Patch diff. Highlights exactly what changed.", zenoh: "c3i/state/diff", crit: 2, usab: 3, info: 4, ux: 3 },
        Idea { id: 170, title: "Auto-Save Dashboard Configuration", source: "AG-UI + Zenoh", desc: "Dashboard layout, active filters, pinned items auto-save every 30s to Zenoh KV store. Never lose your workspace.", zenoh: "c3i/state/autosave/{user}", crit: 1, usab: 4, info: 2, ux: 4 },
        Idea { id: 171, title: "Session Recording and Replay", source: "AG-UI Events", desc: "Record all AG-UI events during a session. Replay later for training, debugging, or audit. Like a DVR for the cockpit.", zenoh: "c3i/state/recording/{id}", crit: 3, usab: 3, info: 4, ux: 3 },
        Idea { id: 172, title: "State Schema Versioning", source: "AG-UI + MSTS", desc: "STATE_SNAPSHOT includes schema version. Frontend handles schema migrations gracefully when server updates.", zenoh: "c3i/state/schema/version", crit: 3, usab: 2, info: 3, ux: 2 },
        Idea { id: 173, title: "Optimistic UI Updates", source: "AG-UI STATE_DELTA", desc: "Frontend applies state changes optimistically before server confirms. Reverts if server-side validation fails. Snappy UX.", zenoh: "c3i/state/optimistic", crit: 2, usab: 4, info: 2, ux: 4 },
        Idea { id: 174, title: "Conflict Resolution for Shared State", source: "AG-UI + Zenoh", desc: "When two operators modify the same state simultaneously, Zenoh vector clocks detect conflict. UI shows merge dialog.", zenoh: "c3i/state/conflict", crit: 3, usab: 3, info: 3, ux: 3 },
        Idea { id: 175, title: "Offline Mode with Sync", source: "AG-UI + State", desc: "Dashboard works offline using cached STATE_SNAPSHOT. When reconnected, STATE_DELTA stream catches up. No data loss.", zenoh: "c3i/state/offline", crit: 2, usab: 4, info: 2, ux: 4 },
        Idea { id: 176, title: "State Export/Import", source: "AG-UI + State", desc: "Export entire dashboard state as JSON file. Import on another machine. Useful for sharing configurations between operators.", zenoh: "c3i/state/export", crit: 1, usab: 3, info: 2, ux: 3 },
        Idea { id: 177, title: "Event Sourcing for All Changes", source: "AG-UI + Safety", desc: "All state mutations stored as an event log (not just final state). Complete history reconstructable from events.", zenoh: "c3i/state/events", crit: 4, usab: 2, info: 4, ux: 2 },
        Idea { id: 178, title: "State Snapshot Compression", source: "AG-UI + Performance", desc: "Large STATE_SNAPSHOTs compressed with gzip before SSE transmission. Reduces bandwidth by ~70% for initial load.", zenoh: "c3i/state/compressed", crit: 2, usab: 2, info: 2, ux: 3 },
        Idea { id: 179, title: "Selective State Subscription", source: "AG-UI + Performance", desc: "Client subscribes to specific state subtrees (e.g., only planning, not telemetry). Reduces event volume for focused views.", zenoh: "c3i/state/subscribe/{path}", crit: 2, usab: 3, info: 3, ux: 3 },
        Idea { id: 180, title: "State Garbage Collection", source: "AG-UI + Performance", desc: "Old STATE_SNAPSHOTs automatically pruned after retention period. Configurable per-domain (safety: 365d, telemetry: 7d).", zenoh: "c3i/state/gc", crit: 2, usab: 2, info: 2, ux: 2 },

        // ===================================================================
        // CATEGORY 10: Advanced & Future (181-200)
        // ===================================================================
        Idea { id: 181, title: "A2UI Declarative Widget Specs", source: "Google A2UI Spec", desc: "C3I defines domain-specific A2UI widget schemas: MeshNodeGrid, ComplianceMatrix, SparklineChart. Agents propose widget trees, frontend validates and mounts.", zenoh: "c3i/a2ui/widgets", crit: 3, usab: 4, info: 4, ux: 5 },
        Idea { id: 182, title: "MCP-UI Iframe Embedding", source: "Microsoft MCP-UI", desc: "External tools (Grafana, Prometheus, custom dashboards) embedded as MCP-UI iframes within the cockpit. Agent manages iframe lifecycle.", zenoh: "c3i/mcp_ui/iframe/*", crit: 2, usab: 4, info: 3, ux: 4 },
        Idea { id: 183, title: "Open-JSON-UI for Structured Responses", source: "OpenAI Open-JSON-UI", desc: "Agent responses follow Open-JSON-UI schema for consistent structured rendering. Tables, lists, code blocks all typed.", zenoh: "c3i/ojui/responses", crit: 2, usab: 4, info: 4, ux: 4 },
        Idea { id: 184, title: "Self-Healing Mesh via AG-UI Feedback", source: "AG-UI + A2A + OODA", desc: "OODA cycle detects failure, AG-UI interrupts for human approval, Zenoh A2A coordinates recovery across mesh. Closed-loop self-healing.", zenoh: "c3i/self_heal/{incident}", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 185, title: "Digital Twin Generative Visualization", source: "Generative UI + Chaya", desc: "Agent generates a visual digital twin of the mesh: containers, connections, data flow, health states. Interactive and explorable.", zenoh: "c3i/digital_twin/viz", crit: 3, usab: 3, info: 4, ux: 5 },
        Idea { id: 186, title: "Predictive Maintenance Dashboard", source: "OTel + Generative UI", desc: "Agent analyzes trends and predicts when components will fail. Generates timeline showing predicted failure dates and recommended actions.", zenoh: "c3i/predict/maintenance", crit: 4, usab: 3, info: 5, ux: 3 },
        Idea { id: 187, title: "Natural Language System Configuration", source: "AG-UI + MCP", desc: "Operator says 'increase the OODA cycle frequency to every 10 seconds'. Agent translates to config change, seeks approval, applies.", zenoh: "c3i/config/nlp", crit: 3, usab: 5, info: 3, ux: 4 },
        Idea { id: 188, title: "Generative Runbook Creation", source: "Google Generative UI + Safety", desc: "Agent generates interactive runbooks for incident response. Step-by-step guide with clickable actions that trigger actual operations.", zenoh: "c3i/runbook/generate", crit: 3, usab: 4, info: 4, ux: 4 },
        Idea { id: 189, title: "Agent Marketplace via Zenoh", source: "A2A + Zenoh", desc: "Agents advertise capabilities on c3i/marketplace. Operator can 'install' new agents that auto-register with ServiceRegistry.", zenoh: "c3i/marketplace", crit: 2, usab: 3, info: 3, ux: 4 },
        Idea { id: 190, title: "Federated Learning Across Holons", source: "A2A + Zenoh", desc: "Each holon trains local anomaly model. Federated learning aggregates models via Zenoh without sharing raw data.", zenoh: "c3i/federated/model", crit: 3, usab: 2, info: 4, ux: 2 },
        Idea { id: 191, title: "Explainable AI Dashboard", source: "AG-UI REASONING + Generative UI", desc: "For every AI decision, generate an explanation page showing: input features, model weights, decision boundary, confidence score.", zenoh: "c3i/xai/explain/{decision}", crit: 3, usab: 3, info: 5, ux: 4 },
        Idea { id: 192, title: "Chaos Engineering Console", source: "Generative UI + Immune", desc: "Interactive chaos engineering interface: select fault type (CPU spike, network partition, memory leak), target container, duration. Execute and observe.", zenoh: "c3i/chaos/console", crit: 3, usab: 3, info: 4, ux: 4 },
        Idea { id: 193, title: "Regulatory Compliance Report Generator", source: "Generative UI + Safety", desc: "Agent generates full IEC 61508 / DO-178C compliance report with evidence mapping: requirement -> test -> result -> artifact.", zenoh: "c3i/compliance/report", crit: 4, usab: 3, info: 5, ux: 3 },
        Idea { id: 194, title: "Agent Performance Leaderboard", source: "OTel + AG-UI", desc: "Rank agents by: response time, success rate, resource efficiency. Gamified view showing top performers.", zenoh: "c3i/agents/leaderboard", crit: 2, usab: 3, info: 3, ux: 4 },
        Idea { id: 195, title: "Zero-Trust Agent Onboarding", source: "AG-UI Interrupts + Safety", desc: "New agent must pass constitutional checks, capability verification, and operator approval before joining mesh. AG-UI interrupt for human review.", zenoh: "c3i/onboard/{agent_id}", crit: 4, usab: 3, info: 3, ux: 3 },
        Idea { id: 196, title: "Semantic Zoom in Dashboard", source: "Generative UI + HMI", desc: "Zoom out: see entire mesh as abstract boxes. Zoom in: see individual metrics, logs, traces. Continuous semantic zoom.", zenoh: "c3i/ui/semantic_zoom", crit: 2, usab: 4, info: 3, ux: 5 },
        Idea { id: 197, title: "AR Overlay for Physical Infrastructure", source: "AG-UI Multimodality + AR", desc: "Augmented reality overlay shows container health when pointing phone at server rack. AG-UI events stream to AR app.", zenoh: "c3i/modal/ar", crit: 1, usab: 2, info: 3, ux: 5 },
        Idea { id: 198, title: "Generative Test Scenario Builder", source: "Generative UI + Verification", desc: "Agent generates interactive test scenario builder: select fractal layer, component, failure mode. Auto-generates test code.", zenoh: "c3i/test/builder", crit: 3, usab: 3, info: 4, ux: 4 },
        Idea { id: 199, title: "Autonomous Recovery Orchestration", source: "AG-UI + A2A + OODA + Safety", desc: "Full autonomous recovery: OODA detects failure -> A2A coordinates agents -> AG-UI shows progress -> Safety validates -> Guardian approves if needed.", zenoh: "c3i/recovery/auto/{incident}", crit: 5, usab: 3, info: 4, ux: 3 },
        Idea { id: 200, title: "Recursive Meta-Agent for System Evolution", source: "AG-UI + A2A + Generative UI", desc: "A meta-agent that observes system performance, proposes architectural improvements, generates implementation plans, and (with approval) evolves the system.", zenoh: "c3i/meta/evolution", crit: 4, usab: 2, info: 5, ux: 3 },
    ]
}
