defmodule Indrajaal.Repo.Migrations.CreateCoreDomain do
  @moduledoc "
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  "

  use Ecto.Migration

  @spec up() :: any()
  def up do
    create table(:tenants, primary_key: false) do
      add :id,
          :uuid,
          null: false,
          default: fragment("gen_random_uuid()"),
          primary_key: true

      add :name, :text, null: false
      add :slug, :citext, null: false
      add :settings, :map, default: %{}
      add :status, :text, default: "active"
      add :subscription_tier, :text, default: "free"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(
             :tenants,
             [:subscription_tier],
             name: "tenants_subscription_tier_index"
           )

    create index(:tenants, [:status], name: "tenants_status_index")

    create unique_index(:tenants, [:slug], name: "tenants_unique_slug_index")

    create table(:system_configs, primary_key: false) do
      add :tenant_id, :uuid, null: false

      add :id,
          :uuid,
          null: false,
          default: fragment("gen_random_uuid()"),
          primary_key: true

      add :key, :text, null: false
      add :value, :map, null: false
      add :description, :text
      add :category, :text, default: "general"
      add :encrypted?, :boolean, default: false
      add :editable?, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(
             :system_configs,
             [:editable?],
             name: "system_configs_editable_index"
           )

    create index(
             :system_configs,
             [:category],
             name: "system_configs_category_index"
           )

    create unique_index(:system_configs, [:tenant_id, :key],
             name: "system_configs_unique_key_per_tenant_index"
           )

    create table(:organizations, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "organizations_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id,
          :uuid,
          null: false,
          default: fragment("gen_random_uuid()"),
          primary_key: true

      add :name, :text, null: false
      add :code, :text
      add :is_primary, :boolean, default: false
      add :settings, :map, default: %{}
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_organization_id,
          references(:organizations,
            column: :id,
            name: "organizations_parent_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(
             :organizations,
             [:parent_organization_id],
             name: "organizations_hierarchy_index"
           )

    create index(
             :organizations,
             [:tenant_id, :active],
             name: "organizations_active_index"
           )

    create index(:organizations, [:tenant_id, :is_primary],
             name: "organizations_primary_index",
             where: "\"is_primary\" = true"
           )

    create unique_index(:organizations, [:tenant_id, :code],
             name: "organizations_unique_code_per_tenant_index",
             where: "code IS NOT NULL"
           )

    create table(:feature_flags, primary_key: false) do
      add :tenant_id, :uuid, null: false

      add :id,
          :uuid,
          null: false,
          default: fragment("gen_random_uuid()"),
          primary_key: true

      add :name, :text, null: false
      add :key, :text, null: false
      add :enabled, :boolean, default: false
      add :rollout_percentage, :bigint, default: 0
      add :targeting_rules, :map, default: %{}
      add :description, :text
      add :tags, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(
             :feature_flags,
             [:tags],
             name: "feature_flags_tags_index",
             using: "GIN"
           )

    create index(
             :feature_flags,
             [:enabled],
             name: "feature_flags_enabled_index"
           )

    create unique_index(:feature_flags, [:tenant_id, :key],
             name: "feature_flags_unique_key_per_tenant_index"
           )

    create table(:audit_logs, primary_key: false) do
      add :tenant_id, :uuid, null: false

      add :id,
          :uuid,
          null: false,
          default: fragment("gen_random_uuid()"),
          primary_key: true

      add :actor_id, :uuid
      add :actor_type, :text
      add :action, :text, null: false
      add :resource_type, :text, null: false
      add :resource_id, :uuid
      add :changes, :map, default: %{}
      add :metadata, :map, default: %{}
      add :ip_address, :text
      add :__user_agent, :text
      add :__request_id, :uuid
      add :session_id, :uuid
      add :severity, :text, default: "info"
      add :success?, :boolean, default: true
      add :error_message, :text

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(
             :audit_logs,
             [:__request_id],
             name: "audit_logs_request_id_index"
           )

    create index(:audit_logs, [:success?],
             name: "audit_logs_failures_index",
             where: ~s/"success?" = false/
           )

    create index(:audit_logs, [:severity],
             name: "audit_logs_severity_index",
             where: "severity >= 'warning'"
           )

    create index(:audit_logs, [:resource_type, :resource_id, :occurred_at],
             name: "audit_logs_resource_time_index"
           )

    create index(
             :audit_logs,
             [:actor_id, :occurred_at],
             name: "audit_logs_actor_time_index"
           )

    create index(
             :audit_logs,
             [:tenant_id, :occurred_at],
             name: "audit_logs_tenant_time_index"
           )

    # TimescaleDB setup removed for development environment
    # execute("
    # SELECT create_hypertable('audit_logs', 'occurred_at',
    #   chunk_time_interval => interval '1 day',
    #   if_not_exists => true
    # );
    # ")

    # execute("
    # ALTER TABLE audit_logs SET (
    #   timescaledb.compress,
    #   timescaledb.compress_segmentby = 'tenant_id',
    #   timescaledb.compress_orderby = 'occurred_at DESC'
    # );

    # SELECT add_compression_policy('audit_logs', INTERVAL '30 days');
    # ")

    # execute("
    # SELECT add_retention_policy('audit_logs', INTERVAL '1 year');
    # ")
  end

  @spec down() :: any()
  def down do
    # TimescaleDB cleanup removed for development environment
    # execute("
    # SELECT remove_retention_policy('audit_logs');
    # ")

    # execute("
    # SELECT remove_compression_policy('audit_logs');
    # ")

    # execute("
    # -- Hypertables cannot be easily reverted
    # ")

    drop_if_exists index(:audit_logs, [:tenant_id, :occurred_at],
                     name: "audit_logs_tenant_time_index"
                   )

    drop_if_exists index(:audit_logs, [:actor_id, :occurred_at],
                     name: "audit_logs_actor_time_index"
                   )

    drop_if_exists index(
                     :audit_logs,
                     [:resource_type, :resource_id, :occurred_at],
                     name: "audit_logs_resource_time_index"
                   )

    drop_if_exists index(
                     :audit_logs,
                     [:severity],
                     name: "audit_logs_severity_index"
                   )

    drop_if_exists index(
                     :audit_logs,
                     [:success?],
                     name: "audit_logs_failures_index"
                   )

    drop_if_exists index(
                     :audit_logs,
                     [:__request_id],
                     name: "audit_logs_request_id_index"
                   )

    drop table(:audit_logs)

    drop_if_exists unique_index(:feature_flags, [:tenant_id, :key],
                     name: "feature_flags_unique_key_per_tenant_index"
                   )

    drop_if_exists index(:feature_flags, [:tenant_id, :key],
                     name: "feature_flags_unique_key_per_tenant_index"
                   )

    drop_if_exists index(
                     :feature_flags,
                     [:enabled],
                     name: "feature_flags_enabled_index"
                   )

    drop_if_exists index(
                     :feature_flags,
                     [:tags],
                     name: "feature_flags_tags_index"
                   )

    drop table(:feature_flags)

    drop_if_exists unique_index(:organizations, [:tenant_id, :code],
                     name: "organizations_unique_code_per_tenant_index"
                   )

    drop constraint(:organizations, "organizations_tenant_id_fkey")

    drop constraint(:organizations, "organizations_parent_organization_id_fkey")

    drop_if_exists index(:organizations, [:tenant_id, :code],
                     name: "organizations_unique_code_per_tenant_index"
                   )

    drop_if_exists index(:organizations, [:tenant_id, :is_primary],
                     name: "organizations_primary_index"
                   )

    drop_if_exists index(:organizations, [:tenant_id, :active],
                     name: "organizations_active_index"
                   )

    drop_if_exists index(:organizations, [:parent_organization_id],
                     name: "organizations_hierarchy_index"
                   )

    drop table(:organizations)

    drop_if_exists unique_index(:system_configs, [:tenant_id, :key],
                     name: "system_configs_unique_key_per_tenant_index"
                   )

    drop_if_exists index(:system_configs, [:tenant_id, :key],
                     name: "system_configs_unique_key_per_tenant_index"
                   )

    drop_if_exists index(
                     :system_configs,
                     [:category],
                     name: "system_configs_category_index"
                   )

    drop_if_exists index(
                     :system_configs,
                     [:editable?],
                     name: "system_configs_editable_index"
                   )

    drop table(:system_configs)

    drop_if_exists unique_index(
                     :tenants,
                     [:slug],
                     name: "tenants_unique_slug_index"
                   )

    drop_if_exists index(:tenants, [:slug], name: "tenants_unique_slug_index")

    drop_if_exists index(:tenants, [:status], name: "tenants_status_index")

    drop_if_exists index(
                     :tenants,
                     [:subscription_tier],
                     name: "tenants_subscription_tier_index"
                   )

    drop table(:tenants)
  end
end

# Agent: Helper - 2 (General Purpose Agent)
# SOPv5.1 Compliance: ✅ General system coordination and management with cyberne
# Domain: General
# Responsibilities: Template generation, standards enforcement, general coordin
# Multi - Agent Architecture: Integrated with 11 - agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
