#!/bin/sh
# INDRAJAAL ARK v4.0 - SIL-6 BIOMORPHIC ARCHIVE
# DO NOT EDIT THIS FILE. IT IS A BINARY ORGANISM.
#
# This header allows the Ark to function as a standard shell script.
# It extracts the embedded "Capsid" (Rust Binary) and executes it.

set -e

# Find the seam
# We construct the search string to avoid grep finding THIS line.
S1="|||INDRAJAAL"
S2="_DNA_SEP|||"
SEAM="$S1$S2"

# grep -a (process binary), -b (byte offset), -o (only matching)
# We expect matches. 
# Match 1: Might be in the binary if obfuscation failed (hopefully not).
# Match 2: The actual Seam.
#
# We filter matches > 4096 to skip the header area itself.
#
skip=$(grep -a -b -o "$SEAM" "$0" | awk -F: '$1 > 4096 {print $1}' | head -n 1)

if [ -z "$skip" ]; then
  echo "CRITICAL ERROR: Biomorphic seam not found. The Ark is corrupted."
  exit 1
fi

# The binary starts after this script (approx 128-512 bytes) and ends at the seam.
# Wait, my previous logic was: Header -> Capsid -> Seam -> Data.
# So the binary starts *immediately* after the `exit` of this script?
# No, that's hard to calculate reliably across shells.
#
# Robust Strategy:
# The Seam marks the START of the DATA.
# The CAPSID (Binary) is between the HEADER END and the SEAM.
# But `grep` finds the Seam. We need to find the start of the binary.
#
# Simplified Layout for v4.0:
# 1. This Script (Padded to fixed 4096 bytes)
# 2. Rust Binary (Capsid)
# 3. Magic Seam (|||INDRAJAAL_DNA_SEP|||)
# 4. Data...
#
# Actually, the Rust binary handles finding the seam. 
# We just need to extract the Rust binary.
# If we pad this script to 4096 bytes, we know the binary starts at 4096.
# The binary ends at Seam - SeamLen.

# Let's assume the builder ensures this script is exactly 4096 bytes.
BINARY_START=4096
SEAM_OFFSET=$skip

# Extract Capsid
tmp_dir=$(mktemp -d /tmp/ark.XXXXXX)
capsid="$tmp_dir/capsid"

# We calculate size of binary: Seam Offset - Binary Start
binary_size=$((SEAM_OFFSET - BINARY_START))

# Use dd to extract just the binary part
dd if="$0" of="$capsid" bs=1 skip=$BINARY_START count=$binary_size status=none

chmod +x "$capsid"

# Check if we can execute in /tmp (often mounted noexec)
if ! "$capsid" --help >/dev/null 2>&1; then
  # Fallback to local directory or $HOME
  if [ -w "." ]; then
    alt_dir="."
  else
    alt_dir="$HOME"
  fi
  
  # Clean up /tmp attempt
  rm -rf "$tmp_dir"
  
  # Try fallback
  tmp_dir=$(mktemp -d "$alt_dir/ark.XXXXXX")
  capsid="$tmp_dir/capsid"
  dd if="$0" of="$capsid" bs=1 skip=$BINARY_START count=$binary_size status=none
  chmod +x "$capsid"
fi

# Execute Capsid, passing the Ark path ($0) and any other args
"$capsid" "$0" "$@"
ret=$?

# Cleanup
rm -rf "$tmp_dir"
exit $ret

# PAD_TO_4096_BYTES_BELOW
