// =============================================================================
// Artifacts.fs - Embedded Mesh Configuration and Dockerfiles
// =============================================================================
// GENERATED BY scripts/automation/GenerateArtifacts.fsx
// =============================================================================

namespace Cepaf.Mesh

module Artifacts =

    let [<Literal>] SIL6_COMPOSE = """
# podman-compose-sil6-full-mesh.yml
# SIL-6 Biomorphic Fractal Mesh - Full 16-Container Architecture
# WHAT: Complete mesh with Cognitive Plane (Cortex, CEPAF Bridge) + Zenoh Control Plane
# WHY: Production-equivalent environment with all mesh services
# CONSTRAINTS: Requires rootless Podman 5.4.1+, NixOS images, ~27GB RAM
# STAMP: SC-SIL6-001, SC-MESH-001, SC-CNT-009, SC-CNT-010, SC-CNT-012

version: '3.8'

networks:
  indrajaal-sil6-mesh:
    name: indrajaal-sil6-mesh
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

  indrajaal-internal:
    name: indrajaal-internal
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.29.0.0/16

services:
  # =============================================================================
  # DATA TIER - PostgreSQL + TimescaleDB (172.28.0.20)
  # =============================================================================

  indrajaal-db-prod:
    image: localhost/indrajaal-db-prod:latest
    container_name: indrajaal-db-prod
    hostname: indrajaal-db-prod
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.20
      indrajaal-internal:
    environment:
      POSTGRES_DB: indrajaal_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: "5433"
      TS_TUNE_MEMORY: 4GB
      TS_TUNE_NUM_CPUS: 4
      PHICS_ENABLED: "true"
      NO_TIMEOUT: "true"
      CONTAINER_OS: nixos
      SOPV51_COMPLIANT: "true"
      PGDATA: /var/lib/postgresql/pgdata
    ports:
      - "5433:5433"
    volumes:
      - db_prod_data:/var/lib/postgresql/pgdata:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d indrajaal_prod -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: database
      environment: sil6-mesh
      stamp.verified: "true"
      sil.level: "6"

  # =============================================================================
  # OBSERVABILITY TIER - OTEL + Prometheus + Grafana + Loki + SigNoz (172.28.0.30)
  # =============================================================================

  indrajaal-obs-prod:
    image: localhost/indrajaal-obs-prod:latest
    container_name: indrajaal-obs-prod
    hostname: indrajaal-obs-prod
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.30
    environment:
      HOME: /tmp
      DOTNET_CLI_HOME: /tmp
      # OpenTelemetry Collector
      OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
      OTEL_SERVICE_NAME: indrajaal-obs-prod
      LOG_LEVEL: info
      FRACTAL_LOGGING_ENABLED: "true"

      # Prometheus
      PROMETHEUS_RETENTION_TIME: 15d
      PROMETHEUS_RETENTION_SIZE: 10GB

      # Grafana
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: indrajaal
      GF_SERVER_HTTP_PORT: "3000"
      # GF_INSTALL_PLUGINS removed - plugins require internet access which may not be available
      # grafana-clock-panel and grafana-simple-json-datasource can be installed later
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning

      # Loki
      LOKI_RETENTION_PERIOD: 168h

      # SigNoz Configuration
      SIGNOZ_ENABLED: "true"
      SIGNOZ_QUERY_SERVICE_URL: http://localhost:8080
      SIGNOZ_FRONTEND_PORT: "3301"
      SIGNOZ_ALERT_MANAGER_PORT: "9093"

      # SigNoz ClickHouse (embedded)
      CLICKHOUSE_HOST: localhost
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_HTTP_PORT: "8123"
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DATABASE: signoz_traces
      CLICKHOUSE_TRACES_TABLE: signoz_index_v2
      CLICKHOUSE_METRICS_TABLE: signoz_metrics
      CLICKHOUSE_LOGS_TABLE: signoz_logs

      # Integration flags
      UNIFIED_OBS_MODE: "true"
      SOPV51_COMPLIANT: "true"
    ports:
      # OTEL Collector
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # OTEL metrics
      # Prometheus
      - "9090:9090"
      # Grafana
      - "3000:3000"
      # Loki
      - "3100:3100"
      # SigNoz
      - "3301:3301"   # SigNoz Frontend
      - "8080:8080"   # SigNoz Query Service
      - "9093:9093"   # SigNoz Alert Manager
      # ClickHouse (SigNoz backend)
      - "8123:8123"   # ClickHouse HTTP
      - "9000:9000"   # ClickHouse Native
    volumes:
      - otel_prod_data:/var/log/otel:z
      - prometheus_prod_data:/prometheus:z
      - grafana_prod_data:/var/lib/grafana:z
      - loki_prod_data:/loki:z
      - signoz_prod_data:/var/lib/signoz:z
      - clickhouse_prod_data:/var/lib/clickhouse:z
      - ../../../:/workspace:z
    healthcheck:
      # SC-SIL6-004: Graceful degradation - Only Prometheus + Grafana are mandatory
      # OTEL collector (8888) and SigNoz (8080) are optional, may not be configured
      test: ["CMD-SHELL", "curl -sf http://localhost:9090/-/healthy > /dev/null && curl -sf http://localhost:3000/api/health > /dev/null"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '0.5'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: observability
      environment: sil6-mesh
      services: otel,prometheus,grafana,loki,signoz,clickhouse
      sil.level: "6"

  # =============================================================================
  # MESH CONTROL PLANE - Zenoh Routers (2oo3 Redundancy) (172.28.0.40-42)
  # SC-SIL6-006: 2oo3 voting MANDATORY for production actuations
  # =============================================================================

  # Primary Router (172.28.0.40)
  zenoh-router-1:
    image: localhost/zenoh-router:latest
    container_name: zenoh-router-1
    hostname: zenoh-router-1
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.40
    environment:
      RUST_LOG: info
      ZENOH_ROUTER_ID: router-1
    ports:
      - "7447:7447"   # TCP/Quic transport
      - "8448:8448"   # WebSocket transport
      - "8000:8000"   # REST API (for health checks)
    volumes:
      - ../../../config/zenoh/zenoh-router-1.json5:/zenoh.json5:ro
    command: ["-c", "/zenoh.json5"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: zenoh-router
      environment: sil6-mesh
      mesh.role: control-plane
      mesh.quorum: router-1
      sil.level: "6"

  # Secondary Router (172.28.0.41)
  zenoh-router-2:
    image: localhost/zenoh-router:latest
    container_name: zenoh-router-2
    hostname: zenoh-router-2
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.41
    environment:
      RUST_LOG: info
      ZENOH_ROUTER_ID: router-2
    ports:
      - "7448:7447"   # TCP/Quic transport (offset port)
      - "8449:8448"   # WebSocket transport (offset port)
      - "8001:8000"   # REST API (offset port)
    volumes:
      - ../../../config/zenoh/zenoh-router-2.json5:/zenoh.json5:ro
    command: ["-c", "/zenoh.json5"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: zenoh-router
      environment: sil6-mesh
      mesh.role: control-plane
      mesh.quorum: router-2
      sil.level: "6"

  # Tertiary Router (172.28.0.42) - 2oo3 Quorum
  zenoh-router-3:
    image: localhost/zenoh-router:latest
    container_name: zenoh-router-3
    hostname: zenoh-router-3
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.42
    environment:
      RUST_LOG: info
      ZENOH_ROUTER_ID: router-3
    ports:
      - "7449:7447"   # TCP/Quic transport (offset port)
      - "8450:8448"   # WebSocket transport (offset port)
      - "8002:8000"   # REST API (offset port)
    volumes:
      - ../../../config/zenoh/zenoh-router-3.json5:/zenoh.json5:ro
    command: ["-c", "/zenoh.json5"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: zenoh-router
      environment: sil6-mesh
      mesh.role: control-plane
      mesh.quorum: router-3
      sil.level: "6"

  # Legacy alias for backwards compatibility
  zenoh-router:
    image: localhost/zenoh-router:latest
    container_name: zenoh-router
    hostname: zenoh-router
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.43
    depends_on:
      zenoh-router-1:
        condition: service_healthy
      zenoh-router-2:
        condition: service_healthy
      zenoh-router-3:
        condition: service_healthy
    environment:
      RUST_LOG: info
      ZENOH_ROUTER_ID: router-proxy
    volumes:
      - ../../../config/zenoh/zenoh.json5:/zenoh.json5:ro
    command: ["-c", "/zenoh.json5"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: zenoh-router
      environment: sil6-mesh
      mesh.role: control-plane-proxy
      sil.level: "6"

  # =============================================================================
  # COGNITIVE PLANE - CEPAF Bridge (172.28.0.50)
  # =============================================================================

  cepaf-bridge:
    image: localhost/cepaf-bridge:latest
    container_name: cepaf-bridge
    hostname: cepaf-bridge
    stdin_open: true
    tty: true
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.50
    depends_on:
      zenoh-router:
        condition: service_healthy
    environment:
      CEPAF_BRIDGE_PORT: "9876"
      CEPAF_BRIDGE_HOST: "0.0.0.0"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router:7447
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: cepaf-bridge
      DOTNET_RUNNING_IN_CONTAINER: "true"
      PODMAN_SOCKET: /run/podman/podman.sock
    volumes:
      - /run/user/1000/podman/podman.sock:/run/podman/podman.sock:z
    ports:
      - "9876:9876"   # JSON-RPC bridge
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/cepaf-bridge-ready || curl -sf http://localhost:9876/health > /dev/null || exit 0"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: cepaf-bridge
      environment: sil6-mesh
      mesh.role: cognitive-plane
      stamp.constraint: SC-SYNC-001
      sil.level: "6"

  # =============================================================================
  # COGNITIVE PLANE - F# Cortex (172.28.0.60)
  # =============================================================================

  indrajaal-cortex:
    image: localhost/indrajaal-cortex:latest
    container_name: indrajaal-cortex
    hostname: indrajaal-cortex
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.60
    depends_on:
      zenoh-router:
        condition: service_healthy
      cepaf-bridge:
        condition: service_healthy
    environment:
      CORTEX_PORT: "9877"
      CORTEX_HOST: "0.0.0.0"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router:7447
      CEPAF_BRIDGE_URL: http://cepaf-bridge:9876
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-cortex
      DOTNET_RUNNING_IN_CONTAINER: "true"
    ports:
      - "9877:9877"   # Cortex API
    # Override entrypoint: --cortex CLI mode not yet implemented in Cepaf CLI
    # Runs in standby mode until Cortex HTTP API is built (future sprint)
    entrypoint: ["bash", "-c", "echo 'Cortex standby — awaiting --cortex CLI implementation' && while true; do sleep 3600; done"]
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'sleep 3600' || pgrep -f bash"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: cortex
      environment: sil6-mesh
      mesh.role: cognitive-plane
      stamp.constraint: SC-MESH-006
      sil.level: "6"

  # =============================================================================
  # COGNITIVE PLANE - Local AI (Ollama) (172.28.0.65)
  # =============================================================================

  indrajaal-ollama:
    image: localhost/indrajaal-ollama:latest
    container_name: indrajaal-ollama
    hostname: indrajaal-ollama
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.65
    volumes:
      - ollama_prod_data:/root/.ollama:z
    ports:
      - "11435:11434"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo -e \"GET /api/tags HTTP/1.0\\r\\nHost: localhost\\r\\n\\r\\n\" > /dev/tcp/localhost/11434' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: local-ai
      environment: sil6-mesh
      sil.level: "6"

  # =============================================================================
  # APPLICATION TIER - Phoenix + FLAME + Clustering + Redis (172.28.0.10)
  # =============================================================================

  indrajaal-ex-app-1:
    image: localhost/indrajaal-ex-app-1:latest
    container_name: indrajaal-ex-app-1
    hostname: indrajaal-ex-app-1
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.10
      indrajaal-internal:
    depends_on:
      indrajaal-db-prod:
        condition: service_healthy
      indrajaal-obs-prod:
        condition: service_started
      zenoh-router:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      DATABASE_SSL: "false"
      POSTGRES_HOST: indrajaal-db-prod
      POSTGRES_PORT: "5433"
      POSTGRES_DB: indrajaal_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      # Redis (embedded)
      REDIS_EMBEDDED: "true"
      REDIS_URL: redis://localhost:6379
      REDIS_HOST: localhost
      REDIS_PORT: "6379"

      # Phoenix
      PHX_HOST: localhost
      PHX_PORT: "4000"
      SECRET_KEY_BASE: production_equivalent_secret_key_base_64_chars_minimum_here_change_me

      # FLAME Configuration
      FLAME_ENABLED: "true"
      FLAME_BACKEND: local
      FLAME_MIN_POOL: "2"
      FLAME_MAX_POOL: "10"

      # Clustering
      CLUSTERING_ENABLED: "true"
      RELEASE_NODE: indrajaal@indrajaal-ex-app-1
      RELEASE_COOKIE: indrajaal_prod_cookie

      # Prajna Cockpit
      PRAJNA_COCKPIT_ENABLED: "true"
      PRAJNA_DARK_MODE: "true"
      PRAJNA_AI_COPILOT_ENABLED: "true"

      # OpenRouter AI
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      OPENROUTER_MODEL: anthropic/claude-3.5-sonnet

      # Observability - VERBOSE MODE
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-ex-app-1
      FRACTAL_LOGGING_ENABLED: "true"
      LOG_LEVEL: debug
      VERBOSE_LOGGING: "true"
      DASHBOARD_MODE: "true"
      CONSOLE_LOGGING: "true"
      KPI_DISPLAY: "true"
      STATE_DISPLAY: "true"
      TELEMETRY_VERBOSE: "true"
      ZENOH_LOG_LEVEL: debug
      SENTINEL_VERBOSE: "true"
      OODA_VERBOSE: "true"

      # Zenoh Mesh Integration (SIL-6)
      ZENOH_ENABLED: "true"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router:7447
      # SC-ZENOH-001: Zenoh NIF must be active on seed node
      # NIF compiles from host-mounted source; Rust required in image
      SKIP_ZENOH_NIF: "0"
      SKIP_LINEAGE_NIF: "1"
      RUSTLER_SKIP_COMPILE: "false"

      # Cognitive Plane Integration
      CEPAF_BRIDGE_URL: http://cepaf-bridge:9876
      CORTEX_URL: http://indrajaal-cortex:9877

      # Tailscale Mesh Integration
      TAILSCALE_ENABLED: "true"
      TAILSCALE_SOCKET: /var/run/tailscale/tailscaled.sock
      TS_USERSPACE_NETWORK: "true"
      TS_AUTH_KEY: ${TAILSCALE_AUTH_KEY:-}

      # Framework
      PHICS_ENABLED: "true"
      NO_TIMEOUT: "true"
      PATIENT_MODE: enabled
      SOPV51_COMPLIANT: "true"
      UNIFIED_APP_MODE: "true"
      SIL_LEVEL: "6"
      # Production mode to avoid FileSystem dependency (phoenix_live_reload)
      MIX_ENV: "prod"
      # Locale fix for Elixir UTF-8
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      ELIXIR_ERL_OPTIONS: "+fnu +S 16:16 +SDio 16"
    command: ["sh", "-c", "mix local.hex --force && mix local.rebar --force && MIX_ENV=prod mix deps.get && MIX_ENV=prod mix compile && MIX_ENV=prod mix ecto.create && MIX_ENV=prod mix ecto.migrate && MIX_ENV=prod mix phx.server"]
    ports:
      - "4000:4000"   # Phoenix
      - "4001:4001"   # Health
      - "6379:6379"   # Redis (exposed for debugging)
    volumes:
      - app_prod_data:/app/data:z
      - redis_prod_data:/var/lib/redis:z
      # Persist compilation state to survive restarts
      - app_build_cache_1:/workspace/_build:z
      - app_deps_cache_1:/workspace/deps:z
      # Mount source from host for development
      - ../../../:/workspace:z
      # Tailscale integration (mount from host)
      - /var/run/tailscale:/var/run/tailscale:ro
      - /usr/bin/tailscale:/usr/bin/tailscale:ro
      - /usr/sbin/tailscaled:/usr/sbin/tailscaled:ro
    working_dir: /workspace
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4000/ > /dev/null || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 30
      start_period: 900s
    deploy:
      resources:
        limits:
          memory: 20G
          cpus: '2.0'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: application
      environment: sil6-mesh
      stamp.verified: "true"
      flame.enabled: "true"
      clustering.enabled: "true"
      redis.embedded: "true"
      zenoh.enabled: "true"
      services: phoenix,flame,clustering,redis,zenoh
      sil.level: "6"

  # =============================================================================
  # APPLICATION TIER - HA NODE 2 (172.28.0.11)
  # =============================================================================

  indrajaal-ex-app-2:
    image: localhost/indrajaal-ex-app-1:latest
    container_name: indrajaal-ex-app-2
    hostname: indrajaal-ex-app-2
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.11
      indrajaal-internal:
    depends_on:
      indrajaal-ex-app-1:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      DATABASE_SSL: "false"
      POSTGRES_HOST: indrajaal-db-prod
      POSTGRES_PORT: "5433"
      POSTGRES_DB: indrajaal_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://indrajaal-ex-app-1:6379
      REDIS_HOST: indrajaal-ex-app-1
      REDIS_PORT: "6379"
      PHX_HOST: localhost
      PHX_PORT: "4000"
      SECRET_KEY_BASE: production_equivalent_secret_key_base_64_chars_minimum_here_change_me
      FLAME_ENABLED: "true"
      FLAME_BACKEND: local
      FLAME_MIN_POOL: "2"
      FLAME_MAX_POOL: "10"
      CLUSTERING_ENABLED: "true"
      RELEASE_NODE: indrajaal@indrajaal-ex-app-2
      RELEASE_COOKIE: indrajaal_prod_cookie
      ZENOH_ENABLED: "true"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router:7447
      SKIP_ZENOH_NIF: "0"
      SKIP_LINEAGE_NIF: "1"
      RUSTLER_SKIP_COMPILE: "false"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-ex-app-2
      CEPAF_BRIDGE_URL: http://cepaf-bridge:9876
      CORTEX_URL: http://indrajaal-cortex:9877
      TAILSCALE_ENABLED: "false"
      PHICS_ENABLED: "true"
      NO_TIMEOUT: "true"
      PATIENT_MODE: enabled
      LOG_LEVEL: info
      MIX_ENV: "prod"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      SIL_LEVEL: "6"
      ELIXIR_ERL_OPTIONS: "+fnu +S 16:16 +SDio 16"
    command: ["sh", "-c", "mix local.hex --force && mix local.rebar --force && MIX_ENV=prod mix deps.get && MIX_ENV=prod mix compile && MIX_ENV=prod mix phx.server"]
    ports:
      - "4003:4000"   # Phoenix (Offset)
      - "4004:4001"   # Health (Offset)
    volumes:
      - app_prod_data_2:/app/data:z
      - app_build_cache_2:/workspace/_build:z
      - app_deps_cache_2:/workspace/deps:z
      - ../../../:/workspace:z
    working_dir: /workspace
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4000/ > /dev/null || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 30
      start_period: 600s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: application
      environment: sil6-mesh
      role: ha-node-2

  # =============================================================================
  # APPLICATION TIER - HA NODE 3 (172.28.0.12)
  # =============================================================================

  indrajaal-ex-app-3:
    image: localhost/indrajaal-ex-app-1:latest
    container_name: indrajaal-ex-app-3
    hostname: indrajaal-ex-app-3
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.12
      indrajaal-internal:
    depends_on:
      indrajaal-ex-app-2:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      DATABASE_SSL: "false"
      POSTGRES_HOST: indrajaal-db-prod
      POSTGRES_PORT: "5433"
      POSTGRES_DB: indrajaal_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://indrajaal-ex-app-1:6379
      REDIS_HOST: indrajaal-ex-app-1
      REDIS_PORT: "6379"
      PHX_HOST: localhost
      PHX_PORT: "4000"
      SECRET_KEY_BASE: production_equivalent_secret_key_base_64_chars_minimum_here_change_me
      FLAME_ENABLED: "true"
      FLAME_BACKEND: local
      FLAME_MIN_POOL: "2"
      FLAME_MAX_POOL: "10"
      CLUSTERING_ENABLED: "true"
      RELEASE_NODE: indrajaal@indrajaal-ex-app-3
      RELEASE_COOKIE: indrajaal_prod_cookie
      ZENOH_ENABLED: "true"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router:7447
      SKIP_ZENOH_NIF: "0"
      SKIP_LINEAGE_NIF: "1"
      RUSTLER_SKIP_COMPILE: "false"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-ex-app-3
      CEPAF_BRIDGE_URL: http://cepaf-bridge:9876
      CORTEX_URL: http://indrajaal-cortex:9877
      TAILSCALE_ENABLED: "false"
      PHICS_ENABLED: "true"
      NO_TIMEOUT: "true"
      PATIENT_MODE: enabled
      LOG_LEVEL: info
      MIX_ENV: "prod"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      SIL_LEVEL: "6"
      ELIXIR_ERL_OPTIONS: "+fnu +S 16:16 +SDio 16"
    command: ["sh", "-c", "mix local.hex --force && mix local.rebar --force && MIX_ENV=prod mix deps.get && MIX_ENV=prod mix compile && MIX_ENV=prod mix phx.server"]
    ports:
      - "4005:4000"   # Phoenix (Offset)
      - "4006:4001"   # Health (Offset)
    volumes:
      - app_prod_data_3:/app/data:z
      - app_build_cache_3:/workspace/_build:z
      - app_deps_cache_3:/workspace/deps:z
      - ../../../:/workspace:z
    working_dir: /workspace
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4000/ > /dev/null || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 30
      start_period: 600s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: application
      environment: sil6-mesh
      role: ha-node-3

  # =============================================================================
  # DIGITAL TWIN PLANE - Chaya (172.28.0.70)
  # =============================================================================

  indrajaal-chaya:
    image: localhost/indrajaal-ex-app-1:latest
    container_name: indrajaal-chaya
    hostname: indrajaal-chaya
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.70
      indrajaal-internal:
    depends_on:
      indrajaal-ex-app-1:
        condition: service_healthy
      zenoh-router:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      DATABASE_SSL: "false"
      POSTGRES_HOST: indrajaal-db-prod
      POSTGRES_PORT: "5433"
      POSTGRES_DB: indrajaal_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://indrajaal-ex-app-1:6379
      CHAYA_MODE: "true"
      RELEASE_NODE: chaya@indrajaal-chaya
      RELEASE_COOKIE: indrajaal_prod_cookie
      ZENOH_ENABLED: "true"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router:7447
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-chaya
      PHX_SERVER: "true"
      PHX_PORT: "4002"
      SECRET_KEY_BASE: production_equivalent_secret_key_base_64_chars_minimum_here_change_me
      MIX_ENV: "prod"
      SKIP_ZENOH_NIF: "0"
      SKIP_LINEAGE_NIF: "1"
      RUSTLER_SKIP_COMPILE: "false"
      LOG_LEVEL: info
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      SIL_LEVEL: "6"
    volumes:
      - app_prod_data_chaya:/app/data:z
      - app_build_cache_chaya:/workspace/_build:z
      - app_deps_cache_chaya:/workspace/deps:z
      - ../../../:/workspace:z
    working_dir: /workspace
    command: ["sh", "-c", "mix local.hex --force && mix local.rebar --force && MIX_ENV=prod mix deps.get && MIX_ENV=prod mix compile && MIX_ENV=prod mix phx.server"]
    ports:
      - "4002:4002"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4002/ > /dev/null || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 30
      start_period: 600s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.25'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: chaya
      role: digital-twin

  # =============================================================================
  # SATELLITE PLANE - ML Flame Runners (172.28.0.80-81)
  # =============================================================================

  indrajaal-ml-runner-1:
    image: localhost/indrajaal-ex-app-1:latest
    container_name: indrajaal-ml-runner-1
    hostname: indrajaal-ml-runner-1
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.80
      indrajaal-internal:
    depends_on:
      indrajaal-ex-app-1:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      DATABASE_SSL: "false"
      FLAME_PARENT: indrajaal@indrajaal-ex-app-1
      RELEASE_NODE: runner1@indrajaal-ml-runner-1
      RELEASE_COOKIE: indrajaal_prod_cookie
      PHX_SERVER: "false"
      MIX_ENV: "prod"
      SKIP_ZENOH_NIF: "0"
      SKIP_LINEAGE_NIF: "1"
      RUSTLER_SKIP_COMPILE: "false"
      LOG_LEVEL: info
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    volumes:
      - app_prod_data_ml1:/app/data:z
      - app_build_cache_ml1:/workspace/_build:z
      - app_deps_cache_ml1:/workspace/deps:z
      - ../../../:/workspace:z
    working_dir: /workspace
    command: ["sh", "-c", "mix local.hex --force && mix local.rebar --force && MIX_ENV=prod mix deps.get && MIX_ENV=prod mix compile && echo 'ML Runner 1 ready' && touch /tmp/ml-runner-ready && sleep infinity"]
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/ml-runner-ready"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 600s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: flame-runner
      role: satellite-ml-1

  indrajaal-ml-runner-2:
    image: localhost/indrajaal-ex-app-1:latest
    container_name: indrajaal-ml-runner-2
    hostname: indrajaal-ml-runner-2
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.81
      indrajaal-internal:
    depends_on:
      indrajaal-ml-runner-1:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      DATABASE_SSL: "false"
      FLAME_PARENT: indrajaal@indrajaal-ex-app-1
      RELEASE_NODE: runner2@indrajaal-ml-runner-2
      RELEASE_COOKIE: indrajaal_prod_cookie
      PHX_SERVER: "false"
      MIX_ENV: "prod"
      SKIP_ZENOH_NIF: "0"
      SKIP_LINEAGE_NIF: "1"
      RUSTLER_SKIP_COMPILE: "false"
      LOG_LEVEL: info
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    volumes:
      - app_prod_data_ml2:/app/data:z
      - app_build_cache_ml2:/workspace/_build:z
      - app_deps_cache_ml2:/workspace/deps:z
      - ../../../:/workspace:z
    working_dir: /workspace
    command: ["sh", "-c", "mix local.hex --force && mix local.rebar --force && MIX_ENV=prod mix deps.get && MIX_ENV=prod mix compile && echo 'ML Runner 2 ready' && touch /tmp/ml-runner-ready && sleep infinity"]
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/ml-runner-ready"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 600s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: flame-runner
      role: satellite-ml-2

  # =============================================================================
  # COMPUTE TIER - Mojo MAX Inference Stub (172.28.0.90)
  # =============================================================================

  indrajaal-mojo:
    image: localhost/indrajaal-mojo:latest
    container_name: indrajaal-mojo
    hostname: indrajaal-mojo
    networks:
      indrajaal-sil6-mesh:
        ipv4_address: 172.28.0.90
    depends_on:
      zenoh-router:
        condition: service_healthy
    ports:
      - "11436:11436"   # MAX Inference API (stub)
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 11436 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: mojo-compute
      environment: sil6-mesh
      mesh.role: compute-plane
      stamp.constraint: SC-MOJO-001
      sil.level: "6"

volumes:
  db_prod_data:
  otel_prod_data:
  prometheus_prod_data:
  grafana_prod_data:
  loki_prod_data:
  signoz_prod_data:
  clickhouse_prod_data:
  ollama_prod_data:
  app_prod_data:
  redis_prod_data:
  # Persistent compilation cache per app container (isolated to avoid race conditions)
  app_build_cache_1:
  app_deps_cache_1:
  app_build_cache_2:
  app_deps_cache_2:
  app_build_cache_3:
  app_deps_cache_3:
  app_build_cache_chaya:
  app_deps_cache_chaya:
  app_build_cache_ml1:
  app_deps_cache_ml1:
  app_prod_data_2:
  app_prod_data_3:
  app_prod_data_chaya:
  app_prod_data_ml1:
  app_prod_data_ml2:
  app_build_cache_ml2:
  app_deps_cache_ml2:

# =============================================================================
# Architecture: SIL-6 Biomorphic Fractal Mesh (6 Containers)
# =============================================================================
#
# ┌────────────────────────────────────────────────────────────────────────────────┐
# │                     SIL-6 BIOMORPHIC FRACTAL MESH (6 Containers)               │
# ├────────────────────────────────────────────────────────────────────────────────┤
# │                                                                                 │
# │  ┌─────────────────────────────────────────────────────────────────────────┐   │
# │  │ COGNITIVE PLANE (F# .NET 10.0)                                          │   │
# │  │  ┌─────────────────────┐  ┌─────────────────────┐                       │   │
# │  │  │ indrajaal-cortex    │  │ cepaf-bridge        │                       │   │
# │  │  │ :9877               │  │ :9876               │                       │   │
# │  │  │ 172.28.0.60         │  │ 172.28.0.50         │                       │   │
# │  │  └─────────────────────┘  └─────────────────────┘                       │   │
# │  └─────────────────────────────────────────────────────────────────────────┘   │
# │                             │                                                   │
# │                             ▼ Zenoh Pub/Sub                                    │
# │  ┌─────────────────────────────────────────────────────────────────────────┐   │
# │  │ MESH CONTROL PLANE                                                       │   │
# │  │  ┌───────────────────────────────────────────────────────────────┐      │   │
# │  │  │ zenoh-router (eclipse/zenoh:1.0.0)                            │      │   │
# │  │  │ :7447 (TCP) | :8448 (WebSocket) | :8000 (REST API)            │      │   │
# │  │  │ 172.28.0.40                                                    │      │   │
# │  │  └───────────────────────────────────────────────────────────────┘      │   │
# │  └─────────────────────────────────────────────────────────────────────────┘   │
# │                             │                                                   │
# │                             ▼                                                   │
# │  ┌─────────────────────────────────────────────────────────────────────────┐   │
# │  │ APPLICATION PLANE                                                        │   │
# │  │  ┌─────────────────────────────────────────────────────────────────┐    │   │
# │  │  │ indrajaal-ex-app-1 (Phoenix + FLAME + Redis + Zenoh NIF)        │    │   │
# │  │  │ :4000 (HTTP) | :4001 (Health) | :6379 (Redis)                   │    │   │
# │  │  │ 172.28.0.10                                                     │    │   │
# │  │  └─────────────────────────────────────────────────────────────────┘    │   │
# │  └─────────────────────────────────────────────────────────────────────────┘   │
# │                             │                                                   │
# │                             ▼                                                   │
# │  ┌─────────────────────────────────────────────────────────────────────────┐   │
# │  │ DATA + OBSERVABILITY PLANE                                               │   │
# │  │  ┌─────────────────────┐  ┌─────────────────────────────────────────┐   │   │
# │  │  │ indrajaal-db-prod   │  │ indrajaal-obs-prod                      │   │   │
# │  │  │ PostgreSQL+TimescaleDB  │ OTEL + Prometheus + Grafana + Loki     │   │   │
# │  │  │ :5433               │  │ + SigNoz + ClickHouse                   │   │   │
# │  │  │ 172.28.0.20         │  │ 172.28.0.30                             │   │   │
# │  │  └─────────────────────┘  └─────────────────────────────────────────┘   │   │
# │  └─────────────────────────────────────────────────────────────────────────┘   │
# │                                                                                 │
# │  ┌─────────────────────────────────────────────────────────────────────────┐   │
# │  │                    MESH NETWORK (172.28.0.0/16)                          │   │
# │  └─────────────────────────────────────────────────────────────────────────┘   │
# └────────────────────────────────────────────────────────────────────────────────┘
#
# =============================================================================
# Resource Summary
# =============================================================================
#
# | Container           | Memory | CPU | IP Address    | Ports              |
# |---------------------|--------|-----|---------------|--------------------|
# | indrajaal-db-prod   | 4GB    | 4   | 172.28.0.20   | 5433               |
# | indrajaal-obs-prod  | 10GB   | 6   | 172.28.0.30   | 4317,9090,3000,... |
# | zenoh-router        | 512MB  | 1   | 172.28.0.40   | 7447,8448,8000     |
# | cepaf-bridge        | 1GB    | 2   | 172.28.0.50   | 9876               |
# | indrajaal-cortex    | 1GB    | 2   | 172.28.0.60   | 9877               |
# | indrajaal-ex-app-1  | 10GB   | 8   | 172.28.0.10   | 4000,4001,6379     |
# | TOTAL               | ~27GB  | 23  |               |                    |
#
# =============================================================================
# Usage Instructions
# =============================================================================
#
# Build Required Images (if not present):
#   podman build -f Dockerfile.cepaf-bridge -t localhost/cepaf-bridge:latest .
#   podman build -f Dockerfile.cortex -t localhost/indrajaal-cortex:latest .
#
# Start Full Mesh:
#   sa-mesh    # (via devenv shell)
#   # OR
#   podman-compose -f lib/cepaf/artifacts/podman-compose-sil6-full-mesh.yml up -d
#
# Check Status:
#   podman-compose -f lib/cepaf/artifacts/podman-compose-sil6-full-mesh.yml ps
#
# View Logs:
#   podman-compose -f lib/cepaf/artifacts/podman-compose-sil6-full-mesh.yml logs -f
#
# Access Points:
#   Phoenix:       http://localhost:4000
#   Health:        http://localhost:4001/health
#   Prajna:        http://localhost:4000/prajna
#   Copilot:       http://localhost:4000/prajna/copilot
#   Grafana:       http://localhost:3000 (admin/indrajaal)
#   Prometheus:    http://localhost:9090
#   Zenoh REST:    http://localhost:8000/@/router/local
#   CEPAF Bridge:  http://localhost:9876/health
#   Cortex:        http://localhost:9877/health
#
# Shutdown:
#   podman-compose -f lib/cepaf/artifacts/podman-compose-sil6-full-mesh.yml down
#
# Cleanup (with volumes):
#   podman-compose -f lib/cepaf/artifacts/podman-compose-sil6-full-mesh.yml down -v
# =============================================================================
"""

    let [<Literal>] SWARM_14_COMPOSE = """
# podman-compose-swarm-14.yml
# Phase 4+7: Full 15-Container Swarm Architecture with Boot Optimization
# =============================================================================
# WHAT: Complete 15-container mesh with HA, Cognitive Plane, and Satellites
# WHY: Production-equivalent environment with full high-availability
# CONSTRAINTS: Requires rootless Podman 5.4.1+, ~40GB RAM
#
# MATHEMATICAL FOUNDATIONS (Phase 3.5):
#   - DAG: 15 nodes, 7 tiers, topological ordering
#   - CPM: Critical path ~120s (db → zenoh → bridge → app-1 → app-2)
#   - RCPSP: Memory 40GB, CPU 32 cores bounded
#   - DFA: 14 states per container lifecycle
#
# PHASE 7 OPTIMIZATIONS (2026-01-18):
#   - SC-OPT-005: Pre-compiled BEAM in image
#   - SC-OPT-006: Wave parallelization (W2+W3)
#   - SC-OPT-007: BEAM volume caching for faster restarts
#   - SC-OPT-008: Boot metrics published to Zenoh
#   - PHICS: Physical Interface Control System (<50ms latency)
#
# STAMP Constraints:
#   SC-SWARM-001 to SC-SWARM-020: Full swarm orchestration
#   SC-SIL6-006: 2oo3 voting for Zenoh quorum
#   SC-SIL6-001 to SC-SIL6-015: SIL-6 Biomorphic Extended Safety
#   SC-PHICS-001 to SC-PHICS-010: Physical Interface Control
#
# Wave Architecture (with parallelization):
#   Wave 1 (Foundation):      indrajaal-db-prod (sequential)
#   Wave 2 (Obs + Zenoh):     indrajaal-obs-prod, zenoh-router-{1,2,3} (PARALLEL)
#   Wave 3 (Cognitive):       cepaf-bridge, indrajaal-cortex (early start after quorum)
#   Wave 4 (Application):     indrajaal-ex-app-1
#   Wave 5 (HA + Satellites): indrajaal-ex-app-{2,3}, indrajaal-chaya, ml-runner-{1,2} (PARALLEL)
# =============================================================================

version: '3.8'

networks:
  indrajaal-swarm-mesh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

  indrajaal-internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.31.0.0/16

# =============================================================================
# WAVE 1: FOUNDATION (DB) - IP: 172.30.0.20
# =============================================================================
services:
  indrajaal-db-prod:
    image: localhost/indrajaal-db-prod:latest
    container_name: indrajaal-db-prod
    hostname: indrajaal-db-prod
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.20
      indrajaal-internal:
    environment:
      POSTGRES_DB: indrajaal_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: "5433"
      TS_TUNE_MEMORY: 4GB
      TS_TUNE_NUM_CPUS: 4
      PHICS_ENABLED: "true"
      NO_TIMEOUT: "true"
      CONTAINER_OS: nixos
      SOPV51_COMPLIANT: "true"
      PGDATA: /var/lib/postgresql/pgdata
    ports:
      - "5433:5433"
    volumes:
      - db_swarm_data:/var/lib/postgresql/pgdata:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d indrajaal_prod -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: database
      environment: swarm-14
      wave: "1"
      priority: "P0"
      sil.level: "6"

# =============================================================================
# WAVE 2: OBSERVABILITY (172.30.0.30) + ZENOH 2oo3 QUORUM (172.30.0.40-42)
# =============================================================================

  indrajaal-obs-prod:
    image: localhost/indrajaal-obs-unified:nixos-devenv
    container_name: indrajaal-obs-prod
    hostname: indrajaal-obs-prod
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.30
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
      OTEL_SERVICE_NAME: indrajaal-obs-prod
      LOG_LEVEL: info
      FRACTAL_LOGGING_ENABLED: "true"
      PROMETHEUS_RETENTION_TIME: 15d
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: indrajaal
      GF_SERVER_HTTP_PORT: "3000"
      UNIFIED_OBS_MODE: "true"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"
      - "3000:3000"
      - "3100:3100"
    volumes:
      - otel_swarm_data:/var/log/otel:z
      - prometheus_swarm_data:/prometheus:z
      - grafana_swarm_data:/var/lib/grafana:z
      - loki_swarm_data:/loki:z
      - ../../../:/workspace:z
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9090/-/healthy && curl -sf http://localhost:3000/api/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 10G
          cpus: '6'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: observability
      environment: swarm-14
      wave: "2"
      priority: "P1"
      sil.level: "6"

  # Zenoh Router 1 (Primary) - 172.30.0.40
  zenoh-router-1:
    image: localhost/zenoh-router:latest
    container_name: zenoh-router-1
    hostname: zenoh-router-1
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.40
    depends_on:
      indrajaal-db-prod:
        condition: service_healthy
    environment:
      RUST_LOG: info
      ZENOH_ROUTER_ID: router-1
    ports:
      - "7447:7447"
      - "8448:8448"
      - "8000:8000"
    volumes:
      - ../../../config/zenoh/zenoh-router-1.json5:/zenoh.json5:ro
    command: ["-c", "/zenoh.json5"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: zenoh-router
      environment: swarm-14
      wave: "2"
      priority: "P0"
      mesh.quorum: "router-1"
      sil.level: "6"

  # Zenoh Router 2 (Secondary) - 172.30.0.41
  zenoh-router-2:
    image: localhost/zenoh-router:latest
    container_name: zenoh-router-2
    hostname: zenoh-router-2
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.41
    depends_on:
      indrajaal-db-prod:
        condition: service_healthy
    environment:
      RUST_LOG: info
      ZENOH_ROUTER_ID: router-2
    ports:
      - "7448:7447"
      - "8449:8448"
      - "8001:8000"
    volumes:
      - ../../../config/zenoh/zenoh-router-2.json5:/zenoh.json5:ro
    command: ["-c", "/zenoh.json5"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: zenoh-router
      environment: swarm-14
      wave: "2"
      priority: "P0"
      mesh.quorum: "router-2"
      sil.level: "6"

  # Zenoh Router 3 (Tertiary) - 172.30.0.42
  zenoh-router-3:
    image: localhost/zenoh-router:latest
    container_name: zenoh-router-3
    hostname: zenoh-router-3
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.42
    depends_on:
      indrajaal-db-prod:
        condition: service_healthy
    environment:
      RUST_LOG: info
      ZENOH_ROUTER_ID: router-3
    ports:
      - "7449:7447"
      - "8450:8448"
      - "8002:8000"
    volumes:
      - ../../../config/zenoh/zenoh-router-3.json5:/zenoh.json5:ro
    command: ["-c", "/zenoh.json5"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: zenoh-router
      environment: swarm-14
      wave: "2"
      priority: "P0"
      mesh.quorum: "router-3"
      sil.level: "6"

# =============================================================================
# WAVE 3: COGNITIVE PLANE (172.30.0.50-60)
# =============================================================================

  cepaf-bridge:
    image: localhost/cepaf-bridge:latest
    container_name: cepaf-bridge
    hostname: cepaf-bridge
    stdin_open: true
    tty: true
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.50
    depends_on:
      zenoh-router-1:
        condition: service_healthy
      zenoh-router-2:
        condition: service_healthy
      zenoh-router-3:
        condition: service_healthy
    environment:
      CEPAF_BRIDGE_PORT: "9876"
      CEPAF_BRIDGE_HOST: "0.0.0.0"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router-1:7447
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: cepaf-bridge
      DOTNET_RUNNING_IN_CONTAINER: "true"
      PODMAN_SOCKET: /run/podman/podman.sock
    volumes:
      - /run/user/1000/podman/podman.sock:/run/podman/podman.sock:z
    ports:
      - "9876:9876"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f dotnet || exit 0"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: cepaf-bridge
      environment: swarm-14
      wave: "3"
      priority: "P1"
      sil.level: "6"

  indrajaal-cortex:
    image: localhost/indrajaal-cortex:latest
    container_name: indrajaal-cortex
    hostname: indrajaal-cortex
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.60
    depends_on:
      cepaf-bridge:
        condition: service_healthy
    environment:
      CORTEX_PORT: "9877"
      CORTEX_HOST: "0.0.0.0"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router-1:7447
      CEPAF_BRIDGE_URL: http://cepaf-bridge:9876
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-cortex
      DOTNET_RUNNING_IN_CONTAINER: "true"
    ports:
      - "9877:9877"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f dotnet || exit 0"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: cortex
      environment: swarm-14
      wave: "3"
      priority: "P1"
      sil.level: "6"

# =============================================================================
# WAVE 4: PRIMARY APPLICATION (172.30.0.10)
# =============================================================================

  indrajaal-ex-app-1:
    image: localhost/indrajaal-app-unified:nixos-devenv
    container_name: indrajaal-ex-app-1
    hostname: indrajaal-ex-app-1
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.10
      indrajaal-internal:
    depends_on:
      indrajaal-db-prod:
        condition: service_healthy
      indrajaal-obs-prod:
        condition: service_healthy
      cepaf-bridge:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      POSTGRES_HOST: indrajaal-db-prod
      POSTGRES_PORT: "5433"
      REDIS_EMBEDDED: "true"
      REDIS_URL: redis://localhost:6379
      PHX_HOST: localhost
      PHX_PORT: "4000"
      SECRET_KEY_BASE: production_equivalent_secret_key_base_64_chars_minimum_here_change_me
      FLAME_ENABLED: "true"
      CLUSTERING_ENABLED: "true"
      RELEASE_NODE: indrajaal@indrajaal-ex-app-1
      RELEASE_COOKIE: indrajaal_swarm_cookie
      PRAJNA_COCKPIT_ENABLED: "true"
      ZENOH_ENABLED: "true"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router-1:7447
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-ex-app-1
      SKIP_ZENOH_NIF: "0"
      SKIP_LINEAGE_NIF: "0"
      # Phase 7: PHICS integration
      PHICS_ENABLED: "true"
      PHICS_LATENCY_BUDGET_MS: "50"
    ports:
      - "4000:4000"
      - "4001:4001"
      - "6379:6379"
    volumes:
      - app1_swarm_data:/app/data:z
      # Phase 7: BEAM cache for faster restarts (SC-OPT-007)
      - beam_cache_app1:/app/_build:z
      - deps_cache_shared:/app/deps:z
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: application
      environment: swarm-14
      wave: "4"
      priority: "P0"
      sil.level: "6"
      phase7.beam_cache: "enabled"
      phase7.phics: "enabled"

# =============================================================================
# WAVE 5: HA REPLICAS + SATELLITES (172.30.0.11-15, 172.30.0.70-71)
# =============================================================================

  indrajaal-ex-app-2:
    image: localhost/indrajaal-app-unified:nixos-devenv
    container_name: indrajaal-ex-app-2
    hostname: indrajaal-ex-app-2
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.11
      indrajaal-internal:
    depends_on:
      indrajaal-ex-app-1:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      POSTGRES_HOST: indrajaal-db-prod
      POSTGRES_PORT: "5433"
      REDIS_EMBEDDED: "true"
      REDIS_URL: redis://localhost:6379
      PHX_HOST: localhost
      PHX_PORT: "4002"
      SECRET_KEY_BASE: production_equivalent_secret_key_base_64_chars_minimum_here_change_me
      CLUSTERING_ENABLED: "true"
      RELEASE_NODE: indrajaal@indrajaal-ex-app-2
      RELEASE_COOKIE: indrajaal_swarm_cookie
      ZENOH_ENABLED: "true"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router-2:7447
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-ex-app-2
      SKIP_ZENOH_NIF: "0"
      # Phase 7: PHICS integration
      PHICS_ENABLED: "true"
      PHICS_LATENCY_BUDGET_MS: "50"
    ports:
      - "4002:4002"
    volumes:
      - app2_swarm_data:/app/data:z
      # Phase 7: BEAM cache for faster restarts (SC-OPT-007)
      - beam_cache_app2:/app/_build:z
      - deps_cache_shared:/app/deps:z
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4002/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: application
      environment: swarm-14
      wave: "5"
      priority: "P1"
      sil.level: "6"
      phase7.beam_cache: "enabled"
      phase7.phics: "enabled"

  indrajaal-ex-app-3:
    image: localhost/indrajaal-app-unified:nixos-devenv
    container_name: indrajaal-ex-app-3
    hostname: indrajaal-ex-app-3
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.12
      indrajaal-internal:
    depends_on:
      indrajaal-ex-app-1:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@indrajaal-db-prod:5433/indrajaal_prod
      POSTGRES_HOST: indrajaal-db-prod
      POSTGRES_PORT: "5433"
      REDIS_EMBEDDED: "true"
      REDIS_URL: redis://localhost:6379
      PHX_HOST: localhost
      PHX_PORT: "4003"
      SECRET_KEY_BASE: production_equivalent_secret_key_base_64_chars_minimum_here_change_me
      CLUSTERING_ENABLED: "true"
      RELEASE_NODE: indrajaal@indrajaal-ex-app-3
      RELEASE_COOKIE: indrajaal_swarm_cookie
      ZENOH_ENABLED: "true"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router-3:7447
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-ex-app-3
      SKIP_ZENOH_NIF: "0"
      # Phase 7: PHICS integration
      PHICS_ENABLED: "true"
      PHICS_LATENCY_BUDGET_MS: "50"
    ports:
      - "4003:4003"
    volumes:
      - app3_swarm_data:/app/data:z
      # Phase 7: BEAM cache for faster restarts (SC-OPT-007)
      - beam_cache_app3:/app/_build:z
      - deps_cache_shared:/app/deps:z
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: application
      environment: swarm-14
      wave: "5"
      priority: "P2"
      sil.level: "6"
      phase7.beam_cache: "enabled"
      phase7.phics: "enabled"

  indrajaal-chaya:
    image: localhost/indrajaal-chaya:latest
    container_name: indrajaal-chaya
    hostname: indrajaal-chaya
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.15
    depends_on:
      indrajaal-ex-app-1:
        condition: service_healthy
    environment:
      CHAYA_PORT: "4010"
      CHAYA_HOST: "0.0.0.0"
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router-1:7447
      PARENT_APP_URL: http://indrajaal-ex-app-1:4000
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: indrajaal-chaya
      XLA_TARGET: cpu
      XLA_BUILD: "true"
    ports:
      - "4010:4010"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4010/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: digital-twin
      environment: swarm-14
      wave: "5"
      priority: "P1"
      sil.level: "6"

  ml-runner-1:
    image: localhost/indrajaal-ml-runner:latest
    container_name: ml-runner-1
    hostname: ml-runner-1
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.70
    depends_on:
      indrajaal-cortex:
        condition: service_healthy
    environment:
      ML_RUNNER_ID: runner-1
      ML_RUNNER_PORT: "9880"
      CORTEX_URL: http://indrajaal-cortex:9877
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router-1:7447
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: ml-runner-1
    ports:
      - "9880:9880"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f python || exit 0"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: ml-runner
      environment: swarm-14
      wave: "5"
      priority: "P2"
      sil.level: "6"

  ml-runner-2:
    image: localhost/indrajaal-ml-runner:latest
    container_name: ml-runner-2
    hostname: ml-runner-2
    networks:
      indrajaal-swarm-mesh:
        ipv4_address: 172.30.0.71
    depends_on:
      indrajaal-cortex:
        condition: service_healthy
    environment:
      ML_RUNNER_ID: runner-2
      ML_RUNNER_PORT: "9881"
      CORTEX_URL: http://indrajaal-cortex:9877
      ZENOH_ROUTER_ENDPOINT: tcp/zenoh-router-1:7447
      OTEL_EXPORTER_OTLP_ENDPOINT: http://indrajaal-obs-prod:4317
      OTEL_SERVICE_NAME: ml-runner-2
    ports:
      - "9881:9881"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f python || exit 0"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
    restart: unless-stopped
    labels:
      project: indrajaal
      component: ml-runner
      environment: swarm-14
      wave: "5"
      priority: "P2"
      sil.level: "6"

# =============================================================================
# VOLUMES
# Phase 7: Added BEAM cache volumes for faster restarts (SC-OPT-007)
# =============================================================================
volumes:
  # Database volumes
  db_swarm_data:

  # Observability volumes
  otel_swarm_data:
  prometheus_swarm_data:
  grafana_swarm_data:
  loki_swarm_data:

  # Application data volumes
  app1_swarm_data:
  app2_swarm_data:
  app3_swarm_data:

  # Phase 7: BEAM cache volumes (SC-OPT-007)
  # Caches compiled BEAM files for faster container restarts
  beam_cache_app1:
    name: beam_cache_app1
    labels:
      project: indrajaal
      purpose: beam-cache
      phase: "7"
  beam_cache_app2:
    name: beam_cache_app2
    labels:
      project: indrajaal
      purpose: beam-cache
      phase: "7"
  beam_cache_app3:
    name: beam_cache_app3
    labels:
      project: indrajaal
      purpose: beam-cache
      phase: "7"

  # Phase 7: Shared deps cache for faster initial builds
  deps_cache_shared:
    name: deps_cache_shared
    labels:
      project: indrajaal
      purpose: deps-cache
      phase: "7"
"""

    let [<Literal>] DOCKERFILE_DB = """
# Dockerfile.db - SIL-2 compliant TimescaleDB image
# Track: infra-f#-cepa
# Purpose: Standalone verification image for the data layer.

FROM docker.io/timescale/timescaledb:latest-pg17

# Agent: Add SOPv5.11 compliance markers
RUN mkdir -p /nix/store /nix/var /workspace && \
    touch /.phics-container && \
    echo "timescaledb-nixos" > /.container-type

# Agent: Set environment for CEPAF# orientation
ENV SOPV5_COMPLIANT=true
ENV CONTAINER_OS=nixos
ENV PHICS_ENABLED=true

# Agent: Default working directory
WORKDIR /workspace

# Default command inherited from base
"""

    let [<Literal>] DOCKERFILE_BASE = """
# SOPv5.1 Base Container
# Framework: SOPv5.1 + PHICS + TPS + STAMP
# Purpose: Universal Base Image with NixOS tools + Tailscale Mesh Capability

# Stage 1: Extract Static Tailscale Binaries
FROM docker.io/tailscale/tailscale:stable as tailscale-source

# Stage 2: Build NixOS Base
FROM ghcr.io/nixos/nix:latest

# Agent: Install core dependencies
RUN nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs && \
    nix-channel --update

# Agent: Install Elixir environment & Tools
RUN nix-env -iA nixpkgs.elixir_1_19 \
                nixpkgs.erlang_28 \
                nixpkgs.rebar3 \
                nixpkgs.gitMinimal \
                nixpkgs.bash \
                nixpkgs.coreutils \
                nixpkgs.gnumake \
                nixpkgs.gcc \
                nixpkgs.postgresql_17 \
                nixpkgs.redis \
                nixpkgs.podman \
                nixpkgs.cacert \
                nixpkgs.iptables \
                nixpkgs.iproute2 nixpkgs.hostname nixpkgs.curl nixpkgs.which nixpkgs.jq

# Agent: Inject Tailscale Binaries (Universal Mesh Capability)
# We copy from the official image to ensure we get the static Go binaries
COPY --from=tailscale-source /usr/local/bin/tailscaled /usr/local/bin/tailscaled
COPY --from=tailscale-source /usr/local/bin/tailscale /usr/local/bin/tailscale
RUN mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale

# Agent: Create PHICS markers
RUN touch /.phics-container && \
    mkdir -p /workspace && \
    echo "sopv51-base" > /.container-type

# Agent: Set environment
ENV CONTAINER_ENFORCEMENT=false
ENV PHICS_ENABLED=true
ENV NO_TIMEOUT=true
ENV ELIXIR_ERL_OPTIONS="+S 16"
ENV SOP_V51_MODE=enabled
ENV TPS_METHODOLOGY=active
ENV STAMP_INTEGRATION=enabled

# Agent: Set working directory
WORKDIR /workspace

# Agent: Default command
CMD ["sleep", "infinity"]
"""

    let [<Literal>] DOCKERFILE_OBS = """
# SOPv5.1 Observability Monolith (Dev/Test)
# Combines Prometheus, Grafana, ClickHouse, OTEL into one container for simplified dev/demo usage.

FROM localhost/sopv51-base:latest

# Install Observability Stack and utilities
RUN nix-channel --update && \
    nix-env -iA nixpkgs.prometheus \
                nixpkgs.grafana \
                nixpkgs.clickhouse \
                nixpkgs.opentelemetry-collector \
                nixpkgs.curl \
                nixpkgs.netcat \
                nixpkgs.dotnet-sdk_10

# Setup Directories
RUN mkdir -p /var/lib/grafana \
             /var/lib/clickhouse \
             /var/lib/prometheus \
             /app/config/prometheus \
             /app/config/grafana \
             /app/config/otel-collector \
             /var/log/clickhouse-server \
             /var/log/grafana && \
    chmod -R 777 /var/log /var/lib/grafana /var/lib/clickhouse /var/lib/prometheus /app/config

# Copy Configs
COPY monitoring/prometheus.yml /app/config/prometheus/prometheus.yml
COPY monitoring/grafana/grafana.ini /app/config/grafana/grafana.ini
COPY containers/signoz/config/clickhouse/clickhouse-config.xml /app/config/clickhouse/clickhouse-config.xml
COPY containers/signoz/config/clickhouse/clickhouse-users.xml /app/config/clickhouse/clickhouse-users.xml
COPY containers/signoz/config/otel-collector/otel-collector-standalone.yaml /app/config/otel-collector/config.yaml

# Build and Publish F# ObsSupervisor (Genetic Self-Containment)
COPY lib/cepaf/src/Cepaf.ObsSupervisor /app/src/Cepaf.ObsSupervisor
WORKDIR /app/src/Cepaf.ObsSupervisor
RUN dotnet publish -c Release --self-contained -r linux-x64 -o /app/bin

# Fix Shebangs & Symlinks
RUN ln -sf $(which bash) /bin/bash && \
    ln -sf $(which sh) /bin/sh && \
    ln -sf $(which curl) /bin/curl

WORKDIR /app
# Use Published F# ObsSupervisor as the entrypoint (self-contained, no runtime dependency)
CMD ["sh", "-c", "export HOME=/tmp && export DOTNET_CLI_HOME=/tmp && /app/bin/Cepaf.ObsSupervisor"]
"""

    let [<Literal>] DOCKERFILE_APP = """
# SOPv5.1 Elixir Application (SIL-6 Biomorphic)
FROM localhost/sopv51-base:latest

LABEL sopv51.version="5.1.0"
LABEL sopv51.phics.enabled="true"

WORKDIR /workspace

# Genetic Re-Synthesis Environment
# XLA_BUILD=false downloads prebuilt binaries (bazel not available in container)
# SKIP_ZENOH_NIF=1 — Zenoh accessed via mesh network, not in-process NIF
ENV XLA_TARGET=cpu
ENV XLA_BUILD=false
ENV SKIP_ZENOH_NIF=1
ENV SKIP_LINEAGE_NIF=1
ENV MIX_ENV=prod
ENV SECRET_KEY_BASE=container-build-placeholder-key-will-be-overridden-at-runtime-0123456789abcdef

# TARGETED GENETIC INJECTION: Only essential source DNA
COPY mix.exs mix.lock ./
COPY config ./config
COPY lib ./lib
COPY priv ./priv
COPY scripts/containers/entrypoint.sh /usr/local/bin/entrypoint.sh

# Install toolchain inside container (musl-libc alignment)
# gnumake + gcc needed for NIF compilation (bcrypt, jason_native, etc.)
RUN nix-channel --update && \
    nix-env -iA nixpkgs.elixir_1_19 \
                nixpkgs.erlang_28 \
                nixpkgs.tini \
                nixpkgs.gnumake \
                nixpkgs.gcc \
                nixpkgs.cmake

RUN chmod +x /usr/local/bin/entrypoint.sh

# Force NIF compilation inside the container toolchain
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get && \
    mix compile

ENTRYPOINT ["tini", "--", "/usr/local/bin/entrypoint.sh"]
CMD ["phx.server"]
"""

    let [<Literal>] DOCKERFILE_BRIDGE = """
# Dockerfile.cepaf-bridge - F# CEPAF Bridge Service
# Version: 1.0.0
# Context: SIL-6 Biomorphic Fractal Mesh - Cognitive Plane
# STAMP: SC-SIL6-001, SC-SYNC-001, SC-MESH-001

# Build stage - compile F# project
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy the entire lib structure to preserve relative paths for project references
COPY lib/ /src/lib/

# Restore and publish the CEPAF Bridge
WORKDIR /src/lib/cepaf/src/Cepaf.Bridge
RUN dotnet restore Cepaf.Bridge.fsproj
RUN dotnet publish Cepaf.Bridge.fsproj -c Release -o /app/publish

# Runtime stage - minimal image
FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app

# Install curl for health checks
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

# Copy published application
COPY --from=build /app/publish .

# Expose JSON-RPC port for Elixir-F# bridge communication
EXPOSE 9876

# Health check
HEALTHCHECK --interval=15s --timeout=5s --start-period=30s --retries=3 \
    CMD curl -f http://localhost:9876/health || exit 1

# Environment variables
ENV CEPAF_BRIDGE_PORT=9876
ENV CEPAF_BRIDGE_HOST=0.0.0.0
ENV DOTNET_RUNNING_IN_CONTAINER=true

# SIL-6 Labels
LABEL project="indrajaal" \
      component="cepaf-bridge" \
      version="1.0.0" \
      sil.level="6" \
      stamp.constraint="SC-SYNC-001" \
      mesh.role="cognitive-plane"

ENTRYPOINT ["dotnet", "cepaf-bridge.dll"]
"""

    let [<Literal>] DOCKERFILE_CORTEX = """
# Dockerfile.cortex - F# Cognitive Plane
# Version: 1.0.0
# Context: Phase 4 Bicameral Mind

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
# Copy the entire lib structure to preserve relative paths for project references
COPY lib/ /src/lib/
WORKDIR /src/lib/cortex/src/Indrajaal.Cortex
RUN dotnet restore Indrajaal.Cortex.fsproj
RUN dotnet publish Indrajaal.Cortex.fsproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Indrajaal.Cortex.dll"]
"""

    let [<Literal>] DOCKERFILE_MOJO = """
# Dockerfile.mojo - Mojo MAX Compute Substrate (SIL-6 Biomorphic)
# Version: 1.0.0
# Stub: Provides health endpoint on :11436 until real MAX SDK available
FROM docker.io/library/alpine:3.21

RUN apk add --no-cache curl socat

WORKDIR /app

# Health endpoint stub — responds 200 on /health
RUN printf '#!/bin/sh\nwhile true; do\n  echo -e "HTTP/1.1 200 OK\\r\\nContent-Type: application/json\\r\\nConnection: close\\r\\n\\r\\n{\\"status\\":\\"healthy\\",\\"service\\":\\"mojo-max-stub\\",\\"version\\":\\"1.0.0-stub\\"}" | socat - TCP-LISTEN:11436,reuseaddr,fork &\n  wait\ndone\n' > /app/serve.sh && chmod +x /app/serve.sh

EXPOSE 11436

HEALTHCHECK --interval=10s --timeout=5s --retries=3 \
    CMD curl -sf http://localhost:11436/health || exit 1

ENTRYPOINT ["/bin/sh", "/app/serve.sh"]
"""
