defmodule Indrajaal.Devices.Device do
  @moduledoc """
  Ash resource for device management.

  Implements multi - tenant data model with audit fields.
  Generated by worker - 2.
  """

  use Indrajaal.BaseResource,
    domain: Indrajaal.Devices

  use Indrajaal.Multitenancy.TenantResource

  postgres do
    table "devices"
    repo Indrajaal.Repo
  end

  attributes do
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
      public? true
    end

    attribute :description, :string do
      public? true
    end

    attribute :active, :boolean do
      default true
      public? true
    end

    attribute :metadata, :map do
      default %{}
      public? true
    end

    # Domain-specific fields
    attribute :device_type_id, :uuid do
      allow_nil? true
      public? true
    end

    attribute :serial_number, :string do
      public? true
    end

    attribute :firmware_version, :string do
      public? true
    end

    attribute :ip_address, :string do
      public? true
    end

    attribute :mac_address, :string do
      public? true
    end

    attribute :status, :string do
      default "offline"
      public? true
    end

    attribute :last_seen_at, :utc_datetime do
      public? true
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :tenant, Indrajaal.Core.Tenant do
      allow_nil? false
    end

    belongs_to :device_type, Indrajaal.Devices.DeviceType do
      source_attribute :device_type_id
      destination_attribute :id
      allow_nil? true
      public? true
    end

    belongs_to :site, Indrajaal.Sites.Site do
      allow_nil? true
      public? true
    end
  end

  actions do
    defaults [:read, :update, :destroy]

    create :create do
      primary? true

      accept [
        :name,
        :description,
        :active,
        :metadata,
        :device_type_id,
        :serial_number,
        :firmware_version,
        :ip_address,
        :mac_address,
        :status,
        :last_seen_at,
        :tenant_id,
        :site_id
      ]
    end

    read :by_id do
      argument :id, :uuid, allow_nil?: false

      filter expr(id == ^arg(:id))
    end

    read :updated_since do
      argument :since, :utc_datetime, allow_nil?: false

      filter expr(updated_at >= ^arg(:since))
    end
  end

  code_interface do
    define :create
    define :read
    define :update
    define :destroy
    define :by_id, args: [:id]
    define :updated_since, args: [:since]
  end

  validations do
    validate present(:name), message: "Name is _required"
    validate string_length(:name, min: 1, max: 255)
    validate string_length(:description, max: 1000)
  end

  # Traditional Ecto changeset for compatibility with existing context code
  @spec changeset(Ecto.Schema.t(), map()) :: Ecto.Changeset.t()
  def changeset(device, attrs) do
    device
    |> Ecto.Changeset.cast(attrs, [
      :name,
      :description,
      :active,
      :metadata,
      :device_type_id,
      :serial_number,
      :firmware_version,
      :ip_address,
      :status,
      :last_seen_at
    ])
    |> Ecto.Changeset.validate_required([:name])
    |> Ecto.Changeset.validate_length(:name, min: 1, max: 255)
    |> Ecto.Changeset.validate_length(:description, max: 1000)
  end
end

# Agent: Worker - 2 (Devices Domain Agent)
# SOPv5.1 Compliance: ✅ Device management and hardware integration coordination
# Domain: Devices
# Responsibilities: Device management, hardware integration, IoT coordination
# Multi - Agent Architecture: Integrated with 11 - agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
