{application,timescale,
             [{modules,['Elixir.Timescale','Elixir.Timescale.Hyperfunctions',
                        'Elixir.Timescale.Hyperfunctions.Toolkit',
                        'Elixir.Timescale.Migration',
                        'Elixir.Timescale.MigrationArgError',
                        'Elixir.Timescale.MigrationUtils',
                        'Elixir.Timescale.OptionalArgError',
                        'Elixir.Timescale.QueryUtils']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,ecto_sql]},
              {description,"Easy time-series data in TimescaleDB with Ecto"},
              {registered,[]},
              {vsn,"0.1.1"}]}.
