defmodule Indrajaal.Repo.Migrations.CreateSitesDomain do
  @moduledoc "
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  "

  use Ecto.Migration

  @spec up() :: any()
  def up do
    create table(:zones, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "zones_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :code, :text, null: false
      add :description, :text
      add :zone_type, :text, null: false, default: "public"
      add :security_level, :text, null: false, default: "medium"
      add :access_control_type, :text, default: "open"
      add :monitoring_level, :text, default: "motion"
      add :allowed_roles, {:array, :text}, default: []
      add :time_restrictions, :map, default: %{}
      add :compliance_requirements, {:array, :text}, default: []
      add :alarm_priority, :text, default: "medium"
      add :auto_lockdown?, :boolean, default: false
      add :visitor_allowed?, :boolean, default: true
      add :recording_enabled?, :boolean, default: true
      add :retention_days, :bigint, default: 30
      add :active?, :boolean, default: true
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id, :uuid, null: false
      add :building_id, :uuid
      add :floor_id, :uuid
      add :parent_zone_id, :uuid
    end

    create index(:zones, [:active?], name: "zones_active_index", where: ~s/"active?" = true/)

    create index(:zones, [:parent_zone_id], where: "parent_zone_id IS NOT NULL")

    create index(:zones, [:floor_id], where: "floor_id IS NOT NULL")

    create index(:zones, [:building_id], where: "building_id IS NOT NULL")

    create index(:zones, [:site_id, :security_level])

    create index(:zones, [:site_id, :zone_type])

    create index(:zones, [:site_id, :code], unique: true)

    create table(:sites, primary_key: false) do
      add :tenant_id, :uuid, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:zones) do
      modify :site_id,
             references(:sites,
               column: :id,
               name: "zones_site_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sites) do
      add :name, :text, null: false
      add :code, :text, null: false
      add :description, :text
      add :address, :map, default: %{}
      add :coordinates, :map, default: %{}
      add :timezone, :text, default: "UTC"
      add :business_hours, :map
      add :contact_info, :map, default: %{}
      add :emergency_contacts, {:array, :map}, default: []
      add :site_type, :text, default: "office"
      add :status, :text, default: "active"
      add :security_level, :text, default: "medium"
      add :max_occupancy, :bigint
      add :current_occupancy, :bigint, default: 0
      add :features, {:array, :text}, default: []
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "sites_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:sites, [:security_level])

    create index(:sites, [:site_type])

    create index(:sites, [:status], where: "status = 'active'")

    create index(:sites, [:tenant_id, :organization_id])

    create index(:sites, [:tenant_id, :code], unique: true)

    alter table(:sites) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "sites_tenant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:sites, [:tenant_id, :code], name: "sites_unique_code_per_tenant_index")

    create table(:locations, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "locations_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :location_type, :text, null: false
      add :name, :text, null: false
      add :full_path, :text
      add :coordinates, :map
      add :reference_id, :uuid
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id,
          references(:sites,
            column: :id,
            name: "locations_site_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :building_id, :uuid
      add :floor_id, :uuid
      add :zone_id, :uuid
      add :area_id, :uuid
    end

    create index(:locations, [:area_id], where: "area_id IS NOT NULL")

    create index(:locations, [:zone_id], where: "zone_id IS NOT NULL")

    create index(:locations, [:floor_id], where: "floor_id IS NOT NULL")

    create index(:locations, [:building_id], where: "building_id IS NOT NULL")

    create index(:locations, [:site_id], where: "site_id IS NOT NULL")

    create index(:locations, [:reference_id])

    create index(:locations, [:tenant_id, :location_type])

    create table(:floors, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "floors_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :level, :bigint, null: false
      add :description, :text
      add :floor_type, :text, default: "office"
      add :area_sqm, :float
      add :ceiling_height_m, :float
      add :max_occupancy, :bigint
      add :current_occupancy, :bigint, default: 0
      add :access_restricted?, :boolean, default: false
      add :emergency_equipment, {:array, :map}, default: []
      add :evacuation_routes, {:array, :map}, default: []
      add :floor_plan_url, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :building_id, :uuid, null: false
      add :site_id, :uuid, null: false
    end

    create index(:floors, [:access_restricted?],
             name: "floors_access_restricted_index",
             where: ~s/"access_restricted?" = true/
           )

    create index(:floors, [:floor_type])

    create index(:floors, [:site_id])

    create index(:floors, [:building_id, :level], unique: true)

    create table(:buildings, primary_key: false) do
      add :tenant_id, :uuid, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:zones) do
      modify :building_id,
             references(:buildings,
               column: :id,
               name: "zones_building_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :floor_id,
             references(:floors,
               column: :id,
               name: "zones_floor_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :parent_zone_id,
             references(:zones,
               column: :id,
               name: "zones_parent_zone_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:zones, [:site_id, :code], name: "zones_unique_code_per_site_index")

    alter table(:locations) do
      modify :building_id,
             references(:buildings,
               column: :id,
               name: "locations_building_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :floor_id,
             references(:floors,
               column: :id,
               name: "locations_floor_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :zone_id,
             references(:zones,
               column: :id,
               name: "locations_zone_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:floors) do
      modify :building_id,
             references(:buildings,
               column: :id,
               name: "floors_building_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :site_id,
             references(:sites,
               column: :id,
               name: "floors_site_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:floors, [:building_id, :level],
             name: "floors_unique_level_per_building_index"
           )

    alter table(:buildings) do
      add :name, :text, null: false
      add :code, :text, null: false
      add :description, :text
      add :building_type, :text, default: "main"
      add :floor_count, :bigint, default: 1
      add :underground_levels, :bigint, default: 0
      add :total_area_sqm, :float
      add :year_built, :bigint
      add :last_renovation, :bigint
      add :access_points, {:array, :map}, default: []
      add :emergency_exits, {:array, :map}, default: []
      add :amenities, {:array, :text}, default: []
      add :status, :text, default: "active"
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id,
          references(:sites,
            column: :id,
            name: "buildings_site_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:buildings, [:building_type])

    create index(:buildings, [:site_id, :status])

    create index(:buildings, [:site_id, :code], unique: true)

    alter table(:buildings) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "buildings_tenant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:buildings, [:site_id, :code],
             name: "buildings_unique_code_per_site_index"
           )

    create table(:areas, primary_key: false) do
      add :tenant_id, :uuid, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:locations) do
      modify :area_id,
             references(:areas,
               column: :id,
               name: "locations_area_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:areas) do
      add :name, :text, null: false
      add :code, :text, null: false
      add :description, :text
      add :area_type, :text, default: "office"
      add :area_sqm, :float
      add :max_occupancy, :bigint
      add :current_occupancy, :bigint, default: 0
      add :access_level, :text, default: "employees"
      add :climate_controlled?, :boolean, default: true
      add :has_windows?, :boolean, default: false
      add :emergency_exit?, :boolean, default: false
      add :assets, {:array, :map}, default: []
      add :environmental_data, :map, default: %{}
      add :booking_enabled?, :boolean, default: false
      add :booking_rules, :map, default: %{}
      add :status, :text, default: "available"
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id,
          references(:sites,
            column: :id,
            name: "areas_site_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :building_id,
          references(:buildings,
            column: :id,
            name: "areas_building_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :floor_id,
          references(:floors,
            column: :id,
            name: "areas_floor_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :zone_id,
          references(:zones,
            column: :id,
            name: "areas_zone_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:areas, [:status], where: "status = 'available'")

    create index(:areas, [:booking_enabled?],
             name: "areas_booking_enabled_index",
             where: ~s/"booking_enabled?" = true/
           )

    create index(:areas, [:area_type])

    create index(:areas, [:floor_id], where: "floor_id IS NOT NULL")

    create index(:areas, [:site_id, :status])

    create index(:areas, [:zone_id, :code], unique: true)

    alter table(:areas) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "areas_tenant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:areas, [:zone_id, :code], name: "areas_unique_code_per_zone_index")
  end

  @spec down() :: any()
  def down do
    drop_if_exists unique_index(:areas, [:zone_id, :code],
                     name: "areas_unique_code_per_zone_index"
                   )

    drop constraint(:areas, "areas_tenant_id_fkey")

    drop constraint(:areas, "areas_site_id_fkey")

    drop constraint(:areas, "areas_building_id_fkey")

    drop constraint(:areas, "areas_floor_id_fkey")

    drop constraint(:areas, "areas_zone_id_fkey")

    alter table(:areas) do
      modify :tenant_id, :uuid
    end

    drop_if_exists index(:areas, [:zone_id, :code])

    drop_if_exists index(:areas, [:site_id, :status])

    drop_if_exists index(:areas, [:floor_id])

    drop_if_exists index(:areas, [:area_type])

    drop_if_exists index(:areas, [:booking_enabled?], name: "areas_booking_enabled_index")

    drop_if_exists index(:areas, [:status])

    alter table(:areas) do
      remove :zone_id
      remove :floor_id
      remove :building_id
      remove :site_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :status
      remove :booking_rules
      remove :booking_enabled?
      remove :environmental_data
      remove :assets
      remove :emergency_exit?
      remove :has_windows?
      remove :climate_controlled?
      remove :access_level
      remove :current_occupancy
      remove :max_occupancy
      remove :area_sqm
      remove :area_type
      remove :description
      remove :code
      remove :name
    end

    drop constraint(:locations, "locations_area_id_fkey")

    alter table(:locations) do
      modify :area_id, :uuid
    end

    drop table(:areas)

    drop_if_exists unique_index(:buildings, [:site_id, :code],
                     name: "buildings_unique_code_per_site_index"
                   )

    drop constraint(:buildings, "buildings_tenant_id_fkey")

    drop constraint(:buildings, "buildings_site_id_fkey")

    alter table(:buildings) do
      modify :tenant_id, :uuid
    end

    drop_if_exists index(:buildings, [:site_id, :code])

    drop_if_exists index(:buildings, [:site_id, :status])

    drop_if_exists index(:buildings, [:building_type])

    alter table(:buildings) do
      remove :site_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :status
      remove :amenities
      remove :emergency_exits
      remove :access_points
      remove :last_renovation
      remove :year_built
      remove :total_area_sqm
      remove :underground_levels
      remove :floor_count
      remove :building_type
      remove :description
      remove :code
      remove :name
    end

    drop_if_exists unique_index(:floors, [:building_id, :level],
                     name: "floors_unique_level_per_building_index"
                   )

    drop constraint(:floors, "floors_building_id_fkey")

    drop constraint(:floors, "floors_site_id_fkey")

    alter table(:floors) do
      modify :site_id, :uuid
      modify :building_id, :uuid
    end

    drop constraint(:locations, "locations_building_id_fkey")

    drop constraint(:locations, "locations_floor_id_fkey")

    drop constraint(:locations, "locations_zone_id_fkey")

    alter table(:locations) do
      modify :zone_id, :uuid
      modify :floor_id, :uuid
      modify :building_id, :uuid
    end

    drop_if_exists unique_index(:zones, [:site_id, :code],
                     name: "zones_unique_code_per_site_index"
                   )

    drop constraint(:zones, "zones_building_id_fkey")

    drop constraint(:zones, "zones_floor_id_fkey")

    drop constraint(:zones, "zones_parent_zone_id_fkey")

    alter table(:zones) do
      modify :parent_zone_id, :uuid
      modify :floor_id, :uuid
      modify :building_id, :uuid
    end

    drop table(:buildings)

    drop constraint(:floors, "floors_tenant_id_fkey")

    drop_if_exists index(:floors, [:building_id, :level])

    drop_if_exists index(:floors, [:site_id])

    drop_if_exists index(:floors, [:floor_type])

    drop_if_exists index(:floors, [:access_restricted?], name: "floors_access_restricted_index")

    drop table(:floors)

    drop constraint(:locations, "locations_tenant_id_fkey")

    drop constraint(:locations, "locations_site_id_fkey")

    drop_if_exists index(:locations, [:tenant_id, :location_type])

    drop_if_exists index(:locations, [:reference_id])

    drop_if_exists index(:locations, [:site_id])

    drop_if_exists index(:locations, [:building_id])

    drop_if_exists index(:locations, [:floor_id])

    drop_if_exists index(:locations, [:zone_id])

    drop_if_exists index(:locations, [:area_id])

    drop table(:locations)

    drop_if_exists unique_index(:sites, [:tenant_id, :code],
                     name: "sites_unique_code_per_tenant_index"
                   )

    drop constraint(:sites, "sites_tenant_id_fkey")

    drop constraint(:sites, "sites_organization_id_fkey")

    alter table(:sites) do
      modify :tenant_id, :uuid
    end

    drop_if_exists index(:sites, [:tenant_id, :code])

    drop_if_exists index(:sites, [:tenant_id, :organization_id])

    drop_if_exists index(:sites, [:status])

    drop_if_exists index(:sites, [:site_type])

    drop_if_exists index(:sites, [:security_level])

    alter table(:sites) do
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :features
      remove :current_occupancy
      remove :max_occupancy
      remove :security_level
      remove :status
      remove :site_type
      remove :emergency_contacts
      remove :contact_info
      remove :business_hours
      remove :timezone
      remove :coordinates
      remove :address
      remove :description
      remove :code
      remove :name
    end

    drop constraint(:zones, "zones_site_id_fkey")

    alter table(:zones) do
      modify :site_id, :uuid
    end

    drop table(:sites)

    drop constraint(:zones, "zones_tenant_id_fkey")

    drop_if_exists index(:zones, [:site_id, :code])

    drop_if_exists index(:zones, [:site_id, :zone_type])

    drop_if_exists index(:zones, [:site_id, :security_level])

    drop_if_exists index(:zones, [:building_id])

    drop_if_exists index(:zones, [:floor_id])

    drop_if_exists index(:zones, [:parent_zone_id])

    drop_if_exists index(:zones, [:active?], name: "zones_active_index")

    drop table(:zones)
  end
end
