defmodule Indrajaal.Repo.Migrations.CreatePolicyDomain do
  @moduledoc "
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  "

  use Ecto.Migration

  @spec up() :: any()
  def up do
    create table(:user_roles, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "user_roles_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :assigned_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")

      add :assigned_by_id,
          references(:users,
            column: :id,
            name: "user_roles_assigned_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :expires_at, :utc_datetime_usec
      add :scope_type, :text, default: "global"
      add :scope_id, :uuid
      add :conditions, :map, default: %{}
      add :reason, :text
      add :approved?, :boolean, default: true
      add :approved_at, :utc_datetime_usec

      add :approved_by_id,
          references(:users,
            column: :id,
            name: "user_roles_approved_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :role_id, :uuid, null: false
    end

    create index(:user_roles, [:scope_type, :scope_id], where: "scope_type != 'global'")

    create index(:user_roles, [:assigned_by_id])

    create index(:user_roles, [:expires_at], where: "expires_at IS NOT NULL")

    create index(:user_roles, [:role_id])

    create index(:user_roles, [:user_id, :approved?],
             name: "user_roles_user_approved_index",
             where: ~s/"approved?" = true/
           )

    create index(:user_roles, [:tenant_id, :user_id, :role_id, :scope_type, :scope_id],
             name: "user_roles_unique_assignment_index",
             unique: true
           )

    create table(:roles, primary_key: false) do
      add :tenant_id, :uuid, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_roles) do
      modify :role_id,
             references(:roles,
               column: :id,
               name: "user_roles_role_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:user_roles, [:tenant_id, :user_id, :role_id, :scope_type, :scope_id],
             name: "user_roles_unique_user_role_scope_index"
           )

    alter table(:roles) do
      add :name, :text, null: false
      add :code, :text, null: false
      add :description, :text
      add :system_role?, :boolean, default: false
      add :assignable?, :boolean, default: true
      add :level, :bigint, default: 0
      add :metadata, :map, default: %{}
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_role_id,
          references(:roles,
            column: :id,
            name: "roles_parent_role_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:roles, [:level])

    create index(:roles, [:archived_at], where: "archived_at IS NOT NULL")

    create index(:roles, [:parent_role_id], where: "parent_role_id IS NOT NULL")

    create index(:roles, [:tenant_id, :system_role?], name: "roles_tenant_system_index")

    create index(:roles, [:tenant_id, :code], unique: true)

    alter table(:roles) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "roles_tenant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:roles, [:tenant_id, :code], name: "roles_unique_code_per_tenant_index")

    create table(:role_permissions, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "role_permissions_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :granted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")

      add :granted_by_id,
          references(:users,
            column: :id,
            name: "role_permissions_granted_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :expires_at, :utc_datetime_usec
      add :conditions, :map, default: %{}
      add :reason, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :role_id,
          references(:roles,
            column: :id,
            name: "role_permissions_role_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :permission_id, :uuid, null: false
    end

    create index(:role_permissions, [:granted_by_id])

    create index(:role_permissions, [:expires_at], where: "expires_at IS NOT NULL")

    create index(:role_permissions, [:permission_id])

    create index(:role_permissions, [:role_id])

    create index(:role_permissions, [:tenant_id, :role_id, :permission_id], unique: true)

    create table(:permissions, primary_key: false) do
      add :tenant_id, :uuid, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:role_permissions) do
      modify :permission_id,
             references(:permissions,
               column: :id,
               name: "role_permissions_permission_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:role_permissions, [:tenant_id, :role_id, :permission_id],
             name: "role_permissions_unique_role_permission_index"
           )

    alter table(:permissions) do
      add :name, :text, null: false
      add :code, :text, null: false
      add :resource, :text, null: false
      add :action, :text, null: false
      add :description, :text
      add :category, :text, default: "crud"
      add :scope, :text, default: "tenant"
      add :conditions, :map, default: %{}
      add :risk_level, :text, default: "low"
      add :requires_mfa?, :boolean, default: false
      add :active?, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:permissions, [:active?],
             name: "permissions_active_index",
             where: ~s/"active?" = true/
           )

    create index(:permissions, [:risk_level])

    create index(:permissions, [:category])

    create index(:permissions, [:tenant_id, :resource, :action])

    create index(:permissions, [:tenant_id, :code], unique: true)

    alter table(:permissions) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "permissions_tenant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:permissions, [:tenant_id, :code],
             name: "permissions_unique_code_per_tenant_index"
           )

    create table(:access_rules, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "access_rules_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :code, :text, null: false
      add :description, :text
      add :rule_type, :text, default: "conditional"
      add :resource_type, :text, null: false
      add :action, :text
      add :conditions, :map, null: false, default: %{}
      add :effect, :text, default: "allow"
      add :priority, :bigint, default: 100
      add :scope, :text, default: "tenant"
      add :active?, :boolean, default: true
      add :effective_from, :utc_datetime_usec
      add :effective_until, :utc_datetime_usec
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :role_id,
          references(:roles,
            column: :id,
            name: "access_rules_role_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :permission_id,
          references(:permissions,
            column: :id,
            name: "access_rules_permission_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:access_rules, [:effective_from, :effective_until])

    create index(:access_rules, [:active?, :priority],
             name: "access_rules_active_priority_index",
             where: ~s/"active?" = true/
           )

    create index(:access_rules, [:permission_id], where: "permission_id IS NOT NULL")

    create index(:access_rules, [:role_id], where: "role_id IS NOT NULL")

    create index(:access_rules, [:tenant_id, :resource_type, :action, :priority])

    create index(:access_rules, [:tenant_id, :code], unique: true)

    create unique_index(:access_rules, [:tenant_id, :code],
             name: "access_rules_unique_code_per_tenant_index"
           )
  end

  @spec down() :: any()
  def down do
    drop_if_exists unique_index(:access_rules, [:tenant_id, :code],
                     name: "access_rules_unique_code_per_tenant_index"
                   )

    drop constraint(:access_rules, "access_rules_tenant_id_fkey")

    drop constraint(:access_rules, "access_rules_role_id_fkey")

    drop constraint(:access_rules, "access_rules_permission_id_fkey")

    drop_if_exists index(:access_rules, [:tenant_id, :code])

    drop_if_exists index(:access_rules, [:tenant_id, :resource_type, :action, :priority])

    drop_if_exists index(:access_rules, [:role_id])

    drop_if_exists index(:access_rules, [:permission_id])

    drop_if_exists index(:access_rules, [:active?, :priority],
                     name: "access_rules_active_priority_index"
                   )

    drop_if_exists index(:access_rules, [:effective_from, :effective_until])

    drop table(:access_rules)

    drop_if_exists unique_index(:permissions, [:tenant_id, :code],
                     name: "permissions_unique_code_per_tenant_index"
                   )

    drop constraint(:permissions, "permissions_tenant_id_fkey")

    alter table(:permissions) do
      modify :tenant_id, :uuid
    end

    drop_if_exists index(:permissions, [:tenant_id, :code])

    drop_if_exists index(:permissions, [:tenant_id, :resource, :action])

    drop_if_exists index(:permissions, [:category])

    drop_if_exists index(:permissions, [:risk_level])

    drop_if_exists index(:permissions, [:active?], name: "permissions_active_index")

    alter table(:permissions) do
      remove :updated_at
      remove :inserted_at
      remove :active?
      remove :requires_mfa?
      remove :risk_level
      remove :conditions
      remove :scope
      remove :category
      remove :description
      remove :action
      remove :resource
      remove :code
      remove :name
    end

    drop_if_exists unique_index(:role_permissions, [:tenant_id, :role_id, :permission_id],
                     name: "role_permissions_unique_role_permission_index"
                   )

    drop constraint(:role_permissions, "role_permissions_permission_id_fkey")

    alter table(:role_permissions) do
      modify :permission_id, :uuid
    end

    drop table(:permissions)

    drop constraint(:role_permissions, "role_permissions_tenant_id_fkey")

    drop constraint(:role_permissions, "role_permissions_granted_by_id_fkey")

    drop constraint(:role_permissions, "role_permissions_role_id_fkey")

    drop_if_exists index(:role_permissions, [:tenant_id, :role_id, :permission_id])

    drop_if_exists index(:role_permissions, [:role_id])

    drop_if_exists index(:role_permissions, [:permission_id])

    drop_if_exists index(:role_permissions, [:expires_at])

    drop_if_exists index(:role_permissions, [:granted_by_id])

    drop table(:role_permissions)

    drop_if_exists unique_index(:roles, [:tenant_id, :code],
                     name: "roles_unique_code_per_tenant_index"
                   )

    drop constraint(:roles, "roles_tenant_id_fkey")

    drop constraint(:roles, "roles_parent_role_id_fkey")

    alter table(:roles) do
      modify :tenant_id, :uuid
    end

    drop_if_exists index(:roles, [:tenant_id, :code])

    drop_if_exists index(:roles, [:tenant_id, :system_role?], name: "roles_tenant_system_index")

    drop_if_exists index(:roles, [:parent_role_id])

    drop_if_exists index(:roles, [:archived_at])

    drop_if_exists index(:roles, [:level])

    alter table(:roles) do
      remove :parent_role_id
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :metadata
      remove :level
      remove :assignable?
      remove :system_role?
      remove :description
      remove :code
      remove :name
    end

    drop_if_exists unique_index(
                     :user_roles,
                     [:tenant_id, :user_id, :role_id, :scope_type, :scope_id],
                     name: "user_roles_unique_user_role_scope_index"
                   )

    drop constraint(:user_roles, "user_roles_role_id_fkey")

    alter table(:user_roles) do
      modify :role_id, :uuid
    end

    drop table(:roles)

    drop constraint(:user_roles, "user_roles_tenant_id_fkey")

    drop constraint(:user_roles, "user_roles_assigned_by_id_fkey")

    drop constraint(:user_roles, "user_roles_approved_by_id_fkey")

    drop constraint(:user_roles, "user_roles_user_id_fkey")

    drop_if_exists index(:user_roles, [:tenant_id, :user_id, :role_id, :scope_type, :scope_id],
                     name: "user_roles_unique_assignment_index"
                   )

    drop_if_exists index(:user_roles, [:user_id, :approved?],
                     name: "user_roles_user_approved_index"
                   )

    drop_if_exists index(:user_roles, [:role_id])

    drop_if_exists index(:user_roles, [:expires_at])

    drop_if_exists index(:user_roles, [:assigned_by_id])

    drop_if_exists index(:user_roles, [:scope_type, :scope_id])

    drop table(:user_roles)
  end
end
