defmodule Indrajaal.Repo.Migrations.CreateRemainingDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @spec up() :: any()
  def up do
    create table(:integration_webhooks, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "integration_webhooks_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :url, :text, null: false
      add :secret_key, :text
      add :active?, :boolean, null: false, default: true
      add :events, {:array, :text}, null: false, default: []
      add :http_method, :text, null: false, default: "post"
      add :content_type, :text, null: false, default: "application/json"
      add :timeout_seconds, :bigint, null: false, default: 30
      add :retry_attempts, :bigint, null: false, default: 3
      add :custom_headers, :map, default: %{}
      add :last_success_at, :utc_datetime_usec
      add :last_failure_at, :utc_datetime_usec
      add :failure_count, :bigint, null: false, default: 0
      add :total_calls, :bigint, null: false, default: 0
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "integration_webhooks_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:integration_webhooks, [:events], using: "gin")

    create index(:integration_webhooks, [:active?],
             name: "webhooks_active_index",
             where: "\"active?\" = true"
           )

    create index(:integration_webhooks, [:organization_id])

    create index(:integration_webhooks, [:tenant_id, :name], unique: true)

    create table(:integration_api_connections, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "integration_api_connections_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :connection_type, :text, null: false
      add :base_url, :text
      add :api_key, :text
      add :username, :text
      add :password, :text
      add :certificate_data, :text
      add :connection_config, :map, default: %{}
      add :status, :text, null: false, default: "disconnected"
      add :last_connected_at, :utc_datetime_usec
      add :last_error_at, :utc_datetime_usec
      add :last_error_message, :text
      add :connection_attempts, :bigint, null: false, default: 0
      add :rate_limit_per_minute, :bigint
      add :timeout_seconds, :bigint, null: false, default: 30
      add :enabled?, :boolean, null: false, default: true
      add :auto_retry?, :boolean, null: false, default: true
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "integration_api_connections_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:integration_api_connections, [:enabled?],
             name: "api_connections_enabled_index",
             where: "\"enabled?\" = true"
           )

    create index(:integration_api_connections, [:status])

    create index(:integration_api_connections, [:connection_type])

    create index(:integration_api_connections, [:organization_id])

    create index(:integration_api_connections, [:tenant_id, :name], unique: true)

    create table(:integration_sync_jobs, primary_key: false) do
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "integration_sync_jobs_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :job_type, :text, null: false, default: "scheduled"
      add :status, :text, null: false, default: "pending"
      add :direction, :text, null: false
      add :schedule_cron, :text
      add :batch_size, :bigint, null: false, default: 100
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :next_run_at, :utc_datetime_usec
      add :records_processed, :bigint, null: false, default: 0
      add :records_succeeded, :bigint, null: false, default: 0
      add :records_failed, :bigint, null: false, default: 0
      add :error_message, :text
      add :error_details, :map, default: %{}
      add :configuration, :map, default: %{}
      add :result_summary, :map, default: %{}
      add :enabled?, :boolean, null: false, default: true
      add :retry_count, :bigint, null: false, default: 0
      add :max_retries, :bigint, null: false, default: 3
      add :created_by, :uuid, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :api_connection_id,
          references(:integration_api_connections,
            column: :id,
            name: "integration_sync_jobs_api_connection_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :data_mapping_id, :uuid
      add :creator_id, :uuid
    end

    create index(:integration_sync_jobs, [:created_by])

    create index(:integration_sync_jobs, [:next_run_at],
             where: "next_run_at IS NOT NULL AND \"enabled?\" = true"
           )

    create index(:integration_sync_jobs, [:enabled?],
             name: "sync_jobs_enabled_index",
             where: "\"enabled?\" = true"
           )

    create index(:integration_sync_jobs, [:job_type])

    create index(:integration_sync_jobs, [:status])

    create index(:integration_sync_jobs, [:data_mapping_id], where: "data_mapping_id IS NOT NULL")

    create index(:integration_sync_jobs, [:api_connection_id])

    create table(:integration_data_mappings, primary_key: false) do
      add :tenant_id, :uuid, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:integration_sync_jobs) do
      modify :data_mapping_id,
             references(:integration_data_mappings,
               column: :id,
               name: "integration_sync_jobs_data_mapping_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :creator_id,
             references(:users,
               column: :id,
               name: "integration_sync_jobs_creator_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:integration_data_mappings) do
      add :name, :text, null: false
      add :source_system, :text, null: false
      add :target_system, :text, null: false
      add :entity_type, :text, null: false
      add :direction, :text, null: false, default: "inbound"
      add :field_mappings, :map, null: false, default: %{}
      add :transformation_rules, :map, default: %{}
      add :filter_conditions, :map, default: %{}
      add :active?, :boolean, null: false, default: true
      add :priority, :bigint, null: false, default: 100
      add :created_by, :uuid, null: false
      add :last_used_at, :utc_datetime_usec
      add :usage_count, :bigint, null: false, default: 0
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :api_connection_id,
          references(:integration_api_connections,
            column: :id,
            name: "integration_data_mappings_api_connection_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :creator_id,
          references(:users,
            column: :id,
            name: "integration_data_mappings_creator_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:integration_data_mappings, [:priority], where: "\"active?\" = true")

    create index(:integration_data_mappings, [:active?],
             name: "data_mappings_active_index",
             where: "\"active?\" = true"
           )

    create index(:integration_data_mappings, [:direction])

    create index(:integration_data_mappings, [:entity_type])

    create index(:integration_data_mappings, [:api_connection_id])

    alter table(:integration_data_mappings) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "integration_data_mappings_tenant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  @spec down() :: any()
  def down do
    drop constraint(:integration_data_mappings, "integration_data_mappings_tenant_id_fkey")

    drop constraint(
           :integration_data_mappings,
           "integration_data_mappings_api_connection_id_fkey"
         )

    drop constraint(:integration_data_mappings, "integration_data_mappings_creator_id_fkey")

    alter table(:integration_data_mappings) do
      modify :tenant_id, :uuid
    end

    drop_if_exists index(:integration_data_mappings, [:api_connection_id])

    drop_if_exists index(:integration_data_mappings, [:entity_type])

    drop_if_exists index(:integration_data_mappings, [:direction])

    drop_if_exists index(:integration_data_mappings, [:active?],
                     name: "data_mappings_active_index"
                   )

    drop_if_exists index(:integration_data_mappings, [:priority])

    alter table(:integration_data_mappings) do
      remove :creator_id
      remove :api_connection_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :usage_count
      remove :last_used_at
      remove :created_by
      remove :priority
      remove :active?
      remove :filter_conditions
      remove :transformation_rules
      remove :field_mappings
      remove :direction
      remove :entity_type
      remove :target_system
      remove :source_system
      remove :name
    end

    drop constraint(:integration_sync_jobs, "integration_sync_jobs_data_mapping_id_fkey")

    drop constraint(:integration_sync_jobs, "integration_sync_jobs_creator_id_fkey")

    alter table(:integration_sync_jobs) do
      modify :creator_id, :uuid
      modify :data_mapping_id, :uuid
    end

    drop table(:integration_data_mappings)

    drop constraint(:integration_sync_jobs, "integration_sync_jobs_tenant_id_fkey")

    drop constraint(:integration_sync_jobs, "integration_sync_jobs_api_connection_id_fkey")

    drop_if_exists index(:integration_sync_jobs, [:api_connection_id])

    drop_if_exists index(:integration_sync_jobs, [:data_mapping_id])

    drop_if_exists index(:integration_sync_jobs, [:status])

    drop_if_exists index(:integration_sync_jobs, [:job_type])

    drop_if_exists index(:integration_sync_jobs, [:enabled?], name: "sync_jobs_enabled_index")

    drop_if_exists index(:integration_sync_jobs, [:next_run_at])

    drop_if_exists index(:integration_sync_jobs, [:created_by])

    drop table(:integration_sync_jobs)

    drop constraint(:integration_api_connections, "integration_api_connections_tenant_id_fkey")

    drop constraint(
           :integration_api_connections,
           "integration_api_connections_organization_id_fkey"
         )

    drop_if_exists index(:integration_api_connections, [:tenant_id, :name])

    drop_if_exists index(:integration_api_connections, [:organization_id])

    drop_if_exists index(:integration_api_connections, [:connection_type])

    drop_if_exists index(:integration_api_connections, [:status])

    drop_if_exists index(:integration_api_connections, [:enabled?],
                     name: "api_connections_enabled_index"
                   )

    drop table(:integration_api_connections)

    drop constraint(:integration_webhooks, "integration_webhooks_tenant_id_fkey")

    drop constraint(:integration_webhooks, "integration_webhooks_organization_id_fkey")

    drop_if_exists index(:integration_webhooks, [:tenant_id, :name])

    drop_if_exists index(:integration_webhooks, [:organization_id])

    drop_if_exists index(:integration_webhooks, [:active?], name: "webhooks_active_index")

    drop_if_exists index(:integration_webhooks, [:events])

    drop table(:integration_webhooks)
  end
end
