// =============================================================================
// GenerateArtifacts.fsx - Script to embed YAML/Dockerfiles into F# source
// =============================================================================
open System
open System.IO

let artifacts = [
    "SIL6_COMPOSE", "lib/cepaf/artifacts/podman-compose-sil6-full-mesh.yml"
    "SWARM_14_COMPOSE", "lib/cepaf/artifacts/podman-compose-swarm-14.yml"
    "DOCKERFILE_DB", "Dockerfile.db"
    "DOCKERFILE_OBS", "Dockerfile.observability"
    "DOCKERFILE_APP", "Dockerfile.sopv51-app"
    "DOCKERFILE_BRIDGE", "Dockerfile.cepaf-bridge"
    "DOCKERFILE_CORTEX", "Dockerfile.cortex"
]

let header = """// =============================================================================
// Artifacts.fs - Embedded Mesh Configuration and Dockerfiles
// =============================================================================
// GENERATED BY scripts/automation/GenerateArtifacts.fsx
// =============================================================================

namespace Cepaf.Mesh

module Artifacts =

"""

let generateContent () =
    let contents = 
        artifacts 
        |> List.map (fun (key, path) ->
            if File.Exists(path) then
                let data = File.ReadAllText(path)
                sprintf "    let [<Literal>] %s = \"\"\"\n%s\"\"\"\n" key data
            else
                sprintf "    let [<Literal>] %s = \"\"\n" key
        )
    header + (String.concat "\n" contents)

let outputPath = "lib/cepaf/src/Cepaf/Mesh/Artifacts.fs"
File.WriteAllText(outputPath, generateContent())
printfn "Successfully generated %s" outputPath
