namespace Cepaf.Planning

open System
open System.Text.RegularExpressions

module MarkdownParser =

    let private headerRegex = Regex(@"^#+\s+([\d\.\wX]+)\s+-\s+(.+)", RegexOptions.Compiled)
    let private statusRegex = Regex(@"\*\*Status\*\*:\s*([^|\n]+)", RegexOptions.Compiled)
    let private priorityRegex = Regex(@"\*\*Priority\*\*:\s*([^|\n]+)", RegexOptions.Compiled)
    let private parentRegex = Regex(@"\*\*Parent\*\*:\s*([^|\n]+)", RegexOptions.Compiled)
    let private ownerRegex = Regex(@"\*\*Owner\*\*:\s*([^|\n]+)", RegexOptions.Compiled)
    let private assignedRegex = Regex(@"\*\*Assigned\*\*:\s*([^|\n]+)", RegexOptions.Compiled)

    let parse (content: string) : TaskItem list = 
        let lines = content.Split([|'\n'|])
        
        // Simple state machine loop
        let rec loop lines (currentTask: TaskItem option) acc = 
            match lines with 
            | [] -> 
                match currentTask with 
                | Some t -> (t :: acc) |> List.rev
                | None -> acc |> List.rev
            
            | line :: rest ->
                let headerMatch = headerRegex.Match(line)
                if headerMatch.Success then
                    let id = headerMatch.Groups.[1].Value.Trim()
                    let title = headerMatch.Groups.[2].Value.Trim()
                    
                    // Finalize previous task
                    let newAcc = 
                        match currentTask with 
                        | Some t -> t :: acc
                        | None -> acc

                    // Extract priority from title if present "(P1 ...)"
                    let titlePriorityMatch = Regex.Match(title, @"\((P\d).*\)")
                    let (cleanTitle, titlePriority) = 
                        if titlePriorityMatch.Success then
                            (title.Replace(titlePriorityMatch.Value, "").Trim(), Some (DomainHelpers.parsePriority titlePriorityMatch.Groups.[1].Value))
                        else
                            (title, None)

                    let newTask = {
                        Id = id
                        Title = cleanTitle
                        Status = Pending // Default
                        Priority = Option.defaultValue P3_Low titlePriority // Default P3
                        ParentId = None
                        Owner = None
                        Created = DateTime.UtcNow
                        RawLines = [line]
                    }
                    loop rest (Some newTask) newAcc
                else
                    match currentTask with 
                    | Some t ->
                        // Parse attributes from body lines
                        let statusMatch = statusRegex.Match(line)
                        let priorityMatch = priorityRegex.Match(line)
                        let parentMatch = parentRegex.Match(line)
                        let ownerMatch = ownerRegex.Match(line) // or Assigned

                        let updatedTask = 
                            t
                            |> fun task -> if statusMatch.Success then { task with Status = DomainHelpers.parseStatus statusMatch.Groups.[1].Value } else task
                            |> fun task -> if priorityMatch.Success then { task with Priority = DomainHelpers.parsePriority priorityMatch.Groups.[1].Value } else task
                            |> fun task -> if parentMatch.Success then { task with ParentId = Some (parentMatch.Groups.[1].Value.Trim()) } else task
                            |> fun task -> if ownerMatch.Success then { task with Owner = Some (ownerMatch.Groups.[1].Value.Trim()) } else task
                            |> fun task -> { task with RawLines = task.RawLines @ [line] }

                        loop rest (Some updatedTask) acc
                    | None ->
                        // Skip prologue lines or store them if we want to preserve file structure exactly
                        loop rest None acc

        loop (Array.toList lines) None []

    let generateMarkdown (tasks: TaskItem list) : string = 
        // Reconstruct markdown from tasks - simplistic version for now
        // Ideally we preserve the prologue/epilogue
        let sb = System.Text.StringBuilder()
        sb.AppendLine("# PROJECT TODOLIST (Generated by Cepaf.Planning)") |> ignore
        sb.AppendLine() |> ignore
        
        for task in tasks do
            for line in task.RawLines do
                sb.AppendLine(line) |> ignore
            // Ensure spacing
            sb.AppendLine() |> ignore
            
        sb.ToString()
