use crate::db::{get_all_tasks, Task};
use crate::errors::IgnitionError;
use std::fs;

pub fn generate_markdown() -> Result<(), IgnitionError> {
    let tasks = get_all_tasks()?;
    let mut content = String::new();
    content.push_str("# PROJECT TODOLIST (Generated by sa-plan-daemon)\n");
    content.push_str("<!-- MANDATE: SC-TODO-001 | AUTHORITY: sa-plan | STATUS: READ-ONLY ARTIFACT -->\n");
    content.push_str("<!-- DO NOT EDIT THIS FILE MANUALLY. ALL CHANGES WILL BE OVERWRITTEN. -->\n");
    content.push_str("<!-- USE: ./sa-plan add/update/status -->\n\n");
    
    for task in tasks {
        let status_mark = match task.status.as_str() {
            "completed" => "[x]",
            "in_progress" => "[~]",
            "blocked" => "[!]",
            _ => "[ ]",
        };
        content.push_str(&format!("{} {} - {} ({}) [{}]\n", status_mark, task.id, task.title, task.priority, task.status.to_uppercase()));
    }
    
    fs::write("PROJECT_TODOLIST.md", content)?;
    Ok(())
}
