defmodule TDGValidatorTest do
  use ExUnit.Case, async: true
  use Indrajaal.Ultimate.TestConsolidation

  @moduledoc """
  Test suite for Test - Driven Generation Validator

  Validates TDG compliance enforcement and AI code detection
  within the git pre - commit workflow.
  """

  describe "TDG validation core functionality" do
    test "validates TDG validator module definition" do
      # Test TDG validator exists and is properly structured
      assert File.exists?("scripts / testing / tdg_validator.exs")
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "defmodule TDGValidator")
      assert String.contains?(content, "Test - Driven Generation Validator")
    end

    test "ensures AI code detection markers" do
      # Test AI detection markers are properly defined
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "# Generated by Claude")
      assert String.contains?(content, "# AI - generated")
      assert String.contains?(content, "@doc false # AI generated")
    end

    test "validates test file path generation" do
      # Test that test file paths are correctly generated
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "get_test_file_path")
      assert String.contains?(content, "lib/")
      assert String.contains?(content, "test/")
      assert String.contains?(content, "_test.exs")
    end
  end

  describe "pre - commit validation" do
    test "validates pre - commit hook integration" do
      # Test pre - commit functionality
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "validate_pre_commit")
      assert String.contains?(content, "git diff --cached --name - only")
    end

    test "ensures staged file filtering" do
      # Test Elixir file filtering
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "elixir_files")
      assert String.contains?(content, ".ex")
      assert String.contains?(content, ".exs")
    end

    test "validates TDG compliance checking" do
      # Test TDG compliance validation
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "validate_file_tdg_compliance")
      assert String.contains?(content, "is_ai_generated")
    end
  end

  describe "module extraction and testing" do
    test "validates module name extraction" do
      # Test module name extraction functionality
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "extract_module_name")
      assert String.contains?(content, "defmodule")
    end

    test "ensures test file existence checking" do
      # Test test file existence validation
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "check_test_file_exists")
      assert String.contains?(content, "File.exists?")
    end

    test "validates test content verification" do
      # Test that test files actually test the module
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "test_content")
      assert String.contains?(content, "module_name")
    end
  end

  describe "comprehensive validation" do
    test "validates comprehensive TDG checking" do
      # Test comprehensive validation functionality
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "comprehensive_validation")
      assert String.contains?(content, "Path.wildcard")
      assert String.contains?(content, "lib/**/*.ex")
    end

    test "ensures compliance rate calculation" do
      # Test compliance rate calculation
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "compliance_rate")
      assert String.contains?(content, "Float.round")
    end

    test "validates usage documentation" do
      # Test usage documentation
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "show_usage")
      assert String.contains?(content, "--pre - commit")
      assert String.contains?(content, "--comprehensive")
    end
  end

  describe "error handling and exit codes" do
    test "validates proper exit code handling" do
      # Test exit code handling
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "System.halt(0)")
      assert String.contains?(content, "System.halt(1)")
    end

    test "ensures proper error reporting" do
      # Test error reporting
      content = File.read!("scripts / testing / tdg_validator.exs")

      assert String.contains?(content, "TDG violations detected")
      assert String.contains?(content, "❌")
      assert String.contains?(content, "✅")
    end
  end
end

# Test file for TDG validator
# Validates Test - Driven Generation compliance checking
