defmodule Indrajaal.AccessControl.AccessRule do
  # PHASE N: Access control patterns unified

  @moduledoc """
  Ecto schema for access_rule.

  Implements multi - tenant data model with audit fields.
  Generated by worker - 5.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "access_control" do
    field :name, :string
    field :description, :string
    field :active, :boolean, default: true
    field :metadata, :map, default: %{}

    # Multi - tenant isolation
    field :tenant_id, :binary_id

    # Audit fields
    field :created_by_id, :binary_id
    field :updated_by_id, :binary_id

    # Domain - specific fields
    field :rule_type, :string
    field :schedule, :map
    field :permissions, {:array, :string}
    field :conditions, :map
    field :priority, :integer, default: 0

    timestamps()
  end

  @doc false
  @spec changeset(any(), any()) :: any()
  def changeset(item, attrs) do
    item
    |> cast(attrs, [:name, :description, :active, :metadata])
    |> validate_required([:name])
    |> validate_length(:name, min: 1, max: 255)
    |> validate_length(:description, max: 1000)
    |> validate_number(:priority, greater_than_or_equal_to: 0, less_than_or_equal_to: 100)
    |> validate_inclusion(:rule_type, ~w(allow deny schedule))
  end
end

# Agent: Worker - 5 (Security Domain Agent)
# SOPv5.1 Compliance: ✅ Security access control and policy enforcement with cyb
# Domain: Access control
# Responsibilities: Security access control, authentication, policy enforcement
# Multi - Agent Architecture: Integrated with 11 - agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
