#!/usr/bin/env elixir

defmodule TDGValidator do
  @moduledoc "Test-Driven Generation validation for git operations"

  @spec validate_tdg_compliance(any()) :: any()
  def validate_tdg_compliance(changed_files) do
    IO.puts("🧪 Validating TDG compliance...")

    # Filter AI-generated files
    ai_files = filter_ai_generated_files(changed_files)

    if length(ai_files) == 0 do
      IO.puts("  ✅ No AI-generated files detected")
      true
    else
      IO.puts("  🤖 AI-generated files detected: #{length(ai_files)}")

      # Check each AI file has corresponding tests
      violations = Enum.filter(ai_files, fn file ->
        not has_corresponding_tests(file)
      end)

      if length(violations) == 0 do
        IO.puts("  ✅ All AI-generated files have corresponding tests")
        true
      else
        IO.puts("  ❌ TDG violations detected:")
        Enum.each(violations, fn file ->
          IO.puts("    - Missing tests for: #{file}")
        end)
        false
      end
    end
  end

  @spec filter_ai_generated_files(term()) :: term()
  defp filter_ai_generated_files(files) do
    # Heuristics to detect AI-generated files
    Enum.filter(files, fn file ->
      if File.exists?(file) and String.ends_with?(file, [".ex", ".exs"]) do
        content = File.read!(file)

        # Check for AI generation markers
        ai_markers = [
          "# Generated by Claude",
          "# AI-generated",
          "@doc false # AI generated",
          "# This code was generated"
        ]

        Enum.any?(ai_markers, fn marker ->
          String.contains?(content, marker)
        end)
      else
        false
      end
    end)
  end

  @spec has_corresponding_tests(term()) :: term()
  defp has_corresponding_tests(file) do
    # Check if file has corresponding test file
    test_file = file
    |> String.replace("lib/", "test/")
    |> String.replace(".ex", "_test.exs")

    if File.exists?(test_file) do
      test_content = File.read!(test_file)

      # Check if test file actually tests the module
      module_name = extract_module_name(file)
      String.contains?(test_content, module_name)
    else
      false
    end
  end

  @spec extract_module_name(term()) :: term()
  defp extract_module_name(file) do
    if File.exists?(file) do
      content = File.read!(file)

      case Regex.run(~r/defmodule\s+([A-Za-z0-9_.]+)/, content) do
        [_, module_name] -> module_name
        _ -> ""
      end
    else
      ""
    end
  end

  @spec validate_test_first_development(any()) :: any()
  def validate_test_first_development(commit_message) do
    IO.puts("🎯 Validating test-first development...")

    # Check if commit message indicates proper TDD workflow
    tdd_indicators = [
      "test:",
      "spec:",
      "TDD:",
      "test-driven",
      "failing test",
      "red-green-refactor"
    ]

    is_test_commit = Enum.any?(tdd_indicators, fn indicator ->
      String.contains?(String.downcase(commit_message), indicator)
    end)

    if is_test_commit do
      IO.puts("  ✅ Test-first development indicators found")
      true
    else
      # Check if this is a test file commit
      {_changed_files, __} = System.cmd("git", ["diff", "--name-only", "HEAD~1"])
      files = String.split(changed_files, "\n", trim: true)

      test_files = Enum.filter(files, fn file ->
        String.contains?(file, "test/") or String.ends_with?(file, "_test.exs")
      end)

      if length(test_files) > 0 do
        IO.puts("  ✅ Test files included in commit")
        true
      else
        IO.puts("  ⚠️  No clear test-first development indicators")
        true  # Don't block commits, just warn
      end
    end
  end
end
