defmodule Indrajaal.VisitorManagement.Visitor do
  @moduledoc """
  Ash resource for visitor management.

  Implements multi - tenant data model with audit fields.
  Generated by worker - 6.
  """

  use Indrajaal.BaseResource,
    domain: Indrajaal.VisitorManagement

  use Indrajaal.Multitenancy.TenantResource

  attributes do
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
      public? true
    end

    attribute :description, :string do
      public? true
    end

    attribute :active, :boolean do
      default true
      public? true
    end

    attribute :metadata, :map do
      default %{}
      public? true
    end

    # Domain-specific fields
    attribute :type, :string do
      public? true
    end

    attribute :status, :string do
      public? true
    end

    attribute :configuration, :map do
      public? true
    end

    attribute :tags, {:array, :string} do
      default []
      public? true
    end

    # Relationship fields
    attribute :visitor_type_id, :uuid do
      public? true
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :visitor_type, Indrajaal.VisitorManagement.VisitorType do
      source_attribute :visitor_type_id
      destination_attribute :id
      allow_nil? true
    end
  end

  actions do
    defaults [:create, :read, :update, :destroy]
  end

  validations do
    validate present(:name), message: "Name is _required"
    validate string_length(:name, min: 1, max: 255)
    validate string_length(:description, max: 1000)
  end

  postgres do
    table "visitors"
    repo Indrajaal.Repo

    custom_indexes do
      index [:tenant_id, :visitor_type_id]
      index [:tenant_id, :type]
      index [:tenant_id, :status]
      index [:tenant_id, :active]
    end
  end
end

# Agent: Worker - 6 (Visitor Management Domain Agent)
# SOPv5.1 Compliance: ✅ Visitor management and identity verification coordination
# Domain: VisitorManagement
# Responsibilities: Visitor lifecycle, identity verification, access control
# Multi - Agent Architecture: Integrated with 11 - agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
