defmodule IndrajaalWeb.Prajna.AccessControlLivePropTest do
  @moduledoc """
  Property-based tests for AccessControlLive.

  WHAT: Verifies that AccessControlLive maintains invariants across all valid
        inputs — action/resource/timerange filter combinations are total,
        permission IDs generated by init_permissions are well-formed, anomaly
        detection state is consistent.
  WHY: AccessControlLive has 50-entry permission list and 50-entry audit trail,
       filtered by action (:grant/:deny/:revoke/:all) and timerange
       (:last_15m/:last_1h/:last_24h). Property tests verify correctness under
       adversarial filter sequences and search inputs.
  CONSTRAINTS: SC-COV-001, SC-TDG-001, SC-SEC-044, SC-PRAJNA-004, EP-GEN-014

  TDG Level: L1 (Property Testing)
  """

  use IndrajaalWeb.ConnCase, async: true
  use PropCheck
  import ExUnitProperties, except: [property: 2, property: 3, check: 2]

  alias PropCheck.BasicTypes, as: PC
  alias StreamData, as: SD

  import Phoenix.LiveViewTest

  @moduletag :property
  @moduletag :zenoh_nif

  @valid_actions ["all", "grant", "deny", "revoke"]
  @valid_timeranges ["last_15m", "last_1h", "last_24h"]
  @valid_resources ["all", "alarms", "devices", "users", "reports", "config"]

  # ═══════════════════════════════════════════════════════════════════════
  # ACTION FILTER PROPERTIES
  # ═══════════════════════════════════════════════════════════════════════

  describe "action filter properties" do
    property "P-ACL-001: any valid action filter produces a valid page" do
      forall action <- PC.oneof(@valid_actions) do
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")
        html = render_click(view, "filter_action", %{"action" => action})

        is_binary(html) and String.length(html) > 100
      end
    end

    property "P-ACL-002: action filter is idempotent" do
      forall action <- PC.oneof(@valid_actions) do
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")

        html1 = render_click(view, "filter_action", %{"action" => action})
        html2 = render_click(view, "filter_action", %{"action" => action})

        html1 == html2
      end
    end

    property "P-ACL-003: any sequence of action filter switches ends in valid state" do
      forall actions <- PC.non_empty(PC.list(PC.oneof(@valid_actions))) do
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")

        Enum.each(actions, fn action ->
          render_click(view, "filter_action", %{"action" => action})
        end)

        html = render(view)
        is_binary(html) and String.length(html) > 100
      end
    end
  end

  # ═══════════════════════════════════════════════════════════════════════
  # TIMERANGE FILTER PROPERTIES
  # ═══════════════════════════════════════════════════════════════════════

  describe "timerange filter properties" do
    property "P-ACL-004: any valid timerange filter produces a valid page" do
      forall range <- PC.oneof(@valid_timeranges) do
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")
        html = render_click(view, "filter_timerange", %{"range" => range})

        is_binary(html) and String.length(html) > 100
      end
    end

    property "P-ACL-005: action and timerange filters compose safely" do
      forall {action, range} <- {PC.oneof(@valid_actions), PC.oneof(@valid_timeranges)} do
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")

        render_click(view, "filter_action", %{"action" => action})
        html = render_click(view, "filter_timerange", %{"range" => range})

        is_binary(html) and String.length(html) > 100
      end
    end
  end

  # ═══════════════════════════════════════════════════════════════════════
  # RESOURCE FILTER PROPERTIES
  # ═══════════════════════════════════════════════════════════════════════

  describe "resource filter properties" do
    property "P-ACL-006: any valid resource filter produces a valid page" do
      forall resource <- PC.oneof(@valid_resources) do
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")
        html = render_click(view, "filter_resource", %{"resource" => resource})

        is_binary(html) and String.length(html) > 100
      end
    end

    property "P-ACL-007: three-way filter combination is always safe" do
      forall {action, range, resource} <-
               {PC.oneof(@valid_actions), PC.oneof(@valid_timeranges), PC.oneof(@valid_resources)} do
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")

        render_click(view, "filter_action", %{"action" => action})
        render_click(view, "filter_timerange", %{"range" => range})
        html = render_click(view, "filter_resource", %{"resource" => resource})

        is_binary(html) and String.length(html) > 100
      end
    end
  end

  # ═══════════════════════════════════════════════════════════════════════
  # PERMISSION ID EXISTENCE PROPERTIES
  # ═══════════════════════════════════════════════════════════════════════

  describe "permission ID properties" do
    property "P-ACL-008: selecting a known permission ID renders detail without crash" do
      # init_permissions generates perm_001 through perm_025
      forall n <- PC.integer(1, 25) do
        id = "perm_#{String.pad_leading(Integer.to_string(n), 3, "0")}"
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")
        html = render_click(view, "select_permission", %{"id" => id})

        is_binary(html) and String.length(html) > 100
      end
    end

    property "P-ACL-009: close_detail after select_permission restores base view" do
      forall n <- PC.integer(1, 25) do
        id = "perm_#{String.pad_leading(Integer.to_string(n), 3, "0")}"
        {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")

        render_click(view, "select_permission", %{"id" => id})
        html = render_click(view, "close_detail", %{})

        is_binary(html) and String.length(html) > 100
      end
    end
  end

  # ═══════════════════════════════════════════════════════════════════════
  # STREAMDATA TESTS (ExUnitProperties)
  # ═══════════════════════════════════════════════════════════════════════

  describe "StreamData property tests" do
    @tag timeout: 30_000
    check all(
            action <- SD.member_of(["all", "grant", "deny", "revoke"]),
            range <- SD.member_of(["last_15m", "last_1h", "last_24h"]),
            max_runs: 10
          ) do
      {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")
      render_click(view, "filter_action", %{"action" => action})
      html = render_click(view, "filter_timerange", %{"range" => range})
      assert is_binary(html)
      assert String.length(html) > 100
    end

    @tag timeout: 30_000
    check all(
            n <- SD.integer(1, 25),
            max_runs: 10
          ) do
      id = "perm_#{String.pad_leading(Integer.to_string(n), 3, "0")}"
      {:ok, view, _html} = live(build_conn(), "/cockpit/access-control")
      render_click(view, "select_permission", %{"id" => id})
      html = render_click(view, "close_detail", %{})
      assert is_binary(html)
      assert String.length(html) > 100
    end
  end
end
