defmodule Indrajaal.Sites.Site do
  @moduledoc """
  Ash resource for site management.

  Implements multi - tenant data model with audit fields.
  Generated by worker - 3.
  """

  use Indrajaal.BaseResource,
    domain: Indrajaal.Sites

  use Indrajaal.Multitenancy.TenantResource

  postgres do
    table "sites"
    repo Indrajaal.Repo
  end

  attributes do
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
      public? true
    end

    attribute :code, :string do
      allow_nil? false
      public? true
    end

    attribute :description, :string do
      public? true
    end

    attribute :status, :string do
      default "active"
      public? true
    end

    attribute :site_type, :string do
      default "office"
      public? true
    end

    attribute :security_level, :string do
      default "medium"
      public? true
    end

    attribute :metadata, :map do
      default %{}
      public? true
    end

    # Domain-specific fields
    attribute :address, :map do
      default %{}
      public? true
    end

    attribute :timezone, :string do
      public? true
    end

    attribute :coordinates, :map do
      public? true
    end

    attribute :business_hours, :map do
      public? true
    end

    attribute :contact_info, :map do
      default %{}
      public? true
    end

    attribute :current_occupancy, :integer do
      default 0
      public? true
    end

    attribute :max_occupancy, :integer do
      public? true
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :tenant, Indrajaal.Core.Tenant do
      allow_nil? false
      attribute_public? true
    end

    belongs_to :organization, Indrajaal.Core.Organization do
      allow_nil? true
      attribute_public? true
      attribute_writable? true
    end
  end

  actions do
    defaults [:read, :update, :destroy]

    create :create do
      primary? true

      accept [
        :name,
        :code,
        :description,
        :status,
        :site_type,
        :security_level,
        :metadata,
        :address,
        :timezone,
        :coordinates,
        :business_hours,
        :contact_info,
        :current_occupancy,
        :max_occupancy,
        :tenant_id,
        :organization_id
      ]
    end

    read :by_id do
      argument :id, :uuid, allow_nil?: false

      filter expr(id == ^arg(:id))
    end

    read :updated_since do
      argument :since, :utc_datetime, allow_nil?: false

      filter expr(updated_at >= ^arg(:since))
    end
  end

  code_interface do
    define :create
    define :read
    define :update
    define :destroy
    define :by_id, args: [:id]
    define :updated_since, args: [:since]
  end

  validations do
    validate present(:name), message: "Name is _required"
    validate string_length(:name, min: 1, max: 255)
    validate string_length(:description, max: 1000)
  end
end

# Agent: Worker - 4 (Sites Domain Agent)
# SOPv5.1 Compliance: ✅ Site management and geographic coordination with cybern
# Domain: Sites
# Responsibilities: Site management, geographic coordination, area monitoring
# Multi - Agent Architecture: Integrated with 11 - agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
