# lib/indrajaal/kms/immortality/reconstruction_guide.ex
defmodule Indrajaal.KMS.Immortality.ReconstructionGuide do
  @moduledoc """
  Generates self-documenting reconstruction guides for SMRITI.

  WHAT: Produces a human-readable guide that future civilizations can use
  to reconstruct the SMRITI knowledge base from exported data. The guide
  includes real schema, actual holon counts, and verified checksums.

  WHY: SC-SMRITI-071 requires self-documenting exports. SC-HOLON-016 demands
  format stability for future reconstruction. A guide with hardcoded dummy
  data is useless for actual reconstruction.

  CONSTRAINTS:
  - SC-SMRITI-071: Self-documenting reconstruction guide
  - SC-HOLON-016: Format stability for reconstruction
  - SC-HOLON-010: Regenerable from exported state alone

  ## Change History
  | Version | Date       | Author | Change                                      |
  |---------|------------|--------|---------------------------------------------|
  | 21.2.1  | 2026-03-10 | Claude | Fix: data-driven from actual SQLite state   |
  | 21.0.0  | 2026-01-05 | Claude | Initial stub (hardcoded static guide)       |

  Task 42.3.0.0.0
  """

  alias Indrajaal.KMS.SQLite

  @schema_version "1.0.0"

  @doc """
  Generates a reconstruction guide from the actual SMRITI database state.

  Options:
  - `:db_path` — path to the SMRITI SQLite database
  """
  @spec generate(keyword()) :: String.t()
  def generate(opts \\ []) do
    db_path = Keyword.get(opts, :db_path, get_db_path())
    stats = gather_stats(db_path)
    schema = gather_schema(db_path)

    """
    # SMRITI Knowledge Base Reconstruction Guide
    **Schema Version**: #{@schema_version}
    **Generated**: #{DateTime.to_iso8601(DateTime.utc_now())}
    **Source Database**: #{db_path}

    ## 1. Prerequisites
    - SQLite >= 3.40.0 (FTS5 extension required)
    - Elixir >= 1.19.0 with OTP 28+ (for runtime verification)

    ## 2. Database Statistics
    - **Holons**: #{stats.holon_count}
    - **Evolution Events**: #{stats.event_count}
    - **Clusters**: #{stats.cluster_count}
    - **Database Size**: #{stats.db_size_bytes} bytes
    - **Integrity**: #{stats.integrity_status}

    ## 3. Database Schema
    ```sql
    #{schema}
    ```

    ## 4. Reconstruction Procedure
    1. Create a new SQLite database: `sqlite3 smriti_reconstructed.db`
    2. Apply the schema from Section 3 above
    3. Import data from the JSON export: `smriti_export.json`
    4. Verify integrity: `PRAGMA integrity_check;`
    5. Rebuild FTS index: `INSERT INTO holons_fts(holons_fts) VALUES('rebuild');`
    6. Verify holon count matches: `SELECT COUNT(*) FROM holons;` → should be #{stats.holon_count}

    ## 5. Verification Checksums
    - DB File SHA-256: #{stats.db_checksum}

    ## 6. Format Reference
    - Holon UUID: RFC 4122 v4 format
    - Timestamps: ISO 8601 UTC (e.g., 2026-01-05T12:00:00Z)
    - Content Hash: SHA-256 hex-encoded lowercase
    - Tags: Comma-separated in TEXT column
    - Entropy: REAL value 0.0 (pristine) to 1.0 (maximum entropy)

    ---
    *Generated by Indrajaal SMRITI Immortality Protocol v21.2.1*
    *This guide is self-contained. No external dependencies required for reconstruction.*
    """
  end

  defp gather_stats(db_path) do
    holon_count = query_count(db_path, "SELECT COUNT(*) FROM holons")
    event_count = query_count(db_path, "SELECT COUNT(*) FROM evolution_events")

    cluster_count =
      query_count(db_path, "SELECT COUNT(DISTINCT cluster) FROM holons WHERE cluster IS NOT NULL")

    db_size =
      if File.exists?(db_path) do
        case File.stat(db_path) do
          {:ok, %{size: size}} -> size
          _ -> 0
        end
      else
        0
      end

    integrity = check_integrity(db_path)
    checksum = compute_file_checksum(db_path)

    %{
      holon_count: holon_count,
      event_count: event_count,
      cluster_count: cluster_count,
      db_size_bytes: db_size,
      integrity_status: integrity,
      db_checksum: checksum
    }
  end

  defp query_count(db_path, sql) do
    unless File.exists?(db_path) do
      0
    else
      case SQLite.query(db_path, sql) do
        {:ok, [%{} = row]} -> row |> Map.values() |> List.first() || 0
        {:ok, [[count]]} -> count
        _ -> 0
      end
    end
  rescue
    _ -> 0
  end

  defp check_integrity(db_path) do
    unless File.exists?(db_path) do
      "no_database"
    else
      case SQLite.query(db_path, "PRAGMA integrity_check") do
        {:ok, _} -> "ok"
        _ -> "unknown"
      end
    end
  rescue
    _ -> "unknown"
  end

  defp compute_file_checksum(db_path) do
    if File.exists?(db_path) do
      db_path
      |> File.read!()
      |> then(&:crypto.hash(:sha256, &1))
      |> Base.encode16(case: :lower)
    else
      "no_file"
    end
  rescue
    _ -> "unavailable"
  end

  defp gather_schema(db_path) do
    unless File.exists?(db_path) do
      default_schema()
    else
      case SQLite.query(
             db_path,
             "SELECT sql FROM sqlite_master WHERE type='table' AND sql IS NOT NULL ORDER BY name"
           ) do
        {:ok, rows} when is_list(rows) and rows != [] ->
          rows
          |> Enum.map(fn
            %{sql: sql} when is_binary(sql) -> sql <> ";"
            [sql] when is_binary(sql) -> sql <> ";"
            _ -> nil
          end)
          |> Enum.reject(&is_nil/1)
          |> Enum.join("\n\n")

        _ ->
          default_schema()
      end
    end
  rescue
    _ -> default_schema()
  end

  defp default_schema do
    """
    CREATE TABLE holons (
        holon_uuid TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        content TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        entropy REAL DEFAULT 0.0,
        cluster TEXT,
        tags TEXT,
        created_at TEXT,
        updated_at TEXT
    );

    CREATE TABLE evolution_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        holon_id TEXT NOT NULL,
        type TEXT NOT NULL,
        timestamp TEXT NOT NULL,
        changes TEXT,
        parent_event TEXT,
        metadata TEXT
    );

    CREATE VIRTUAL TABLE holons_fts USING fts5(title, content, tags, content='holons');
    """
  end

  defp get_db_path do
    Application.get_env(:indrajaal, :smriti_db_path, "data/kms/smriti.db")
  end
end
