defmodule Indrajaal.FactoryAlignmentTest do
  use Indrajaal.DataCase, async: true

  @moduledoc """
  Tests that factories are properly aligned with Ash domain APIs.
  Generated by SOPv5.1 Task 8.4.1.
  """

  describe "factory alignment validation" do
    test "tenant_factory creates valid tenant" do
      tenant = insert(:tenant)

      assert tenant.id
      assert tenant.name
      assert tenant.slug
      assert tenant.status == :active
    end

    test "user_factory creates valid user with tenant" do
      tenant = insert(:tenant)
      user = insert(:user, tenant: tenant)

      assert user.id
      assert user.tenant_id == tenant.id
      assert user.email =~ ~r/@test\.example\.com$/
    end

    test "team_factory creates valid team" do
      tenant = insert(:tenant)
      team = insert(:team, tenant: tenant)

      assert team.id
      assert team.tenant_id == tenant.id
      assert team.name
    end

    test "role_factory creates valid role" do
      tenant = insert(:tenant)
      role = insert(:role, tenant: tenant)

      assert role.id
      assert role.tenant_id == tenant.id
      assert role.name
    end

    test "factories handle relationships properly" do
      user = insert(:user)
      team = insert(:team, tenant: user.tenant)

      membership = insert(:team_membership, user: user, team: team)

      assert membership.user_id == user.id
      assert membership.team_id == team.id
      assert membership.tenant_id == user.tenant_id
    end
  end
end

# Agent: Helper - 2 (General Purpose Agent)
# SOPv5.1 Compliance: ✅ General system coordination and management with cyberne
# Domain: General
# Responsibilities: Template generation, standards enforcement, general coordin
# Multi - Agent Architecture: Integrated with 11 - agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
