#!/usr/bin/env -S dotnet fsi

// =========================================================================================
// INDRAJAAL TEST MANAGER (THE OBSERVER)
// Version: 1.1.0
// Architecture: External Observer (F#) monitoring System (Elixir/Podman)
// Compliance: SC-SIL6-020 (Separation of Concerns), SC-METRICS-003 (Mandatory Parallelization)
// ELIXIR_ERL_OPTIONS: "+fnu +S 16:16 +SDio 16" for 16 schedulers, 16 dirty I/O schedulers
// =========================================================================================

#r "nuget: Microsoft.Data.Sqlite"
#r "nuget: Dapper"

open System
open System.Diagnostics
open System.IO
open Microsoft.Data.Sqlite
open Dapper

// --- ONTOLOGY TYPES ---

type TestDefinition = {
    Id: string
    Name: string
    Type: string
    Constraints: string // JSON
    Description: string
}

type TestExecution = {
    Id: string
    DefId: string
    ConfigId: string
    MutationId: string
    StartTime: string
    mutable EndTime: string option
    mutable Verdict: string
}

type TelemetrySignal = {
    ExecutionId: string
    Level: string
    Source: string
    Data: string
}

// --- DATABASE LAYER ---

let dbPath = "data/kms/test_manager.db"
let connectionString = sprintf "Data Source=%s" dbPath

let initDb () =
    use conn = new SqliteConnection(connectionString)
    conn.Open()
    conn.Execute("""
        CREATE TABLE IF NOT EXISTS test_definitions (
            Id TEXT PRIMARY KEY, Name TEXT, Type TEXT, Constraints TEXT
        );
        CREATE TABLE IF NOT EXISTS test_executions (
            Id TEXT PRIMARY KEY, DefId TEXT, ConfigId TEXT, StartTime TEXT, EndTime TEXT, Verdict TEXT
        );
        CREATE TABLE IF NOT EXISTS telemetry_signals (
            Id INTEGER PRIMARY KEY AUTOINCREMENT, ExecutionId TEXT, Level TEXT, Source TEXT, Data TEXT
        );
    """) |> ignore

let registerTest name ttype constraints =
    use conn = new SqliteConnection(connectionString)
    let id = Guid.NewGuid().ToString("N")
    let def = { Id = id; Name = name; Type = ttype; Constraints = constraints; Description = "Auto-generated by F# Test Manager" }
    conn.Execute("INSERT INTO test_definitions (id, name, type, stamp_constraints, description) VALUES (@Id, @Name, @Type, @Constraints, @Description)", def) |> ignore
    id

let startExecution defId configId =
    use conn = new SqliteConnection(connectionString)
    let id = Guid.NewGuid().ToString("N")
    // Placeholder for mutation ID
    let mutationId = "git_current"
    let exec = { 
        Id = id; DefId = defId; ConfigId = configId; MutationId = mutationId;
        StartTime = DateTime.UtcNow.ToString("O"); EndTime = None; Verdict = "running" 
    }
    conn.Execute("INSERT INTO test_executions (id, def_id, config_id, mutation_id, start_time, verdict) VALUES (@Id, @DefId, @ConfigId, @MutationId, @StartTime, @Verdict)", exec) |> ignore
    id

let finishExecution id verdict =
    use conn = new SqliteConnection(connectionString)
    let endTime = DateTime.UtcNow.ToString("O")
    conn.Execute("UPDATE test_executions SET EndTime = @EndTime, Verdict = @Verdict WHERE Id = @Id", 
        {| EndTime = endTime; Verdict = verdict; Id = id |}) |> ignore

let logTelemetry execId level source data =
    use conn = new SqliteConnection(connectionString)
    conn.Execute("INSERT INTO telemetry_signals (ExecutionId, Level, Source, Data) VALUES (@ExecutionId, @Level, @Source, @Data)",
        { ExecutionId = execId; Level = level; Source = source; Data = data }) |> ignore

// --- ORCHESTRATION LAYER ---

// SC-METRICS-003: Mandatory parallelization environment variables
let mandatoryEnvVars = [
    ("ELIXIR_ERL_OPTIONS", "+fnu +S 16:16 +SDio 16")
    ("NO_TIMEOUT", "true")
    ("PATIENT_MODE", "enabled")
    ("INFINITE_PATIENCE", "true")
    ("MIX_OS_DEPS_COMPILE_PARTITION_COUNT", "8")
    ("SKIP_ZENOH_NIF", "0")
]

let injectMandatoryEnv (psi: ProcessStartInfo) =
    for (key, value) in mandatoryEnvVars do
        psi.EnvironmentVariables.[key] <- value

let runCommand cmd args =
    let psi = ProcessStartInfo(FileName = cmd, Arguments = args, UseShellExecute = false, RedirectStandardOutput = true, RedirectStandardError = true)
    injectMandatoryEnv psi  // SC-METRICS-003: Inject mandatory env vars
    let p = Process.Start(psi)
    p.WaitForExit()
    (p.ExitCode, p.StandardOutput.ReadToEnd())

let runSuite mode execId =
    printfn ">>> [OBSERVER] Launching System in %s mode..." mode
    logTelemetry execId "L1" "Observer" (sprintf "Starting %s" mode)
    
    // 1. Start (The Observed)
    let (upCode, upOut) = runCommand "./sa-up.fsx" ("--" + mode)
    if upCode <> 0 then 
        logTelemetry execId "L1" "System" (sprintf "Startup Failed: %s" upOut)
        false
    else
        logTelemetry execId "L1" "System" "Startup Complete"
        
        // 2. Verify (External Probe)
        printfn ">>> [OBSERVER] Probing System Health..."
        let (verifyCode, _) = runCommand "bash" "scripts/verification/fractal_verify_all.sh"
        
        // 3. Shutdown
        runCommand "./sa-down.fsx" "" |> ignore
        
        if verifyCode = 0 then true else false

let runFormalAudit execId =
    printfn ">>> [OBSERVER] Initiating Formal Mathematical Audit..."
    logTelemetry execId "L7" "Math" "Starting Agda/Quint/Graph Audit"
    
    let agda = runCommand "agda" "--check verification/agda/Consensus.agda"
    let quint = runCommand "quint" "verify --invariant=safety_invariant verification/quint/OODA.qnt"
    let graph = runCommand "elixir" "-e 'Indrajaal.AI.Simplex.GraphVerification.verify_topology(actual_graph)'" // Mocked for script
    
    let (aCode, _) = agda
    let (qCode, _) = quint
    
    if aCode = 0 && qCode = 0 then
        printfn ">>> [OBSERVER] Formal Audit: PASSED (Logic is Proven)"
        true
    else
        printfn ">>> [OBSERVER] Formal Audit: FAILED (Invariant Violation)"
        false

// --- MAIN LOOP ---

initDb()

printfn "================================================================================"
printfn "   INDRAJAAL TEST MANAGER (F# OBSERVER)"
printfn "   Formal Unification: SIL6 Certified"
printfn "================================================================================"

let defId = registerTest "MasterSuite" "integration" "SC-MAT-001, SC-MAT-002"
let execId = startExecution defId "config_fractal_v1"

// 1. Mandatory Formal Gate
if not (runFormalAudit execId) then
    finishExecution execId "fail"
    printfn ">>> [FATAL] Formal Verification Failed. Aborting execution."
    Environment.Exit(1)

let modes = ["dev"; "cluster"; "fractal"; "panopticon"]
let mutable allPassed = true

for mode in modes do
    if runSuite mode execId then
        printfn ">>> [OBSERVER] %s Mode: PASS" mode
        logTelemetry execId "L5" "Verdict" (sprintf "%s: PASS" mode)
    else
        printfn ">>> [OBSERVER] %s Mode: FAIL" mode
        logTelemetry execId "L5" "Verdict" (sprintf "%s: FAIL" mode)
        allPassed <- false

let finalVerdict = if allPassed then "pass" else "fail"
finishExecution execId finalVerdict

printfn ">>> [OBSERVER] Suite Complete. Verdict: %s" finalVerdict
printfn ">>> [OBSERVER] Evidence secured in data/kms/test_manager.db"
