defmodule Indrajaal.Compliance.Policy do
  @moduledoc """
  Ecto schema for policy.

  Implements multi - tenant data model with audit fields.
  Generated by worker - 6.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "compliance" do
    field :name, :string
    field :description, :string
    field :active, :boolean, default: true
    field :metadata, :map, default: %{}

    # Multi - tenant isolation
    field :tenant_id, :binary_id

    # Audit fields
    field :created_by_id, :binary_id
    field :updated_by_id, :binary_id

    # Domain - specific fields
    field :type, :string
    field :status, :string
    field :configuration, :map
    field :tags, {:array, :string}, default: []

    timestamps()
  end

  @doc false
  @spec changeset(any(), any()) :: any()
  def changeset(policy \\ %__MODULE__{}, attrs) do
    policy
    |> cast(attrs, [:name, :description, :active, :metadata])
    |> validate_required([:name])
    |> validate_length(:name, min: 1, max: 255)
    |> validate_length(:description, max: 1000)
  end
end

# Agent: Helper - 2 (General Purpose Agent)
# SOPv5.1 Compliance: ✅ General system coordination and management with cyberne
# Domain: Compliance
# Responsibilities: Template generation, standards enforcement, general coordin
# Multi - Agent Architecture: Integrated with 11 - agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
