defmodule Indrajaal.Observability.ObservabilityBehaviour do
  @moduledoc """
  Observability behavior for monitoring and metrics collection.

  Generated by AEE SOPv5.11 Zero Warnings Engine.
  """

  @callback start_monitoring(term()) :: :ok | {:error, term()}
  @callback stop_monitoring(term()) :: :ok | {:error, term()}
  @callback get_metrics() :: map()
end
