defmodule Indrajaal.Accounts.Account do
  @moduledoc """
  Ash resource for account management.

  Implements multi-tenant data model with audit fields and comprehensive
  account management capabilities.
  Generated by worker-2 with SOPv5.11 cybernetic framework integration.
  """

  use Indrajaal.BaseResource,
    domain: Indrajaal.Accounts,
    table: "accounts"

  use Indrajaal.Multitenancy.TenantResource

  attributes do
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
      public? true
      constraints min_length: 1, max_length: 255
    end

    attribute :description, :string do
      public? true
      constraints max_length: 1000
    end

    attribute :active, :boolean do
      allow_nil? false
      public? true
      default true
    end

    attribute :metadata, :map do
      public? true
      default %{}
    end

    # Domain-specific fields
    attribute :type, :string do
      public? true
      constraints max_length: 100
    end

    attribute :status, :string do
      public? true
      constraints max_length: 100
    end

    attribute :configuration, :map do
      public? true
      default %{}
    end

    attribute :tags, {:array, :string} do
      public? true
      default []
    end

    # Audit fields
    attribute :created_by_id, :uuid do
      public? true
    end

    attribute :updated_by_id, :uuid do
      public? true
    end

    timestamps()
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true

      accept [
        :name,
        :description,
        :active,
        :metadata,
        :type,
        :status,
        :configuration,
        :tags
      ]

      argument :tenant_id, :uuid do
        allow_nil? false
      end

      argument :created_by_id, :uuid do
        allow_nil? false
      end

      change set_attribute(:tenant_id, arg(:tenant_id))
      change set_attribute(:created_by_id, arg(:created_by_id))

      validate present([:name])
    end

    update :update do
      primary? true
      require_atomic? false

      accept [
        :name,
        :description,
        :active,
        :metadata,
        :type,
        :status,
        :configuration,
        :tags
      ]

      argument :updated_by_id, :uuid

      change set_attribute(:updated_by_id, arg(:updated_by_id))
    end
  end

  relationships do
    belongs_to :created_by, Indrajaal.Accounts.User do
      source_attribute :created_by_id
      attribute_public? true
    end

    belongs_to :updated_by, Indrajaal.Accounts.User do
      source_attribute :updated_by_id
      attribute_public? true
    end
  end

  policies do
    bypass always() do
      authorize_if actor_attribute_equals(:role, "admin")
    end

    policy action(:create) do
      authorize_if always()
    end

    policy action(:read) do
      authorize_if always()
    end

    policy action([:update, :destroy]) do
      authorize_if actor_attribute_equals(:role, "admin")
      authorize_if actor_attribute_equals(:role, "operator")
    end
  end

  code_interface do
    define :create
    define :read
    define :update
    define :destroy
  end

  postgres do
    table "accounts"
    repo Indrajaal.Repo

    custom_indexes do
      index [:tenant_id, :active]
      index [:name]
      index [:type]
      index [:status]
      index [:created_by_id]
    end
  end

  # Traditional Ecto changeset for compatibility with existing context code
  @spec changeset(any(), any()) :: any()
  def changeset(account, attrs) do
    account
    |> Ecto.Changeset.cast(attrs, [
      :name,
      :description,
      :active,
      :metadata,
      :type,
      :status,
      :configuration,
      :tags,
      :created_by_id,
      :updated_by_id
    ])
    |> Ecto.Changeset.validate_required([:name])
    |> Ecto.Changeset.validate_length(:name, min: 1, max: 255)
    |> Ecto.Changeset.validate_length(:description, max: 1000)
    |> Ecto.Changeset.validate_length(:type, max: 100)
    |> Ecto.Changeset.validate_length(:status, max: 100)
  end
end

# Agent: Worker - 5 (Security Domain Agent)
# SOPv5.1 Compliance: ✅ User account management and authentication coordination
# Domain: Accounts
# Responsibilities: Security access control, authentication, policy enforcement
# Multi - Agent Architecture: Integrated with 11 - agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
