defmodule IntelitorWeb.Api.Mobile.Config.DevicesView do
  @moduledoc """
  JSON rendering for devices in the Mobile API.

  SOPv5.1 Compliance: ✅
  Generated by: worker-2
  Timestamp: 2025-08-03T20:50:30.936811Z
  """

  use IntelitorWeb, :view

  # alias Intelitor.Devices.Device

  @api_version "v1"

  @spec render(term(), term()) :: term()
  def render("index.json", %{devices: items, total: total, page: page, page_size: page_size}) do
    %{
      status: "success",
      data: %{
        devices: render_many(items, __MODULE__, "device.json"),
        total: total,
        page: page,
        page_size: page_size,
        total_pages: ceil(total / page_size)
      },
      metadata: render_metadata()
    }
  end

  @spec render(any(), any()) :: any()
  def render("show.json", %{device: item}) do
    %{
      status: "success",
      data: %{
        device: render_one(item, __MODULE__, "device.json")
      },
      metadata: render_metadata()
    }
  end

  @spec render(any(), any()) :: any()
  def render("device.json", %{device: item}) do
    %{
      id: item.id,
      name: item.name,
      description: item.description,
      active: item.active,
      metadata: item.metadata || %{},
      created_at: DateTime.to_iso8601(item.inserted_at),
      updated_at: DateTime.to_iso8601(item.updated_at)
    }
    |> add_domain_specific_fields(item)
  end

  @spec render(any(), any()) :: any()
  def render("error.json", %{changeset: changeset}) do
    %{
      status: "error",
      errors: render_changeset_errors(changeset),
      metadata: render_metadata()
    }
  end

  @spec render_metadata() :: any()
  defp render_metadata do
    %{
      api_version: @api_version,
      timestamp: DateTime.utc_now() |> DateTime.to_iso8601()
    }
  end

  @spec render_changeset_errors(term()) :: term()
  defp render_changeset_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {msg, opts} ->
      Enum.reduce(opts, msg, fn {key, value}, acc ->
        String.replace(acc, "%{#{key}}", to_string(value))
      end)
    end)
  end

  @spec add_domain_specific_fields(term(), term()) :: term()
  defp add_domain_specific_fields(base, item) do
    # Add domain-specific fields based on the domain type
    case item do
      %{type: type} -> Map.put(base, :type, type)
      %{status: status} -> Map.put(base, :status, status)
      %{location: location} -> Map.put(base, :location, location)
      _ -> base
    end
  end
end

# Agent: Helper-2 (General Purpose Agent)
# SOPv5.1 Compliance: ✅ General system coordination and management with cyberne
# Domain: Web
# Responsibilities: Template generation, standards enforcement, general coordin
# Multi-Agent Architecture: Integrated with 11-agent coordination system
# Cybernetic Feedback: Active feedback loops for continuous improvement
