# This is an example of what the actual video_streams migration would look like
# when generated by Ash using: mix ash_postgres.generate_migrations

defmodule Indrajaal.Repo.Migrations.CreateVideoStreams do
  @moduledoc """
  Creates video_streams table based on Indrajaal.Video.Stream resource.

  This migration is automatically generated by Ash PostgreSQL adapter
  from the Stream resource definition in lib/indrajaal/video/stream.ex
  """

  use Ecto.Migration

  @spec up() :: any()
  def up do
    create table(:video_streams, primary_key: false) do
      # Multi-tenancy (from TenantResource mixin)
      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "video_streams_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      # Primary key (from uuid_primary_key)
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      # Stream identification attributes
      add :camera_id,
          references(:cameras,
            column: :id,
            name: "video_streams_camera_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :stream_type, :text, null: false, default: "primary"
      add :stream_id, :text, null: false

      # Stream configuration
      add :protocol, :text, null: false, default: "webrtc"
      add :source_url, :text, null: false
      add :output_url, :text
      add :stream_key, :text

      # Video settings
      add :resolution, :text, null: false, default: "1920x1080"
      add :framerate, :bigint, null: false, default: 30
      add :bitrate_kbps, :bigint, null: false, default: 2000
      add :codec, :text, null: false, default: "h264"
      add :profile, :text, default: "baseline"

      # Audio settings
      add :audio_enabled?, :boolean, null: false, default: false
      add :audio_codec, :text, default: "aac"
      add :audio_bitrate_kbps, :bigint, default: 128

      # Stream state
      add :status, :text, null: false, default: "initializing"
      add :started_at, :utc_datetime_usec
      add :stopped_at, :utc_datetime_usec
      add :error_message, :text
      add :reconnect_attempts, :bigint, null: false, default: 0

      # Viewers
      add :viewer_count, :bigint, null: false, default: 0
      add :max_viewers, :bigint, default: 100
      add :viewer_sessions, {:array, :map}, default: []

      # Recording
      add :recording_enabled?, :boolean, null: false, default: false

      add :recording_id,
          references(:video_recordings,
            column: :id,
            name: "video_streams_recording_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      # Transcoding
      add :transcoding_enabled?, :boolean, null: false, default: false
      add :transcoding_profiles, {:array, :map}, default: []

      # Performance metrics (as JSON map)
      add :metrics, :map,
        default: %{
          "dropped_frames" => 0,
          "latency_ms" => 0,
          "bandwidth_usage_mbps" => 0,
          "cpu_usage_percent" => 0,
          "memory_usage_mb" => 0
        }

      add :quality_score, :bigint

      # Access control
      add :public_access?, :boolean, null: false, default: false
      add :access_token, :text
      add :allowed_ips, {:array, :text}, default: []

      # Metadata
      add :metadata, :map, default: %{}

      # Timestamps (from BaseResource)
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    # Indexes from the postgres do block in stream.ex
    create index(:video_streams, [:tenant_id, :camera_id])
    create index(:video_streams, [:stream_id], unique: true)
    create index(:video_streams, [:status])
    create index(:video_streams, [:started_at])
    create index(:video_streams, [:recording_id], where: "recording_id IS NOT NULL")

    create index(:video_streams, [:public_access?],
             name: "streams_public_access_index",
             where: "public_access? = true"
           )

    # Additional indexes for performance
    create index(:video_streams, [:tenant_id, :status])
    create index(:video_streams, [:camera_id, :stream_type])
  end

  @spec down() :: any()
  def down do
    drop constraint(:video_streams, "video_streams_tenant_id_fkey")
    drop constraint(:video_streams, "video_streams_camera_id_fkey")
    drop constraint(:video_streams, "video_streams_recording_id_fkey")

    drop_if_exists index(:video_streams, [:tenant_id, :camera_id])
    drop_if_exists index(:video_streams, [:stream_id])
    drop_if_exists index(:video_streams, [:status])
    drop_if_exists index(:video_streams, [:started_at])
    drop_if_exists index(:video_streams, [:recording_id])
    drop_if_exists index(:video_streams, [:public_access?], name: "streams_public_access_index")
    drop_if_exists index(:video_streams, [:tenant_id, :status])
    drop_if_exists index(:video_streams, [:camera_id, :stream_type])

    drop table(:video_streams)
  end
end
