{application,mix_test_watch,
             [{modules,['Elixir.Mix.Tasks.Test.Watch','Elixir.MixTestWatch',
                        'Elixir.MixTestWatch.Config',
                        'Elixir.MixTestWatch.MessageInbox',
                        'Elixir.MixTestWatch.Path',
                        'Elixir.MixTestWatch.PortRunner',
                        'Elixir.MixTestWatch.Runner',
                        'Elixir.MixTestWatch.Watcher']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,file_system]},
              {description,"Automatically run tests when files change"},
              {registered,[]},
              {vsn,"1.3.0"},
              {mod,{'Elixir.MixTestWatch',[]}}]}.
