defmodule Indrajaal.Accounts.AuthenticationTest do
  @moduledoc """
  TDG test suite for Indrajaal.Accounts.Authentication GenServer.

  ## STAMP Safety Integration
  - SC-HOLON-001: State management
  - SC-CON-002: Authentication security

  ## TPS 5-Level RCA Context
  - L1 Symptom: GenServer start/stop failures
  - L5 Root Cause: Missing OTP supervision config
  """

  # async: false because this starts a named GenServer
  use ExUnit.Case, async: false

  @moduletag :zenoh_nif

  alias Indrajaal.Accounts.Authentication

  describe "Authentication GenServer lifecycle" do
    test "module exists" do
      assert Code.ensure_loaded?(Authentication)
    end

    test "start_link/1 is exported" do
      assert function_exported?(Authentication, :start_link, 1)
    end

    test "can start and stop the GenServer" do
      {:ok, pid} = Authentication.start_link([])
      assert Process.alive?(pid)
      GenServer.stop(pid)
    end

    test "child_spec/1 is generated by use GenServer" do
      assert function_exported?(Authentication, :child_spec, 1)
      spec = Authentication.child_spec([])
      assert is_map(spec)
      assert spec.id == Authentication
    end
  end

  describe "Authentication GenServer callbacks" do
    setup do
      {:ok, pid} = start_supervised({Authentication, []})
      %{pid: pid}
    end

    test "GenServer process is alive after start", %{pid: pid} do
      assert Process.alive?(pid)
    end

    test "GenServer responds to state requests", %{pid: _pid} do
      # Authentication is a named GenServer registered as __MODULE__
      # Just verify the process is reachable
      assert is_pid(Process.whereis(Authentication))
    end
  end

  describe "Constitutional Invariants (Ψ₀)" do
    test "Ψ₀ existence: Authentication module exists" do
      assert Authentication.__info__(:module) == Authentication
    end
  end
end
