defmodule Indrajaal.KMS.Panspermia.Exporter do
  @moduledoc """
  Multi-format knowledge exporter for SMRITI immortality protocol.

  WHAT: Exports holon knowledge state to portable formats for disaster recovery,
  federation seeding, and long-term archival.

  WHY: SC-SMRITI-072 requires the immortality protocol to produce real,
  reconstructable exports. SC-HOLON-016 demands format stability for future
  civilizations to reconstruct holon state.

  CONSTRAINTS:
  - SC-SMRITI-072: Immortality protocol execution
  - SC-HOLON-016: Format stability for reconstruction
  - SC-HOLON-010: Holon MUST be regenerable from exported state

  ## Change History
  | Version | Date       | Author | Change                                    |
  |---------|------------|--------|-------------------------------------------|
  | 21.2.1  | 2026-03-10 | Claude | Fix: real export from SQLite, 3 formats   |
  | 21.0.0  | 2026-01-05 | Claude | Initial stub (dummy content)              |

  Task 44.3.0.0.0
  """
  require Logger

  alias Indrajaal.KMS.SQLite

  @formats [:json, :markdown, :sqlite]

  @doc """
  Exports SMRITI knowledge state to the specified format.

  ## Formats
  - `:json` — Full holon data as JSON (machine-readable, portable)
  - `:markdown` — Human-readable knowledge summary
  - `:sqlite` — Direct SQLite file copy (fastest, complete fidelity)

  Returns `{:ok, path}` on success.
  """
  @spec export(atom(), String.t(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def export(format, output_dir, opts \\ []) when format in @formats do
    File.mkdir_p!(output_dir)
    db_path = Keyword.get(opts, :db_path, get_db_path())

    case format do
      :json -> export_json(db_path, output_dir)
      :markdown -> export_markdown(db_path, output_dir)
      :sqlite -> export_sqlite(db_path, output_dir)
    end
  end

  @doc "Returns supported export formats."
  @spec formats() :: [atom()]
  def formats, do: @formats

  # --- JSON Export ---

  defp export_json(db_path, output_dir) do
    with {:ok, holons} <- query_all_holons(db_path),
         {:ok, events} <- query_all_events(db_path) do
      export_data = %{
        format: "smriti-export",
        version: "1.0.0",
        exported_at: DateTime.to_iso8601(DateTime.utc_now()),
        source_db: db_path,
        holon_count: length(holons),
        event_count: length(events),
        holons: holons,
        evolution_events: events
      }

      path = Path.join(output_dir, "smriti_export.json")

      case File.write(path, Jason.encode!(export_data, pretty: true)) do
        :ok ->
          Logger.info("[Panspermia] Exported #{length(holons)} holons to #{path}")
          {:ok, path}

        {:error, reason} ->
          {:error, {:write_failed, reason}}
      end
    end
  end

  # --- Markdown Export ---

  defp export_markdown(db_path, output_dir) do
    with {:ok, holons} <- query_all_holons(db_path),
         {:ok, events} <- query_all_events(db_path) do
      content = build_markdown(holons, events, db_path)
      path = Path.join(output_dir, "smriti_export.md")

      case File.write(path, content) do
        :ok ->
          Logger.info("[Panspermia] Exported markdown summary to #{path}")
          {:ok, path}

        {:error, reason} ->
          {:error, {:write_failed, reason}}
      end
    end
  end

  defp build_markdown(holons, events, db_path) do
    """
    # SMRITI Knowledge Export

    **Exported**: #{DateTime.to_iso8601(DateTime.utc_now())}
    **Source**: #{db_path}
    **Holons**: #{length(holons)}
    **Evolution Events**: #{length(events)}

    ## Holons

    #{Enum.map_join(holons, "\n", &format_holon_md/1)}

    ## Evolution Summary

    #{format_evolution_summary(events)}

    ---
    *Generated by Indrajaal Panspermia Exporter v21.2.1*
    """
  end

  defp format_holon_md(holon) when is_map(holon) do
    id = holon[:id] || holon["id"] || "unknown"
    name = holon[:name] || holon["name"] || "unnamed"
    type = holon[:type] || holon["type"] || "unknown"
    "- **#{name}** (#{id}) — type: #{type}"
  end

  defp format_evolution_summary(events) do
    type_counts =
      events
      |> Enum.group_by(fn e -> e[:type] || e["type"] || "unknown" end)
      |> Enum.map(fn {type, evts} -> "- #{type}: #{length(evts)} events" end)
      |> Enum.join("\n")

    if type_counts == "", do: "No evolution events recorded.", else: type_counts
  end

  # --- SQLite Export (file copy) ---

  defp export_sqlite(db_path, output_dir) do
    if File.exists?(db_path) do
      timestamp = Calendar.strftime(DateTime.utc_now(), "%Y%m%dT%H%M%S")
      dest = Path.join(output_dir, "smriti_export_#{timestamp}.db")

      case File.cp(db_path, dest) do
        :ok ->
          # Also copy WAL and SHM if they exist (active DB state)
          copy_if_exists("#{db_path}-wal", "#{dest}-wal")
          copy_if_exists("#{db_path}-shm", "#{dest}-shm")
          Logger.info("[Panspermia] Exported SQLite database to #{dest}")
          {:ok, dest}

        {:error, reason} ->
          {:error, {:copy_failed, reason}}
      end
    else
      {:error, {:source_not_found, db_path}}
    end
  end

  defp copy_if_exists(src, dest) do
    if File.exists?(src), do: File.cp(src, dest)
  end

  # --- Queries ---

  defp query_all_holons(db_path) do
    unless File.exists?(db_path) do
      {:ok, []}
    else
      case SQLite.query(db_path, "SELECT * FROM holons ORDER BY created_at") do
        {:ok, rows} -> {:ok, rows}
        {:error, _} -> {:ok, []}
      end
    end
  rescue
    _ -> {:ok, []}
  end

  defp query_all_events(db_path) do
    unless File.exists?(db_path) do
      {:ok, []}
    else
      case SQLite.query(db_path, "SELECT * FROM evolution_events ORDER BY timestamp") do
        {:ok, rows} -> {:ok, rows}
        {:error, _} -> {:ok, []}
      end
    end
  rescue
    _ -> {:ok, []}
  end

  defp get_db_path do
    Application.get_env(:indrajaal, :smriti_db_path, "data/kms/smriti.db")
  end
end
